/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations, SchemaComponentsSchemas } from "./schema";
export interface SchemaSchemaComponentsSchemas1 {

        HandoffDraftRequest: {
            title?: string;
            /** Format: uuid */
            targetTaskId: string;
            /** Format: uuid */
            receiverIdentityId: string;
            /** Format: uuid */
            workflowId?: string;
            /** @enum {string} */
            kind: "dependency" | "stage";
            sources: {
                /** Format: uuid */
                sourceTaskId: string;
                /** Format: uuid */
                senderIdentityId: string;
            }[];
        };

        HandoffSourceRevisionRequest: {
            summary: string;
            /** Format: uuid */
            submissionId?: string;
            materialVersionIds?: string[];
            /** Format: uuid */
            reportId?: string;
        };

        HandoffSendRequest: {
            sourceVersion: number;
            reviewHash: string;
        };

        HandoffDecisionRequest: {
            sourceVersion: number;
            reviewHash: string;
            /** @enum {string} */
            decision: "accept" | "reject";
            reason?: string;
            expectedVersion?: number;
        };

        BugDetails: {
            /** Format: uuid */
            sourceTaskId?: string;
            observedReleaseRef?: string;
            environment: string;
            steps: string;
            expected: string;
            actual: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
        };

        ReleaseReport: {
            /** Format: uuid */
            id: string;
            versionLabel: string;
            environment: string;
            url?: string | null;
            /** @enum {string} */
            status: "success" | "partial" | "failed";
            repositoryCommits?: {
                /** Format: uuid */
                repositoryId: string;
                branch?: string;
                commit: string;
            }[];
            /** Format: uuid */
            submissionId?: string | null;
            /** Format: uuid */
            reportedBy: string;
            /** Format: date-time */
            createdAt: string;
        };

        ReleaseReportRequest: {
            versionLabel: string;
            environment: string;
            url?: string;
            /** @enum {string} */
            status: "success" | "partial" | "failed";
            repositoryCommits?: {
                /** Format: uuid */
                repositoryId: string;
                branch?: string;
                commit: string;
            }[];
            /** Format: uuid */
            submissionId?: string;
        };

        FixPropagationRequest: {
            targetReleaseRefs: string[];
        };

        AuditEntry: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            actorType: "user" | "operator" | "agent" | "system";
            /** Format: uuid */
            actorUserId?: string | null;
            /** Format: uuid */
            identityId?: string | null;
            /** @enum {string} */
            source: "web" | "cli" | "delegate" | "timeout" | "worker" | "operator" | "agent";
            operation: string;
            objectType: string;
            objectId?: string;
            /** Format: uuid */
            reviewId?: string | null;
            reason?: string | null;
            /** Format: date-time */
            occurredAt: string;
        };

        WorkflowPresetNode: {
            /** @enum {string} */
            kind?: "activity" | "decision";
            phase?: components["schemas"]["PresetText"];
            id: string;
            name: components["schemas"]["PresetText"];
            responsibility: components["schemas"]["PresetText"];
        };

        WorkflowPreset: {
            /** @enum {string} */
            complexity?: "basic" | "advanced";
            sources?: {
                title: components["schemas"]["PresetText"];
                /** Format: uri */
                url: string;
            }[];
            id: string;
            name: components["schemas"]["PresetText"];
            summary: components["schemas"]["PresetText"];
            instructions: components["schemas"]["PresetText"];
            nodes: components["schemas"]["WorkflowPresetNode"][];
            edges: {
                from: string;
                to: string;
                /** @enum {string} */
                kind?: "sequence" | "feedback";
                label?: components["schemas"]["PresetText"];
            }[];
            roleIds: string[];
            scenarioIds: string[];
        };

        WorkflowScenario: {
            id: string;
            name: components["schemas"]["PresetText"];
            description: components["schemas"]["PresetText"];
            workflowIds: string[];
        };

        WorkflowPresetCatalog: {
            version: string;
            workflows: components["schemas"]["WorkflowPreset"][];
            scenarios: components["schemas"]["WorkflowScenario"][];
            roles: {
                id: string;
                name: components["schemas"]["PresetText"];
            }[];
        };

        ImportWorkflowPresetsRequest: {
            catalogVersion: string;
            scenarioId: string;
            workflowIds: string[];
            /** @enum {string} */
            locale: "zh-CN" | "en";
        };

        ImportedWorkflowPresets: {
            items: components["schemas"]["Workflow"][];
            skipped: {
                presetId: string;
                /** Format: uuid */
                workflowId: string;
                name: string;
            }[];
        };

        WorkCapabilities: {
            editDraft: boolean;
            discardDraft: boolean;
            proposeChange: boolean;
            skip: boolean;
            restore: boolean;
        };

        ExceptionWaiver: {
            /** Format: uuid */
            taskId: string;
            /** Format: uuid */
            requirementId: string;
            fingerprint: string;
        };

        ExecutionException: {
            /** Format: uuid */
            id: string;
            reason: string;
            /** @enum {string} */
            previousStatus: "ready" | "working" | "delivered" | "rework";
            /** Format: uuid */
            actorUserId: string;
            /** Format: date-time */
            createdAt: string;
            waivers: components["schemas"]["ExceptionWaiver"][];
        };

        ExceptionImpact: {
            /** Format: uuid */
            taskId: string;
            /** Format: uuid */
            planId: string | null;
            title: string;
            status: string;
            version: number;
            alreadyStarted: boolean;
            requirements: components["schemas"]["TaskRequirement"][];
        };

        ExecutionReview: {
            /** Format: uuid */
            taskId: string;
            targetVersion: number;
            /** @enum {string} */
            operation: "skip" | "restore";
            reviewHash: string;
            title: string;
            current: components["schemas"]["ExecutionException"] | null;
            affectedTasks: components["schemas"]["ExceptionImpact"][];
            referencingPlanIds: string[];
        };

        ExecutionCommand: {
            expectedVersion: number;
            reviewHash: string;
            reason: string;
            waivers?: components["schemas"]["ExceptionWaiver"][];
            acknowledgeStarted?: boolean;
        };

        DraftDiscardReview: {
            /** Format: uuid */
            targetId: string;
            /** @enum {string} */
            targetType: "task" | "plan";
            targetVersion: number;
            title: string;
            reviewHash: string;
            tasks: components["schemas"]["ExceptionImpact"][];
            blockers: components["schemas"]["WorkBlocker"][];
        };

        WorkDraftUpdate: {
            expectedVersion: number;
            fields: {
                [key: string]: unknown;
            };
        };

        WorkBlocker: {
            phase: string;
            objectType: string;
            objectId: string;
            reason: string;
        };
}
