/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations } from "./schema";
export interface SchemaOperations0 {

    startAgentRun: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description 已登记批次/运行引用（异步执行）。 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: uuid */
                            batchId: string;
                            runId?: string | null;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 重复源或上下文版本冲突。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 预算耗尽（BUDGET_EXHAUSTED），需合法续开。 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };

    getAgentRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AgentRun"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    subscribeRunEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    cancelAgentRun: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                runId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRunRequest"];
            };
        };
        responses: {
            /** @description 已请求取消。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            cancelling: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    extendDiscussionBatch: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                batchId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchExtensionRequest"];
            };
        };
        responses: {
            /** @description 已续开。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            maxRounds: number;
                            extension: number;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };

    createConfirmationIntent: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationIntentRequest"];
            };
        };
        responses: {
            /** @description 意图已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ConfirmationIntent"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    getConfirmationIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                intentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 意图状态与 resultRef。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ConfirmationIntent"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    confirmIntent: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                intentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIntentRequest"];
            };
        };
        responses: {
            /** @description 确认结果（committed/rejected）与 resultRef。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ConfirmationIntent"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    register: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功并建立会话（Set-Cookie）。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResult"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description 邮箱已占用（EMAIL_IN_USE）或幂等冲突。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };

    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功（Set-Cookie）。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResult"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };

    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话有效。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SessionInfo"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销；会话已过期也允许清本地 Cookie。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            revoked: boolean;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedAuthVersion: number;
                };
            };
        };
        responses: {
            /** @description 撤销数量。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            revokedSessions: number;
                            revokedGrants: number;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    recoverPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoverRequest"];
            };
        };
        responses: {
            /** @description 完成；旧会话与授权已撤销。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            completed: boolean;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };

    createDeviceAuthorization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceAuthorizationRequest"];
            };
        };
        responses: {
            /** @description 已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeviceAuthorization"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };

    pollDeviceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceTokenRequest"];
            };
        };
        responses: {
            /** @description pending/slow_down 状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeviceTokenPending"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            /** @description 授权完成，返回 token 对。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TokenPair"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            /** @description denied 或 expired。 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };

    confirmDeviceAuthorization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceConfirmRequest"];
            };
        };
        responses: {
            /** @description 确认结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeviceConfirmResult"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 新 token 对。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TokenPair"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };

    getDeviceAuthorization: {
        parameters: {
            query: {
                userCode: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device name, requested scopes and expiry for human review. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createGlobalConfirmationIntent: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationIntentRequest"];
            };
        };
        responses: {
            /** @description 意图已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ConfirmationIntent"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    getGlobalConfirmationIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 意图状态与 resultRef。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ConfirmationIntent"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    confirmGlobalIntent: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                intentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmIntentRequest"];
            };
        };
        responses: {
            /** @description 确认结果（committed/rejected）与 resultRef。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ConfirmationIntent"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    listHandoffs: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                state?: "waiting" | "accepted" | "needs_revision";
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 交接分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Handoff"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createHandoff: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffDraftRequest"];
            };
        };
        responses: {
            /** @description 交接草稿。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Handoff"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createHandoffSourceRevision: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                handoffId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffSourceRevisionRequest"];
            };
        };
        responses: {
            /** @description 新来源版本。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["HandoffSource"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    sendHandoffSource: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                handoffId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffSendRequest"];
            };
        };
        responses: {
            /** @description 已发送。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["HandoffSource"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    decideHandoffSource: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                handoffId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffDecisionRequest"];
            };
        };
        responses: {
            /** @description 决定结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["HandoffSource"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    sendHandoffReminder: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                handoffId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                };
            };
        };
        responses: {
            /** @description 已登记提醒。 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            reminded: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };

    listReleaseReports: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 上报分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["ReleaseReport"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createReleaseReport: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseReportRequest"];
            };
        };
        responses: {
            /** @description 已登记。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ReleaseReport"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listAudit: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                objectType?: string;
                objectId?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审计分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["AuditEntry"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    subscribeProjectEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream；事件按项目 seq 有序，eventId 去重。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 游标过期（EVENT_CURSOR_EXPIRED），需重新 bootstrap。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };

    getMaterialVersionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 不可变材料版本与清单 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MaterialVersion"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    downloadMaterialVersionById: {
        parameters: {
            query?: {
                /** @description HTML 包内的相对路径条目。 */
                entry?: string;
            };
            header?: {
                Range?: string;
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 内容流。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description 范围内容。 */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    updateMe: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description 更新后的用户。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PublicUser"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description 修改成功，返回轮换后的会话。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResult"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listSessions: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["SessionSummary"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            revoked: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    listClientGrants: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 授权分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["ClientGrant"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    revokeClientGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已撤销。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            revoked: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    listMyInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 邀请分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Invitation"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listMyActions: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                projectId?: string;
                kind?: "submit" | "approve" | "receive" | "accept" | "revise" | "reopen";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 待办分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["PendingAction"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listNotifications: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                unreadOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 提醒分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Notification"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    markNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkNotificationsRequest"];
            };
        };
        responses: {
            /** @description 已标记数量。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            marked: number;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listMembers: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成员分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["ProjectMember"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    updateMemberRole: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRequest"];
            };
        };
        responses: {
            /** @description 更新后的成员。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectMember"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    removeMember: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveMemberRequest"];
            };
        };
        responses: {
            /** @description 移除结果与受影响职责。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RemoveMemberResult"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    listInvitations: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 邀请分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Invitation"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationRequest"];
            };
        };
        responses: {
            /** @description 已创建（含一次性可复制的邀请链接）。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Invitation"] & {
                            inviteUrl?: string;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    revokeInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeInvitationRequest"];
            };
        };
        responses: {
            /** @description 已撤销。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Invitation"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    resolveInvitation: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 邀请预览。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["InvitationResolve"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
