/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations } from "./schema";
export interface SchemaComponents0 {

    schemas: {
        StartRunRequest: {
            /** Format: uuid */
            sourceSubmissionId: string;
            expectedContextVersion?: number;
            reason?: string;
        };
        AgentRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            batchId?: string | null;
            /** Format: uuid */
            roundId?: string | null;
            /** Format: uuid */
            parentRunId?: string | null;
            /** Format: uuid */
            identityId: string;
            identityName?: string;
            bindingVersion?: number | null;
            /** @enum {string} */
            state: "queued" | "provisioning" | "running" | "waiting_children" | "waiting_human" | "waiting_material" | "succeeded" | "failed" | "cancelled";
            budget?: {
                [key: string]: unknown;
            };
            waitingFor?: string[];
            artifactRefs?: {
                [key: string]: unknown;
            }[];
            /** Format: date-time */
            createdAt: string;
        };
        RunEvent: {
            seq: number;
            /** Format: uuid */
            runId?: string;
            type: string;
            payload?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            occurredAt: string;
        };
        CancelRunRequest: {
            expectedVersion: number;
            reason: string;
        };
        BatchExtensionRequest: {
            extraRounds: number;
            expectedVersion: number;
            reason: string;
        };
        ConfirmationIntentRequest: {
            /** @enum {string} */
            operation: "proposal.decision" | "task.acceptance" | "task.reopen" | "plan.acceptance" | "plan.reopen" | "handoff.send" | "handoff.decision" | "project.create" | "workflow.publish";
            /** Format: uuid */
            objectId: string;
            reviewHash: string;
            /** @description 该 operation 的命令载荷快照；服务端计算规范化哈希。 */
            payload?: {
                [key: string]: unknown;
            };
        };
        ConfirmationIntent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            state: "pending" | "committed" | "rejected" | "expired" | "stale";
            operation: string;
            /** Format: uuid */
            objectId: string;
            requestedBy?: {
                /** Format: uuid */
                userId: string;
                deviceName: string | null;
            };
            /** Format: uri */
            confirmUrl?: string | null;
            resultRef?: string | null;
            /** Format: date-time */
            expiresAt: string;
        };
        ConfirmIntentRequest: {
            intentHash: string;
            /** @enum {string} */
            decision: "approve" | "reject";
            csrfToken?: string;
        };
        PublicUser: {
            /** Format: uuid */
            id: string;
            displayName: string;
            /** @description 登录邮箱（未验证的登录标识，非已验证企业身份）。 */
            email: string;
            /** @enum {string} */
            locale: "zh-CN" | "en";
            /** @enum {string} */
            status: "active" | "disabled";
            version: number;
            /** Format: date-time */
            createdAt: string;
        };
        RegisterRequest: {
            displayName: string;
            email: string;
            /** @description 允许粘贴与密码管理器，不限制字符类别。 */
            password: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        AuthResult: {
            user: components["schemas"]["PublicUser"];
            /** Format: date-time */
            sessionExpiresAt: string;
        };
        SessionInfo: {
            user: components["schemas"]["PublicUser"];
            /** Format: date-time */
            expiresAt: string;
            /** @description 与会话绑定的 CSRF token；写请求必须以 X-CSRF-Token 头回传。 */
            csrfToken: string;
        };
        UpdateMeRequest: {
            expectedVersion: number;
            displayName?: string;
            /** @enum {string} */
            locale?: "zh-CN" | "en";
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        RecoverRequest: {
            recoveryCode: string;
            newPassword: string;
        };
        SessionSummary: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            current: boolean;
        };
        DeviceAuthorizationRequest: {
            deviceName: string;
            requestedScopes: string[];
            /** @description 空/缺省表示仅本人项目列表，后续按需授权。 */
            projectScope?: string[];
        };
        DeviceAuthorization: {
            deviceCode: string;
            userCode: string;
            /** Format: uri-reference */
            verificationUri: string;
            /** @description 秒。 */
            expiresIn: number;
            /** @description 轮询间隔秒数。 */
            interval: number;
        };
        DeviceTokenRequest: {
            deviceCode: string;
        };
        DeviceTokenPending: {
            /** @enum {string} */
            status: "pending" | "slow_down";
            interval?: number;
        };
        TokenPair: {
            accessToken: string;
            /** Format: date-time */
            accessExpiresAt: string;
            refreshToken: string;
            /** Format: date-time */
            refreshExpiresAt: string;
            scopes: string[];
        };
        RefreshRequest: {
            refreshToken: string;
        };
        DeviceConfirmRequest: {
            userCode: string;
            approved: boolean;
            scopes?: string[];
            projectScope?: string[];
        };
        DeviceConfirmResult: {
            /** @enum {string} */
            state: "approved" | "denied";
        };
        ClientGrant: {
            /** Format: uuid */
            id: string;
            deviceName: string;
            scopes: string[];
            projectScope?: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            revokedAt: string | null;
            /** Format: date-time */
            lastUsedAt?: string | null;
        };
        SystemInfo: {
            name: string;
            version: string;
            commit?: string;
            protocolVersion: string;
            schemaRange: string;
            capabilities?: {
                [key: string]: unknown;
            };
        };
        Capabilities: {
            registerEnabled: boolean;
            uploadLimits: components["schemas"]["UploadLimits"];
            discussionRounds: {
                default: number;
                min: number;
                max: number;
            };
            approvalTimeoutSeconds?: {
                default: number;
                min: number;
                max: number;
            };
            confirmation: {
                browserConfirmRequired: boolean;
                intentTtlSeconds?: number;
            };
            modelsConfigured?: boolean;
            sandboxConfigured?: boolean;
        };
        UploadLimits: {
            maxFileBytes: number;
            maxBundleBytes: number;
            maxFilesPerSubmission: number;
            maxTextBytes: number;
            partSizeBytes: number;
        };
        RequestMeta: {
            requestId: string;
            /** Format: date-time */
            serverTime: string;
            /**
             * Format: int64
             * @description 当前项目事件序列游标，仅项目资源响应返回。
             */
            eventCursor?: number;
        };
        AffectedResource: {
            type: string;
            id: string;
            version: number;
        };
        CommandMeta: components["schemas"]["RequestMeta"] & {
            affected?: components["schemas"]["AffectedResource"][];
        };
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** @description 兜底文案；客户端按 code+details 映射，不解析句子。 */
            message: string;
            /** @description 结构化错误详情，按 code 不同而不同。 */
            details?: unknown;
            /** @default false */
            retryable: boolean;
        };
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "UNSUPPORTED_SCHEMA" | "INVALID_REFERENCE" | "EMAIL_IN_USE" | "UNAUTHENTICATED" | "SESSION_EXPIRED" | "GRANT_REVOKED" | "FORBIDDEN" | "HUMAN_CONFIRMATION_REQUIRED" | "NOT_FOUND" | "VERSION_CONFLICT" | "REVIEW_STALE" | "DEPENDENCY_CHANGED" | "INVALID_TRANSITION" | "IDEMPOTENCY_CONFLICT" | "SOURCE_VERSION_CONFLICT" | "EVENT_CURSOR_EXPIRED" | "REQUIREMENT_UNMET" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA" | "RATE_LIMITED" | "BUDGET_EXHAUSTED" | "DEPENDENCY_UNAVAILABLE" | "MODEL_UNAVAILABLE" | "SANDBOX_UNAVAILABLE" | "INTERNAL_ERROR";
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
            requestId: string;
        };
        FieldIssue: {
            path: string;
            code: string;
        };
        ListMeta: {
            /** @description 下一页游标；null 表示没有更多数据。 */
            nextCursor?: string | null;
        };
        Topic: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            kind: "project_room" | "discussion" | "handoff";
            contextType?: string | null;
            /** Format: uuid */
            contextId?: string | null;
            lastMessageSeq?: number;
            links?: {
                /** @enum {string} */
                objectType: "plan" | "task";
                /** Format: uuid */
                objectId: string;
            }[];
            /** Format: date-time */
            createdAt: string;
        };
        CreateTopicRequest: {
            title: string;
            initialMessage?: string;
            links?: {
                /** @enum {string} */
                objectType: "plan" | "task";
                /** Format: uuid */
                objectId: string;
            }[];
        };
        TopicLinkRequest: {
            expectedVersion: number;
            targetRefs: {
                /** @enum {string} */
                objectType: "plan" | "task";
                /** Format: uuid */
                objectId: string;
            }[];
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            topicId: string;
            seq: number;
            /** @enum {string} */
            kind: "human" | "agent" | "system";
            /** Format: uuid */
            authorUserId?: string | null;
            authorDisplayName?: string | null;
            /** Format: uuid */
            identityId?: string | null;
            identityName?: string | null;
            /** @enum {string|null} */
            source?: "web" | "cli" | "platform" | null;
            /** Format: uuid */
            submissionId?: string | null;
            /** Format: uuid */
            runId?: string | null;
            content: string;
            /** @enum {string} */
            state: "committed" | "superseded";
            materialVersionIds?: string[];
            /** Format: date-time */
            createdAt: string;
        };
        Submission: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            clientSubmissionId: string;
            /** @enum {string} */
            purpose: "message" | "progress" | "delivery" | "material";
            /** @enum {string} */
            source: "web" | "cli" | "agent";
            text?: string;
            /** Format: uuid */
            topicId?: string | null;
            /** Format: uuid */
            taskId?: string | null;
            /** Format: uuid */
            identityId?: string | null;
            /** Format: uuid */
            actorUserId?: string | null;
            /** @enum {string} */
            status: "preparing" | "ready" | "failed";
            materialVersionIds?: string[];
            codeRefs?: components["schemas"]["CodeRef"][];
            /** Format: uuid */
            messageId?: string | null;
            /** Format: uuid */
            reportId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CodeRef: {
            /** Format: uuid */
            repositoryId: string;
            branch?: string;
            /** @description 完整 commit SHA；服务端固定 verification=reported。 */
            commit?: string;
            pullUrl?: string;
            note?: string;
            /** @enum {string} */
            verification: "reported";
        };
        SubmissionRequest: {
            /** Format: uuid */
            clientSubmissionId: string;
            /** @enum {string} */
            purpose: "message" | "progress" | "delivery" | "material";
            text: string;
            /** Format: uuid */
            topicId?: string;
            /** Format: uuid */
            taskId?: string;
            /** Format: uuid */
            identityId?: string;
            expectedTaskVersion?: number;
            materialVersionIds?: string[];
            codeRefs?: components["schemas"]["CodeRef"][];
        };
        UploadSession: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            state: "open" | "completed" | "cancelled" | "expired";
            /** @enum {string} */
            kind: "file" | "html_bundle";
            name?: string;
            expectedSize: number;
            /** @description 完整文件 SHA256 十六进制。 */
            checksum: string;
            mime?: string;
            /** @description 分片大小字节数（推荐 8MiB）。 */
            partSize: number;
            partCount?: number;
            /** Format: uuid */
            materialId?: string | null;
            /** Format: uuid */
            resultVersionId?: string | null;
            /** Format: date-time */
            expiresAt: string;
        };
        CreateUploadRequest: {
            name: string;
            size: number;
            sha256: string;
            mime: string;
            /** @enum {string} */
            kind: "file" | "html_bundle";
            /** @description HTML 包入口相对路径。 */
            entrypoint?: string;
        };
        CompleteUploadRequest: {
            parts: {
                partNumber: number;
                sha256: string;
            }[];
            /** @description 针对已有材料派生发布时的当前版本号；落后返回 SOURCE_VERSION_CONFLICT。 */
            sourceVersion?: number;
        };
        Material: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            kind: "file" | "html_bundle" | "text";
            /** @enum {string} */
            visibility: "project";
            /** Format: uuid */
            currentVersionId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        MaterialVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            materialId?: string;
            revision: number;
            /** @enum {string} */
            state: "staged" | "ready" | "unavailable";
            sha256: string;
            size: number;
            mime?: string;
            entrypoint?: string | null;
            /** @description HTML 包的相对路径清单。 */
            entries?: {
                relativePath: string;
                size: number;
                sha256: string;
            }[];
            authorId?: string | null;
            runId?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PreviewSession: {
            /**
             * Format: uri
             * @description 隔离 preview origin 的短时 URL。
             */
            previewUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ProjectEvent: {
            /** Format: uuid */
            eventId: string;
            /** Format: uuid */
            projectId: string;
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            type: "message.committed" | "proposal.changed" | "task.changed" | "plan.changed" | "handoff.changed" | "material.ready" | "material.unavailable" | "workflow.published" | "membership.changed" | "run.changed" | "notification.created";
            objectType: string;
            objectId: string;
            version?: number;
            /** Format: date-time */
            occurredAt: string;
            changedFields?: string[];
            refs?: {
                [key: string]: unknown;
            };
        };
        Notification: {
            /** Format: uuid */
            id: string;
            type: string;
            objectRef?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            eventId?: string;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        MarkNotificationsRequest: {
            ids?: string[];
            cursor?: string;
        };
        PendingAction: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "submit" | "approve" | "receive" | "accept" | "revise" | "reopen";
            /** Format: uuid */
            projectId?: string;
            /** @enum {string} */
            objectType: "proposal" | "handoff" | "task" | "plan" | "topic";
            /** Format: uuid */
            objectId: string;
            /** Format: uuid */
            reviewId?: string | null;
            /** Format: date-time */
            dueAt?: string | null;
            summary?: string;
            /** Format: date-time */
            createdAt: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            /** @enum {string} */
            kind: "software" | "design";
            /** @enum {string} */
            status: "active" | "archived";
            /**
             * @description 当前用户在该项目中的角色（owner/manager/member）；非成员为 null。
             * @enum {string}
             */
            role: "owner" | "manager" | "member";
            roleVersion?: number;
            maxDiscussionRounds?: number;
            approvalTimeoutSeconds?: number;
            /** Format: uuid */
            defaultModelId?: string | null;
            sandboxProfileId?: string | null;
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateProjectRequest: {
            title: string;
            description?: string;
            /**
             * @default software
             * @enum {string}
             */
            kind: "software" | "design";
            maxDiscussionRounds?: number;
            approvalTimeoutSeconds?: number;
            /** Format: uuid */
            defaultModelId?: string;
        };
        UpdateProjectRequest: {
            expectedVersion: number;
            title?: string;
            description?: string;
            maxDiscussionRounds?: number;
            approvalTimeoutSeconds?: number;
            /** Format: uuid */
            defaultModelId?: string | null;
        };
        ProjectBootstrap: {
            project: components["schemas"]["Project"];
            /** @description 当前用户在本项目的身份与当前绑定。 */
            identities: components["schemas"]["Identity"][];
            pendingActionsCount?: number;
            /** Format: int64 */
            eventCursor: number;
            summary?: {
                [key: string]: unknown;
            };
        };
        ArchiveRequest: {
            expectedVersion: number;
            reason: string;
        };
        ProjectMember: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            email: string;
            /** @enum {string} */
            role: "owner" | "manager" | "member";
            /** @enum {string} */
            state: "active" | "left" | "removed";
            /** Format: date-time */
            joinedAt: string;
            identities?: components["schemas"]["Identity"][];
        };
        UpdateMemberRequest: {
            expectedVersion: number;
            /** @enum {string} */
            role: "manager" | "member";
        };
        RemoveMemberRequest: {
            expectedVersion: number;
            reason: string;
        };
        RemoveMemberResult: {
            affectedResponsibilities: {
                /** Format: uuid */
                identityId: string;
                /** @enum {string} */
                resolution: "transferred" | "disabled" | "pending";
            }[];
        };
        OwnerTransferRequest: {
            /** Format: uuid */
            targetUserId: string;
            expectedVersion: number;
        };
        OwnerTransfer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            fromUserId: string;
            /** Format: uuid */
            toUserId: string;
            /** @enum {string} */
            state: "pending" | "accepted" | "declined" | "cancelled" | "expired";
            projectVersion?: number;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            confirmedAt?: string | null;
        };
        OwnerTransferDecisionRequest: {
            expectedVersion: number;
            /** @enum {string} */
            decision: "accept" | "decline";
        };
        Invitation: {
            /** Format: uuid */
            id: string;
            targetEmail: string;
            /** Format: uuid */
            targetUserId?: string | null;
            /** @enum {string} */
            state: "pending" | "accepted" | "declined" | "revoked" | "expired";
            /** Format: uuid */
            inviterUserId: string;
            positions: components["schemas"]["PositionSummary"][];
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            acceptedUserId?: string | null;
        };
        CreateInvitationRequest: {
            targetEmail: string;
            positionIds: string[];
        };
        RevokeInvitationRequest: {
            expectedVersion: number;
        };
        InvitationResolve: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            projectTitle: string;
            positions: string[];
            inviterDisplayName: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description 当前登录邮箱是否与受邀邮箱一致。 */
            emailMatches: boolean;
        };
        InvitationDecisionRequest: {
            expectedVersion: number;
            token?: string;
        };
        PositionSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            status: "active" | "archived";
            currentVersion: number;
            publicSummary?: string;
        };
        Position: components["schemas"]["PositionSummary"] & {
            /** @description 公开职责提示词（所有人可见）。 */
            prompt: string;
            /** Format: uuid */
            modelId?: string | null;
            revision: number;
            nodeBindings: {
                /** Format: uuid */
                workflowId: string;
                nodeId: string;
            }[];
        };
        PositionDraftRequest: {
            name: string;
            prompt?: string;
            publicSummary?: string;
            /** Format: uuid */
            modelId?: string | null;
            nodeBindings?: {
                /** Format: uuid */
                workflowId: string;
                nodeId: string;
            }[];
        };
        UpdatePositionRequest: {
            expectedVersion: number;
            name?: string;
            prompt?: string;
            publicSummary?: string;
            /** Format: uuid */
            modelId?: string | null;
            nodeBindings?: {
                /** Format: uuid */
                workflowId: string;
                nodeId: string;
            }[];
        };
        Identity: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "coordinator" | "position";
            /** @enum {string} */
            status: "active" | "suspended";
            /** Format: uuid */
            templateId?: string | null;
            /** @description 当前有效绑定；coordinator 或未绑定为 null。 */
            currentBinding?: {
                bindingVersion: number;
                /** Format: uuid */
                userId: string;
                displayName: string;
                /** Format: date-time */
                validFrom: string;
            } | null;
            currentBindingVersion: number;
            positionName?: string | null;
        };
        CreateIdentityRequest: {
            /** Format: uuid */
            positionId: string;
            /** Format: uuid */
            userId: string;
        };
        ReplaceIdentityRequest: {
            expectedBindingVersion: number;
            /** Format: uuid */
            newUserId: string;
            reason: string;
        };
        PersonalPreferences: {
            revision: number;
            prompt: string;
        };
        UpdatePersonalPreferencesRequest: {
            expectedRevision: number;
            prompt: string;
        };
        ModelSummary: {
            /** Format: uuid */
            id: string;
            displayName: string;
            provider: string;
            enabled: boolean;
            capabilities: {
                toolCalling: boolean;
                vision?: boolean;
                streaming: boolean;
            };
            limits: {
                maxInputTokens: number;
                maxOutputTokens: number;
            };
        };
        WorkflowNode: {
            /** @description 稳定节点 ID，发布后不可复用为不同含义。 */
            id: string;
            name: string;
            responsibility: string;
            /** @description 项目 owner 发布的节点代批授权；不扩大其他节点权限。 */
            delegationUserIds?: string[];
            allowedPositionIds: string[];
            /** @enum {string} */
            defaultApprovalPolicy: "all" | "none";
        };
        WorkflowHardRule: {
            /** @description 缺省适用于整个流程；指定时仅约束该节点。 */
            nodeId?: string;
            /** @enum {string} */
            kind: "task_acceptance" | "handoff_receipt" | "material_ready";
            /** @enum {string} */
            phase?: "start" | "accept" | "both";
            targetId?: string;
        };
        WorkflowDraftBody: {
            name: string;
            instructions?: string;
            nodes: components["schemas"]["WorkflowNode"][];
            advisoryEdges?: {
                from: string;
                to: string;
            }[];
            hardRules?: components["schemas"]["WorkflowHardRule"][];
            approvalPolicies?: {
                [key: string]: "all" | "none";
            };
        };
        Workflow: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            publishedVersionId: string | null;
            hasDraft?: boolean;
            version?: number;
        };
        WorkflowVersion: {
            draftHash?: string;
            /** Format: uuid */
            id: string;
            revision: number;
            /** @enum {string} */
            state: "draft" | "published";
            body?: components["schemas"]["WorkflowDraftBody"];
            mermaid?: string;
            /** Format: date-time */
            publishedAt: string | null;
        };
        PublishWorkflowRequest: {
            expectedVersion: number;
            /** @description SHA256 十六进制；服务端重新计算校验。 */
            draftHash: string;
        };
        RepositoryLink: {
            /** Format: uuid */
            id: string;
            displayName: string;
            url: string;
            provider: string;
            defaultBranch: string;
            /** Format: date-time */
            archivedAt: string | null;
            version?: number;
        };
        RepositoryDraftRequest: {
            displayName: string;
            url: string;
            provider?: string;
            /** @default main */
            defaultBranch: string;
        };
        RepositoryUpdateRequest: {
            expectedVersion: number;
            displayName?: string;
            url?: string;
            provider?: string;
            defaultBranch?: string;
        };
        Plan: {
            /** Format: uuid */
            id: string;
            title: string;
            goal?: string;
            acceptanceCriteria?: string;
            /** @enum {string} */
            status: "draft" | "active" | "accepted" | "cancelled";
            /** Format: uuid */
            ownerIdentityId: string | null;
            /** Format: uuid */
            workflowId: string | null;
            /** Format: uuid */
            latestAcceptanceId?: string | null;
            taskStats?: {
                total: number;
                accepted: number;
                active: number;
                cancelled: number;
            };
            version: number;
            /** Format: date-time */
            createdAt?: string;
        };
        PlanDraftRequest: {
            title: string;
            goal?: string;
            acceptanceCriteria?: string;
            /** Format: uuid */
            ownerIdentityId?: string;
            /** Format: uuid */
            workflowId?: string;
        };
        Task: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            planId?: string | null;
            /** Format: uuid */
            parentTaskId?: string | null;
            title: string;
            expectedOutput?: string;
            acceptanceCriteria?: string;
            /** @enum {string} */
            kind: "task" | "bug";
            /** @enum {string} */
            status: "draft" | "ready" | "working" | "delivered" | "accepted" | "rework" | "cancelled";
            participants?: {
                /** Format: uuid */
                identityId: string;
                displayName?: string;
                responsibility: string;
            }[];
            /** Format: uuid */
            reviewerIdentityId: string | null;
            /** Format: uuid */
            workflowId?: string | null;
            nodeId?: string | null;
            requirements?: components["schemas"]["TaskRequirement"][];
            /** Format: uuid */
            latestReportId?: string | null;
            /** Format: uuid */
            latestAcceptanceId?: string | null;
            /** @description 当前阻塞当前置（由服务端计算）。 */
            blockers?: {
                /** @enum {string} */
                phase: "start" | "accept";
                objectType: string;
                objectId: string;
                reason: string;
            }[];
            version: number;
        };
        TaskRequirement: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            phase: "start" | "accept" | "both";
            /** @enum {string} */
            kind: "task_acceptance" | "handoff_receipt" | "material_ready";
            /** Format: uuid */
            targetId: string;
            /** Format: uuid */
            materialVersionId?: string | null;
            hard: boolean;
            label?: string;
            satisfied?: boolean;
        };
        TaskDraftRequest: {
            title: string;
            /** Format: uuid */
            planId?: string;
            /** Format: uuid */
            parentTaskId?: string;
            expectedOutput?: string;
            acceptanceCriteria?: string;
            /** @enum {string} */
            kind?: "task" | "bug";
            bugDetails?: components["schemas"]["BugDetails"];
            participantIdentityIds?: string[];
            /** Format: uuid */
            reviewerIdentityId?: string;
            /** Format: uuid */
            workflowId?: string;
            nodeId?: string;
            requirements?: {
                /** @enum {string} */
                phase: "start" | "accept" | "both";
                /** @enum {string} */
                kind: "task_acceptance" | "handoff_receipt" | "material_ready";
                /** Format: uuid */
                targetId: string;
                /** Format: uuid */
                materialVersionId?: string;
                hard: boolean;
                label?: string;
            }[];
        };
        StartTaskRequest: {
            expectedVersion: number;
            /** Format: uuid */
            identityId?: string;
        };
        ExecutionMap: {
            /** Format: uuid */
            planId?: string | null;
            nodes: {
                /** Format: uuid */
                taskId: string;
                title: string;
                status: string;
                /** @description 按真实前置关系计算的执行列（0 起）。 */
                column: number;
                blockers?: {
                    [key: string]: unknown;
                }[];
            }[];
            edges: {
                /** Format: uuid */
                fromTaskId: string;
                /** Format: uuid */
                toTaskId: string;
                /** @enum {string} */
                phase: "start" | "accept" | "both";
                /** @enum {string} */
                kind: "hard" | "advisory" | "parent";
            }[];
        };
        WorkReport: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            taskId: string;
            /** Format: uuid */
            identityId: string;
            bindingVersion: number;
            /** Format: uuid */
            submissionId?: string | null;
            /** @enum {string} */
            reportKind: "progress" | "delivery";
            progressHint?: string | null;
            codeRefs?: components["schemas"]["CodeRef"][];
            environmentRefs?: {
                [key: string]: unknown;
            }[];
            /** Format: date-time */
            createdAt: string;
        };
        TaskReportRequest: {
            /** @enum {string} */
            kind: "progress" | "delivery";
            /**
             * Format: uuid
             * @description 引用已 finalize 的 ready 提交；同提交只生成一份报告。
             */
            submissionId?: string;
            text?: string;
            /** Format: uuid */
            identityId?: string;
            materialVersionIds?: string[];
            codeRefs?: components["schemas"]["CodeRef"][];
            expectedTaskVersion?: number;
        };
        AcceptanceReview: {
            /** Format: uuid */
            reviewId: string;
            reviewHash: string;
            /** @enum {string} */
            targetType: "task" | "plan";
            /** Format: uuid */
            targetId: string;
            targetVersion?: number;
            materials?: {
                /** Format: uuid */
                materialId: string;
                /** Format: uuid */
                versionId: string;
                revision: number;
            }[];
            reports?: {
                [key: string]: unknown;
            }[];
            /** @description 计划验收时引用的任务验收 ID 集合。 */
            taskAcceptanceIds?: string[];
            blockers?: {
                [key: string]: unknown;
            }[];
        };
        AcceptanceRequest: {
            /** Format: uuid */
            reviewId: string;
            reviewHash: string;
            expectedVersion: number;
            /** @enum {string} */
            decision: "accept" | "reject";
            reason?: string;
        };
        ReopenRequest: {
            expectedVersion: number;
            /** Format: uuid */
            acceptanceId?: string;
            reason: string;
        };
        DiscardDraftRequest: {
            expectedVersion: number;
        };
        Proposal: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "work_arrangement" | "work_change" | "dependency_change" | "material_link" | "topic_creation" | "formal_conclusion" | "handoff_change" | "release_acceptance";
            /** @enum {string} */
            status: "draft" | "pending" | "approved" | "cancelled" | "stale";
            /** Format: uuid */
            currentReviewId?: string | null;
            /** Format: uuid */
            topicId?: string | null;
            /** Format: uuid */
            senderUserId?: string | null;
            revision?: number;
            version: number;
            /** Format: date-time */
            createdAt: string;
        };
        ProposalChange: {
            /** @enum {string} */
            operation: "activate_object" | "reference_task" | "create_plan" | "create_task" | "update_scope" | "set_assignment" | "set_requirements" | "link_material" | "link_topic" | "cancel_plan" | "cancel_task" | "update_position";
            targetType: string;
            /** Format: uuid */
            targetId?: string | null;
            /** @description 新对象临时引用；服务端分配真实 ID 后在结果中映射。 */
            clientRef?: string | null;
            /** @description 已有对象的版本校验；新对象省略。 */
            expectedVersion?: number;
            fields?: {
                [key: string]: unknown;
            };
            dependsOn?: string[];
        };
        ProposalDraftRequest: {
            /** @enum {string} */
            kind: "work_arrangement" | "work_change" | "dependency_change" | "material_link" | "topic_creation" | "formal_conclusion" | "handoff_change" | "release_acceptance";
            /** Format: uuid */
            topicId?: string;
            reason?: string;
            changes: components["schemas"]["ProposalChange"][];
        };
        ProposalReview: {
            version?: number;
            workflowConstraints?: {
                [key: string]: unknown;
            }[];
            /** Format: uuid */
            reviewId: string;
            reviewHash: string;
            /** Format: uuid */
            proposalId: string;
            /** @enum {string} */
            status: "draft" | "pending" | "approved" | "cancelled" | "stale";
            /** Format: date-time */
            submittedAt?: string | null;
            /** Format: date-time */
            firstApprovalAt?: string | null;
            /** Format: date-time */
            deadlineAt?: string | null;
            changes: components["schemas"]["ProposalChange"][];
            slots: components["schemas"]["ApprovalSlot"][];
            createdIds?: {
                [key: string]: string;
            };
            canAct?: boolean;
            unmetRequirements?: {
                [key: string]: unknown;
            }[];
        };
        ApprovalSlot: {
            /** Format: uuid */
            currentUserId?: string | null;
            bindingVersion?: number;
            canDecide?: boolean;
            canDelegate?: boolean;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            authorityType: "identity" | "user";
            /** Format: uuid */
            authorityId: string;
            displayName?: string;
            positionName?: string | null;
            /** Format: uuid */
            initialUserId?: string | null;
            /** @enum {string} */
            state: "pending" | "approved" | "rejected" | "timeout" | "delegated";
        };
        ProposalSubmitRequest: {
            expectedVersion: number;
            draftHash: string;
        };
        ProposalDecisionRequest: {
            /** Format: uuid */
            reviewId: string;
            reviewHash: string;
            expectedVersion: number;
            /** @enum {string} */
            decision: "approve" | "reject";
            slotIds: string[];
            actingBindingVersions?: {
                /** Format: uuid */
                identityId: string;
                bindingVersion: number;
            }[];
            reason?: string;
        };
        DelegateDecisionRequest: {
            /** Format: uuid */
            reviewId: string;
            reviewHash: string;
            slotIds: string[];
            reason: string;
        };
        ProposalRevisionRequest: {
            /** Format: uuid */
            previousReviewId: string;
            reason: string;
            changes: components["schemas"]["ProposalChange"][];
        };
        Handoff: {
            /** Format: uuid */
            id: string;
            title?: string;
            /** Format: uuid */
            targetTaskId: string;
            /** Format: uuid */
            receiverIdentityId: string;
            receiverDisplayName?: string;
            /** Format: uuid */
            workflowId?: string | null;
            /** @enum {string} */
            kind: "dependency" | "stage";
            /** @enum {string} */
            state: "waiting" | "accepted" | "needs_revision";
            version?: number;
            sources: components["schemas"]["HandoffSource"][];
        };
        HandoffSource: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sourceTaskId: string;
            /** Format: uuid */
            senderIdentityId: string;
            senderDisplayName?: string;
            /** Format: uuid */
            currentVersionId: string | null;
            currentVersion?: number | null;
            /** @enum {string} */
            state: "draft" | "pending" | "accepted" | "rejected";
            reason?: string | null;
            /** Format: date-time */
            sentAt?: string | null;
            /** Format: date-time */
            decidedAt?: string | null;
        };
        HandoffDraftRequest: {
            title?: string;
            /** Format: uuid */
            targetTaskId: string;
            /** Format: uuid */
            receiverIdentityId: string;
            /** Format: uuid */
            workflowId?: string;
            /** @enum {string} */
            kind: "dependency" | "stage";
            sources: {
                /** Format: uuid */
                sourceTaskId: string;
                /** Format: uuid */
                senderIdentityId: string;
            }[];
        };
        HandoffSourceRevisionRequest: {
            summary: string;
            /** Format: uuid */
            submissionId?: string;
            materialVersionIds?: string[];
            /** Format: uuid */
            reportId?: string;
        };
        HandoffSendRequest: {
            sourceVersion: number;
            reviewHash: string;
        };
        HandoffDecisionRequest: {
            sourceVersion: number;
            reviewHash: string;
            /** @enum {string} */
            decision: "accept" | "reject";
            reason?: string;
            expectedVersion?: number;
        };
        BugDetails: {
            /** Format: uuid */
            sourceTaskId?: string;
            observedReleaseRef?: string;
            environment: string;
            steps: string;
            expected: string;
            actual: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
        };
        ReleaseReport: {
            /** Format: uuid */
            id: string;
            versionLabel: string;
            environment: string;
            url?: string | null;
            /** @enum {string} */
            status: "success" | "partial" | "failed";
            repositoryCommits?: {
                /** Format: uuid */
                repositoryId: string;
                branch?: string;
                commit: string;
            }[];
            /** Format: uuid */
            submissionId?: string | null;
            /** Format: uuid */
            reportedBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        ReleaseReportRequest: {
            versionLabel: string;
            environment: string;
            url?: string;
            /** @enum {string} */
            status: "success" | "partial" | "failed";
            repositoryCommits?: {
                /** Format: uuid */
                repositoryId: string;
                branch?: string;
                commit: string;
            }[];
            /** Format: uuid */
            submissionId?: string;
        };
        FixPropagationRequest: {
            targetReleaseRefs: string[];
        };
        AuditEntry: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            actorType: "user" | "operator" | "agent" | "system";
            /** Format: uuid */
            actorUserId?: string | null;
            /** Format: uuid */
            identityId?: string | null;
            /** @enum {string} */
            source: "web" | "cli" | "delegate" | "timeout" | "worker" | "operator" | "agent";
            operation: string;
            objectType: string;
            objectId?: string;
            /** Format: uuid */
            reviewId?: string | null;
            reason?: string | null;
            /** Format: date-time */
            occurredAt: string;
        };
    };

    responses: {
        /** @description 请求不合法（400/422，VALIDATION_ERROR 等）。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未认证（401，UNAUTHENTICATED/SESSION_EXPIRED/GRANT_REVOKED）。 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 已认证但无权限（403，FORBIDDEN/HUMAN_CONFIRMATION_REQUIRED）。 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在或对非成员隐藏存在性（404）。 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 状态/版本/幂等冲突（409，详见 error.code）。 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 前置条件未满足（412，details.blockers 列明阻塞对象）。 */
        RequirementUnmet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求体过大或类型不支持（413/415）。 */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 速率或预算限制（429，带 Retry-After）。 */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 依赖暂不可用（503，retryable 明示）。 */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 内部错误（500）。 */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };

    parameters: {
        /** @description 分页大小，范围 1-100，默认 50。 */
        LimitParam: number;
        /** @description 不透明分页游标，编码范围与过滤条件。 */
        CursorParam: string;
        /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
        IdempotencyKeyParam: string;
        ProjectIdParam: string;
    };

    requestBodies: never;

    headers: never;

    pathItems: never;
}
