/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations, SchemaComponentsSchemas } from "./schema";
export interface SchemaComponents0 {

    schemas: SchemaComponentsSchemas;

    responses: {
        /** @description 请求不合法（400/422，VALIDATION_ERROR 等）。 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未认证（401，UNAUTHENTICATED/SESSION_EXPIRED/GRANT_REVOKED）。 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 已认证但无权限（403，FORBIDDEN/HUMAN_CONFIRMATION_REQUIRED）。 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在或对非成员隐藏存在性（404）。 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 状态/版本/幂等冲突（409，详见 error.code）。 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 前置条件未满足（412，details.blockers 列明阻塞对象）。 */
        RequirementUnmet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求体过大或类型不支持（413/415）。 */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 速率或预算限制（429，带 Retry-After）。 */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 依赖暂不可用（503，retryable 明示）。 */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 内部错误（500）。 */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 稳定的任务主讨论，已有会话复用。 */
        TaskMainTopicResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data: components["schemas"]["TaskMainTopicResult"];
                    meta: components["schemas"]["CommandMeta"];
                };
            };
        };
    };

    parameters: {
        /** @description 分页大小，范围 1-100，默认 50。 */
        LimitParam: number;
        /** @description 不透明分页游标，编码范围与过滤条件。 */
        CursorParam: string;
        /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
        IdempotencyKeyParam: string;
        ProjectIdParam: string;
    };

    requestBodies: never;

    headers: never;

    pathItems: never;
}
