/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations } from "./schema";
export interface SchemaOperations2 {

    delegateProposalDecision: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelegateDecisionRequest"];
            };
        };
        responses: {
            /** @description 代批后的审阅状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProposalReview"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    createProposalRevision: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalRevisionRequest"];
            };
        };
        responses: {
            /** @description 新草稿。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Proposal"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    getSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务信息。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SystemInfo"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };

    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 能力集。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Capabilities"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
        };
    };

    listTopics: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                kind?: "project_room" | "discussion" | "handoff";
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 议题分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Topic"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createTopic: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTopicRequest"];
            };
        };
        responses: {
            /** @description 已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Topic"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    getTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 议题详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Topic"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    listMessages: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                beforeSeq?: number;
                afterSeq?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 消息分页（按 seq 升序）。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Message"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    linkTopic: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicLinkRequest"];
            };
        };
        responses: {
            /** @description 已关联。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Topic"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    createSubmission: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequest"];
            };
        };
        responses: {
            /** @description 已 finalize 的提交（含 message/report 引用）。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Submission"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 版本冲突或材料未 ready（details 列明）。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            412: components["responses"]["RequirementUnmet"];
        };
    };

    listUploadSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["UploadSession"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description 上传方案。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UploadSession"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["TooLarge"];
        };
    };

    uploadPart: {
        parameters: {
            query?: never;
            header: {
                "X-Judex-Part-SHA256": string;
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                uploadId: string;
                partNumber: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description 分片已登记。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            partNumber: number;
                            receivedBytes: number;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
        };
    };

    completeUpload: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                uploadId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteUploadRequest"];
            };
        };
        responses: {
            /** @description 已登记的材料版本。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MaterialVersion"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 来源版本落后（SOURCE_VERSION_CONFLICT）或幂等冲突。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 分片不完整或校验失败。 */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };

    cancelUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                uploadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已取消。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            cancelled: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    listMaterials: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                kind?: "file" | "html_bundle" | "text";
                linkedObjectType?: string;
                linkedObjectId?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 材料分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Material"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listMaterialVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                materialId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["MaterialVersion"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    downloadMaterialContent: {
        parameters: {
            query?: {
                /** @description HTML 包内的相对路径条目。 */
                entry?: string;
            };
            header?: {
                Range?: string;
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                materialId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 内容流。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description 范围内容。 */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    createPreviewSession: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                materialId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 预览会话。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PreviewSession"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 流程分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Workflow"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createWorkflow: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDraftBody"];
            };
        };
        responses: {
            /** @description 已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Workflow"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listWorkflowVersions: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["WorkflowVersion"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    updateWorkflowDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                    body: components["schemas"]["WorkflowDraftBody"];
                };
            };
        };
        responses: {
            /** @description 草稿版本。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WorkflowVersion"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    publishWorkflow: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishWorkflowRequest"];
            };
        };
        responses: {
            /** @description 已发布的版本。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WorkflowVersion"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
