/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations, SchemaComponentsSchemas } from "./schema";
export interface SchemaPaths1 {

    "/projects/{projectId}/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 首屏概览、本人身份与事件游标 */
        get: operations["getProjectBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 归档项目（owner；只读保留历史） */
        post: operations["archiveProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复归档项目（owner） */
        post: operations["restoreProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/owner-transfer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发起负责人转移（owner 发起，双方确认） */
        post: operations["requestOwnerTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/owner-transfers/{transferId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                transferId: string;
            };
            cookie?: never;
        };
        /** 转移请求详情（转出或转入本人） */
        get: operations["getOwnerTransfer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/owner-transfers/{transferId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                transferId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 转入方接受/拒绝负责人转移 */
        post: operations["decideOwnerTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 本人退出项目（先处理活动职责） */
        post: operations["leaveProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 仓库元数据列表 */
        get: operations["listRepositories"];
        put?: never;
        /** 登记仓库元数据（manager；不操纵 Git） */
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/repositories/{repositoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                repositoryId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新仓库元数据（manager） */
        patch: operations["updateRepository"];
        trace?: never;
    };

    "/projects/{projectId}/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 提案分页 */
        get: operations["listProposals"];
        put?: never;
        /** 创建 typed 提案草稿（返回差异与服务端建议审批名单） */
        post: operations["createProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/proposals/{proposalId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 更新提案草稿（只影响 draft） */
        put: operations["updateProposalDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/proposals/{proposalId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交提案（冻结 payload/名单/manifest；sender 人工确认） */
        post: operations["submitProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/proposals/{proposalId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        /** 固定审阅版本（payload/manifest/slots/votes/可执行动作） */
        get: operations["getProposalReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/proposals/{proposalId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 审批决定（当前职责办理人；同一真人可覆盖多个 slot） */
        post: operations["decideProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/proposals/{proposalId}/delegate-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 授权代批（只覆盖 pending 位，记录实际 actor） */
        post: operations["delegateProposalDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/proposals/{proposalId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 基于旧审阅创建修订草稿（旧票不继承） */
        post: operations["createProposalRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务版本与公开 capability 状态 */
        get: operations["getSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 注册规则、上传限制、确认机制与协议版本（匿名最小集） */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 议题分页 */
        get: operations["listTopics"];
        put?: never;
        /** 新建议题（显式用户新建；AI 走建议提案） */
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        /** 议题详情与本人可操作项 */
        get: operations["getTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/topics/{topicId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        /** 消息按 seq 分页（beforeSeq/afterSeq） */
        get: operations["listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/topics/{topicId}/links": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 按预期关联版本替换对象引用，保留主讨论必需归属 */
        put: operations["replaceTopicLinks"];
        /** 议题关联计划/任务（用户明确链接；AI 用提案） */
        post: operations["linkTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 统一提交入口（文字+材料；目的 message/progress/delivery/material） */
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 本人未完成上传会话 */
        get: operations["listUploadSessions"];
        put?: never;
        /** 创建上传会话（返回分片方案） */
        post: operations["createUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/uploads/{uploadId}/parts/{partNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 上传单个分片（二进制流；同号不同摘要冲突） */
        put: operations["uploadPart"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/uploads/{uploadId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 完成上传并登记不可变材料版本（幂等返回同版本） */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/uploads/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 取消未完成上传会话（不删正式材料） */
        delete: operations["cancelUpload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 项目共享资料分页（按 kind/关联过滤） */
        get: operations["listMaterials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/materials/{materialId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                materialId: string;
            };
            cookie?: never;
        };
        /** 不可变版本列表 */
        get: operations["listMaterialVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/materials/{materialId}/versions/{versionId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 版本内容下载（鉴权代理，支持 Range） */
        get: operations["downloadMaterialContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/materials/{materialId}/versions/{versionId}/preview-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为 HTML 包版本创建隔离 origin 短时预览 */
        post: operations["createPreviewSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/workflow-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取全局流程模板和共用场景目录 */
        get: operations["getWorkflowPresetCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/workflows/import-presets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 将选定流程模板复制为项目独立草稿（owner/manager）
         * @description 同一事务导入，按稳定来源或中英文同名流程跳过重复项。不发布、不分配人员或职位、不添加审批授权。
         */
        post: operations["importWorkflowPresets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 流程定义列表 */
        get: operations["listWorkflows"];
        put?: never;
        /** 新建流程草稿（manager；AI 也可另建草稿） */
        post: operations["createWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/workflows/{workflowId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        /** 已发布版本与公开差异 */
        get: operations["listWorkflowVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/workflows/{workflowId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 更新流程草稿（只影响 draft；manager） */
        put: operations["updateWorkflowDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/workflows/{workflowId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发布流程版本（manager 人工确认；版本不可变） */
        post: operations["publishWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/plans/{planId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** updatePlanDraft */
        put: operations["updatePlanDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/plans/{planId}/discard-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        /** getPlanDiscardReview */
        get: operations["getPlanDiscardReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** updateTaskDraft */
        put: operations["updateTaskDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/discard-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        /** getTaskDiscardReview */
        get: operations["getTaskDiscardReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/execution-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        /** getTaskExecutionReview */
        get: operations["getTaskExecutionReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** skipTask */
        post: operations["skipTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** restoreTask */
        post: operations["restoreTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
