/** Generated by api/generate-types.mjs. Do not edit. */
import type { SchemaPaths0 } from "./schema-paths-0";
import type { SchemaPaths1 } from "./schema-paths-1";
import type { SchemaComponents0 } from "./schema-components-0";
import type { SchemaOperations0 } from "./schema-operations-0";
import type { SchemaOperations1 } from "./schema-operations-1";
import type { SchemaOperations2 } from "./schema-operations-2";
export interface paths extends SchemaPaths0, SchemaPaths1 {}
export type webhooks = Record<string, never>;
export interface components extends SchemaComponents0 {}
export type $defs = Record<string, never>;
export interface operations extends SchemaOperations0, SchemaOperations1, SchemaOperations2 {}
