/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations, SchemaComponentsSchemas } from "./schema";
export interface SchemaOperations2 {

    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    updateProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description 更新后的项目。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    getProjectBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 引导数据。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectBootstrap"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    archiveProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description 已归档。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    restoreProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description 已恢复。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    requestOwnerTransfer: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerTransferRequest"];
            };
        };
        responses: {
            /** @description 已创建转移请求。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OwnerTransfer"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    getOwnerTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                transferId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 转移详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OwnerTransfer"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    decideOwnerTransfer: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                transferId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerTransferDecisionRequest"];
            };
        };
        responses: {
            /** @description 决定结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OwnerTransfer"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    leaveProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                };
            };
        };
        responses: {
            /** @description 已退出。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            left: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 存在活动职责需先处理（details 列明）。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };

    listRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 仓库分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["RepositoryLink"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createRepository: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryDraftRequest"];
            };
        };
        responses: {
            /** @description 已登记。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RepositoryLink"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    updateRepository: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                repositoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RepositoryLink"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    listProposals: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                status?: "draft" | "pending" | "approved" | "cancelled" | "stale";
                kind?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 提案分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Proposal"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createProposal: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalDraftRequest"];
            };
        };
        responses: {
            /** @description 草稿已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Proposal"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    updateProposalDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                    reason?: string;
                    changes: components["schemas"]["ProposalChange"][];
                };
            };
        };
        responses: {
            /** @description 更新后的草稿。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Proposal"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    submitProposal: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalSubmitRequest"];
            };
        };
        responses: {
            /** @description 冻结后的审阅。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProposalReview"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    getProposalReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审阅详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProposalReview"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    decideProposal: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalDecisionRequest"];
            };
        };
        responses: {
            /** @description 决定后的审阅状态（全部通过时同事务应用变更）。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProposalReview"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    delegateProposalDecision: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelegateDecisionRequest"];
            };
        };
        responses: {
            /** @description 代批后的审阅状态。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProposalReview"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    createProposalRevision: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalRevisionRequest"];
            };
        };
        responses: {
            /** @description 新草稿。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Proposal"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    getSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务信息。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["SystemInfo"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };

    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 能力集。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Capabilities"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
        };
    };

    listTopics: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                kind?: "project_room" | "discussion" | "handoff";
                planId?: string;
                taskId?: string;
                q?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 议题分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Topic"][];
                            nextCursor: string | null;
                            totalCount?: number;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createTopic: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTopicRequest"];
            };
        };
        responses: {
            /** @description 已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Topic"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    getTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 议题详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Topic"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    listMessages: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                beforeSeq?: number;
                afterSeq?: number;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 消息分页（按 seq 升序）。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Message"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    replaceTopicLinks: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceTopicLinksRequest"];
            };
        };
        responses: {
            /** @description 当前会话及新的关联版本。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Topic"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    linkTopic: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicLinkRequest"];
            };
        };
        responses: {
            /** @description 已关联。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Topic"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    createSubmission: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequest"];
            };
        };
        responses: {
            /** @description 已 finalize 的提交（含 message/report 引用）。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Submission"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 版本冲突或材料未 ready（details 列明）。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            412: components["responses"]["RequirementUnmet"];
        };
    };

    listUploadSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会话分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["UploadSession"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createUploadSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUploadRequest"];
            };
        };
        responses: {
            /** @description 上传方案。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UploadSession"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["TooLarge"];
        };
    };

    uploadPart: {
        parameters: {
            query?: never;
            header: {
                "X-Judex-Part-SHA256": string;
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                uploadId: string;
                partNumber: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description 分片已登记。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            partNumber: number;
                            receivedBytes: number;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
        };
    };

    completeUpload: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                uploadId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteUploadRequest"];
            };
        };
        responses: {
            /** @description 已登记的材料版本。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["MaterialVersion"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 来源版本落后（SOURCE_VERSION_CONFLICT）或幂等冲突。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 分片不完整或校验失败。 */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };

    cancelUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                uploadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已取消。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            cancelled: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    listMaterials: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                kind?: "file" | "html_bundle" | "text";
                linkedObjectType?: string;
                linkedObjectId?: string;
                q?: string;
                formatGroup?: string;
                sort?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 材料分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["MaterialLibraryItem"][];
                            /** @description 当前搜索、格式与工作范围下的资料总数。 */
                            totalCount?: number;
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listMaterialVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                materialId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["MaterialVersion"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    downloadMaterialContent: {
        parameters: {
            query?: {
                /** @description HTML 包内的相对路径条目。 */
                entry?: string;
            };
            header?: {
                Range?: string;
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                materialId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 内容流。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description 范围内容。 */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    createPreviewSession: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                materialId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 预览会话。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PreviewSession"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    getWorkflowPresetCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 只读流程模板，节点和连线生成缩略图；建议职位不构成授权。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WorkflowPresetCatalog"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    importWorkflowPresets: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportWorkflowPresetsRequest"];
            };
        };
        responses: {
            /** @description 新增流程草稿及已存在的跳过项。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ImportedWorkflowPresets"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 流程分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Workflow"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createWorkflow: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDraftBody"];
            };
        };
        responses: {
            /** @description 已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Workflow"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listWorkflowVersions: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["WorkflowVersion"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    updateWorkflowDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                    body: components["schemas"]["WorkflowDraftBody"];
                };
            };
        };
        responses: {
            /** @description 草稿版本。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WorkflowVersion"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    publishWorkflow: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishWorkflowRequest"];
            };
        };
        responses: {
            /** @description 已发布的版本。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WorkflowVersion"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    updatePlanDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkDraftUpdate"];
            };
        };
        responses: {
            /** @description 成功。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Plan"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    getPlanDiscardReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DraftDiscardReview"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    updateTaskDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkDraftUpdate"];
            };
        };
        responses: {
            /** @description 成功。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Task"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    getTaskDiscardReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DraftDiscardReview"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    getTaskExecutionReview: {
        parameters: {
            query?: {
                operation?: "skip" | "restore";
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ExecutionReview"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
