/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations, SchemaComponentsSchemas } from "./schema";
export interface SchemaPaths0 {

    "/projects/{projectId}/topics/{topicId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 请求针对某提交的 AI 分析（重复源不续额度） */
        post: operations["startAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                runId: string;
            };
            cookie?: never;
        };
        /** 公开运行状态、预算与产物引用 */
        get: operations["getAgentRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                runId: string;
            };
            cookie?: never;
        };
        /** 运行增量 SSE（按 run seq 恢复；私有链路脱敏） */
        get: operations["subscribeRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                runId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消运行（不撤销已成立业务决定） */
        post: operations["cancelAgentRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/batches/{batchId}/extensions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                batchId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 显式续开讨论轮次（manager；部署上限内） */
        post: operations["extendDiscussionBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/confirmation-intents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CLI 创建人工确认意图（返回 confirmUrl，不是批准） */
        post: operations["createConfirmationIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/confirmation-intents/{intentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                intentId: string;
            };
            cookie?: never;
        };
        /** 查询意图状态（本人/grant；CLI 轮询用） */
        get: operations["getConfirmationIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/confirmation-intents/{intentId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                intentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 浏览器一次确认（仅 Web 会话；原子执行原领域命令） */
        post: operations["confirmIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 自由注册（邮箱+密码，无邮件验证） */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录（错误统一 INVALID_CREDENTIALS） */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前会话信息（含 CSRF token） */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销当前会话并清 Cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销其他会话与授权 */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 使用一次性恢复码设置新密码（不自动登录） */
        post: operations["recoverPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/device/authorizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CLI 发起设备授权（返回 deviceCode/userCode） */
        post: operations["createDeviceAuthorization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/device/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CLI 轮询设备授权结果（pending/slow_down/denied/expired/token） */
        post: operations["pollDeviceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/device/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 浏览器确认/拒绝设备授权（本人+CSRF） */
        post: operations["confirmDeviceAuthorization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 轮换 token 对（旧 refresh 重放撤销整族） */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/auth/device/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review a pending device authorization */
        get: operations["getDeviceAuthorization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/topics/{topicId}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 从固定消息位置分叉公开会话 */
        post: operations["forkTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        /** 任务统一活动时间线 */
        get: operations["listTaskActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/plans/{planId}/discussion-summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        /** 计划主讨论的任务摘要及待处理讨论建议 */
        get: operations["getPlanDiscussionSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/discussion-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 待处理讨论建议 */
        get: operations["listDiscussionSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/discussion-suggestions/{suggestionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                suggestionId: string;
            };
            cookie?: never;
        };
        /** 取得讨论建议与冻结来源 */
        get: operations["getDiscussionSuggestion"];
        put?: never;
        /** 人选择讨论建议的承载位置 */
        post: operations["resolveDiscussionSuggestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/task-analyses/{analysisId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                analysisId: string;
            };
            cookie?: never;
        };
        /** 读取真实任务分析状态 */
        get: operations["getTaskAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/task-analyses/{analysisId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                analysisId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 保留来源与预算的任务分析重试 */
        post: operations["retryTaskAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/main-topic": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 首次明确点击建立任务主讨论，并发及后续点击复用 */
        post: operations["ensureTaskMainTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 正式任务交付及交接的分页只读投影 */
        get: operations["listDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/confirmation-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户级建项目确认意图（仅 project.create） */
        post: operations["createGlobalConfirmationIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/confirmation-intents/{intentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intentId: string;
            };
            cookie?: never;
        };
        /** 用户级建项目确认意图（仅 project.create） */
        get: operations["getGlobalConfirmationIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/confirmation-intents/{intentId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户级建项目确认意图（仅 project.create） */
        post: operations["confirmGlobalIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/handoffs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 交接分页 */
        get: operations["listHandoffs"];
        put?: never;
        /** 创建交接草稿（多来源；可跨任务） */
        post: operations["createHandoff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/handoffs/{handoffId}/sources/{sourceId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                handoffId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 补交新来源版本（保留旧决定；发送人重新确认） */
        post: operations["createHandoffSourceRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/handoffs/{handoffId}/sources/{sourceId}/send": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                handoffId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发送来源（该来源 sender 人工确认） */
        post: operations["sendHandoffSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/handoffs/{handoffId}/sources/{sourceId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                handoffId: string;
                sourceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 接收/拒收来源（receiver 人工确认；拒收须理由） */
        post: operations["decideHandoffSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/handoffs/{handoffId}/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                handoffId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提醒未回应来源（有冷却限制） */
        post: operations["sendHandoffReminder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/release-reports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 版本发布上报分页 */
        get: operations["listReleaseReports"];
        put?: never;
        /** 上报真实环境版本事实（不是部署命令） */
        post: operations["createReleaseReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 可见业务审计分页（无私人提示词） */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目事件 SSE 流（after/Last-Event-ID；15s 心跳） */
        get: operations["subscribeProjectEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/material-versions/{versionId}/usages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                versionId: string;
            };
            cookie?: never;
        };
        /** listMaterialUsages */
        get: operations["listMaterialUsages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/material-versions/{versionId}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                versionId: string;
            };
            cookie?: never;
        };
        /** getFilePreview */
        get: operations["getFilePreview"];
        put?: never;
        /** prepareFilePreview */
        post: operations["prepareFilePreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/material-versions/{versionId}/preview/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                versionId: string;
            };
            cookie?: never;
        };
        /** 鉴权预览内容 */
        get: operations["downloadFilePreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/materials/{materialId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                materialId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** deleteMaterial */
        delete: operations["deleteMaterial"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/material-versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按固定版本读取材料清单 */
        get: operations["getMaterialVersionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/material-versions/{versionId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 版本内容下载（鉴权代理，支持 Range） */
        get: operations["downloadMaterialVersionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me/recent-topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 本人有权访问的最近讨论 */
        get: operations["listRecentTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新本人资料（不改邮箱） */
        patch: operations["updateMe"];
        trace?: never;
    };

    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 修改密码（轮换当前会话，撤销其他会话/授权） */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 本人活跃会话列表（无 secret） */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤销指定会话 */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me/client-grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 本人 CLI 设备授权列表 */
        get: operations["listClientGrants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me/client-grants/{grantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 撤销 CLI 设备授权 */
        delete: operations["revokeClientGrant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 与本人邮箱匹配的待接受邀请 */
        get: operations["listMyInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 本人待办（按当前绑定计算） */
        get: operations["listMyActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 本人站内提醒 */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/me/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 标记提醒已读（无业务状态变化） */
        post: operations["markNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 成员与公开职责分页 */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 授予/撤回 manager（owner；不移除最后 owner） */
        patch: operations["updateMemberRole"];
        trace?: never;
    };

    "/projects/{projectId}/members/{userId}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 移除成员（manager；owner 不可移除；返回受影响职责） */
        post: operations["removeMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 项目邀请分页（manager） */
        get: operations["listInvitations"];
        put?: never;
        /** 创建邀请（指定邮箱与职位集合，返回邀请链接 token） */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/invitations/{invitationId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                invitationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销邀请（manager） */
        post: operations["revokeInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/invitations/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 按 token 预览邀请（登录且邮箱匹配） */
        get: operations["resolveInvitation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/invitations/{invitationId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 接受邀请（受邀本人；重试不重复建成员） */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/invitations/{invitationId}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitationId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 拒绝邀请（受邀本人） */
        post: operations["declineInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 职位列表（含公开职责） */
        get: operations["listPositions"];
        put?: never;
        /** 创建职位草稿（manager） */
        post: operations["createPosition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/positions/{positionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                positionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改职位（产生新版本；manager） */
        patch: operations["updatePosition"];
        trace?: never;
    };

    "/projects/{projectId}/identities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 稳定身份与当前公开绑定 */
        get: operations["listIdentities"];
        put?: never;
        /** 为成员建立新任职（manager） */
        post: operations["createIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/identities/{identityId}/replace": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                identityId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 替换任职（保留 identity 与历史，生成新 binding） */
        post: operations["replaceIdentityBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 本人当前任职的独立工作提示词（仅本人可见） */
        get: operations["getMyPreferences"];
        /** 更新本人指定职位的提示词（独立 revision，须当前任职） */
        put: operations["updateMyPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公开模型目录（无凭据） */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 计划分页 */
        get: operations["listPlans"];
        put?: never;
        /** 创建计划草稿（正式生效需提案审批） */
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        /** 计划详情（任务统计、历史验收/重开） */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/plans/{planId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 丢弃草稿：作者、计划负责人或管理员，版本化影响核对 */
        post: operations["discardPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/plans/{planId}/acceptance-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        /** 计划验收快照（owner；引用任务验收集合） */
        get: operations["getPlanAcceptanceReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/plans/{planId}/acceptances": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 计划整体验收（owner 人工确认） */
        post: operations["acceptPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/plans/{planId}/reopens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重开已验收计划（owner；保留历史） */
        post: operations["reopenPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 任务分页（按计划/状态过滤） */
        get: operations["listTasks"];
        put?: never;
        /** 创建任务草稿 */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        /** 任务详情（当前报告、硬前置、可执行动作） */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 丢弃草稿：作者、计划负责人或管理员，版本化影响核对 */
        post: operations["discardTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/execution-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 有界任务图（列=执行顺序）与外部依赖摘要 */
        get: operations["getExecutionMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 开始任务（participant；满足 start 硬条件） */
        post: operations["startTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        /** 任务报告列表 */
        get: operations["listTaskReports"];
        put?: never;
        /** 上报进度/交付（与带任务目的的 submissions 同一用例） */
        post: operations["createTaskReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/acceptance-review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        /** 任务验收快照（reviewer） */
        get: operations["getTaskAcceptanceReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/acceptances": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 任务验收/退回（当前 reviewer 人工确认） */
        post: operations["decideTaskAcceptance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/reopens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重开已验收任务（reviewer；引用原验收） */
        post: operations["reopenTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/tasks/{taskId}/fix-propagations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为 Bug 选择修复传播目标（生成工作提案草稿） */
        post: operations["createFixPropagation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/position-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全局内置场景与职位模板（只读） */
        get: operations["getPositionPresetCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/positions/import-presets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量复制选定场景的职位到项目（owner/manager）
         * @description 同一事务创建独立职位，按模板来源或中英文同名职位跳过重复项；不分配成员、流程节点、模型或审批权限。
         */
        post: operations["importPositionPresets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 本人加入的项目分页 */
        get: operations["listProjects"];
        put?: never;
        /** 创建项目（原子建立 owner 成员、主会场与 coordinator） */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 项目公开配置与本人能力 */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新项目配置（manager 及以上） */
        patch: operations["updateProject"];
        trace?: never;
    };
}
