/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations } from "./schema";
export interface SchemaPaths1 {

    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 服务版本与公开 capability 状态 */
        get: operations["getSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 注册规则、上传限制、确认机制与协议版本（匿名最小集） */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 议题分页 */
        get: operations["listTopics"];
        put?: never;
        /** 新建议题（显式用户新建；AI 走建议提案） */
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        /** 议题详情与本人可操作项 */
        get: operations["getTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/topics/{topicId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        /** 消息按 seq 分页（beforeSeq/afterSeq） */
        get: operations["listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/topics/{topicId}/links": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                topicId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 议题关联计划/任务（用户明确链接；AI 用提案） */
        post: operations["linkTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 统一提交入口（文字+材料；目的 message/progress/delivery/material） */
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 本人未完成上传会话 */
        get: operations["listUploadSessions"];
        put?: never;
        /** 创建上传会话（返回分片方案） */
        post: operations["createUploadSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/uploads/{uploadId}/parts/{partNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 上传单个分片（二进制流；同号不同摘要冲突） */
        put: operations["uploadPart"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/uploads/{uploadId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 完成上传并登记不可变材料版本（幂等返回同版本） */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/uploads/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 取消未完成上传会话（不删正式材料） */
        delete: operations["cancelUpload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 项目共享资料分页（按 kind/关联过滤） */
        get: operations["listMaterials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/materials/{materialId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                materialId: string;
            };
            cookie?: never;
        };
        /** 不可变版本列表 */
        get: operations["listMaterialVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/materials/{materialId}/versions/{versionId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 版本内容下载（鉴权代理，支持 Range） */
        get: operations["downloadMaterialContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/materials/{materialId}/versions/{versionId}/preview-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为 HTML 包版本创建隔离 origin 短时预览 */
        post: operations["createPreviewSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        /** 流程定义列表 */
        get: operations["listWorkflows"];
        put?: never;
        /** 新建流程草稿（manager；AI 也可另建草稿） */
        post: operations["createWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/workflows/{workflowId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        /** 已发布版本与公开差异 */
        get: operations["listWorkflowVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/workflows/{workflowId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 更新流程草稿（只影响 draft；manager） */
        put: operations["updateWorkflowDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };

    "/projects/{projectId}/workflows/{workflowId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                workflowId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发布流程版本（manager 人工确认；版本不可变） */
        post: operations["publishWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
