/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations, SchemaComponentsSchemas } from "./schema";
export interface SchemaOperations3 {

    skipTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionCommand"];
            };
        };
        responses: {
            /** @description 成功。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Task"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    restoreTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionCommand"];
            };
        };
        responses: {
            /** @description 成功。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Task"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
