/** Generated by api/generate-types.mjs. Do not edit. */
import type { paths, components, operations } from "./schema";
export interface SchemaOperations1 {

    acceptInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationDecisionRequest"];
            };
        };
        responses: {
            /** @description 接受结果（项目 ID 与身份列表）。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: uuid */
                            projectId: string;
                            identities: components["schemas"]["Identity"][];
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    declineInvitation: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationDecisionRequest"];
            };
        };
        responses: {
            /** @description 已拒绝。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            declined: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    listPositions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 职位分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Position"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createPosition: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionDraftRequest"];
            };
        };
        responses: {
            /** @description 已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Position"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    updatePosition: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                positionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePositionRequest"];
            };
        };
        responses: {
            /** @description 更新后的职位。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Position"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    listIdentities: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 身份分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Identity"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createIdentity: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIdentityRequest"];
            };
        };
        responses: {
            /** @description 已创建身份。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Identity"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    replaceIdentityBinding: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                identityId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceIdentityRequest"];
            };
        };
        responses: {
            /** @description 替换后的身份。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Identity"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    getMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 偏好。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PersonalPreferences"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    updateMyPreferences: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePersonalPreferencesRequest"];
            };
        };
        responses: {
            /** @description 更新后的偏好。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PersonalPreferences"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 模型分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["ModelSummary"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listPlans: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                status?: "draft" | "active" | "accepted" | "cancelled";
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 计划分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Plan"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createPlan: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDraftRequest"];
            };
        };
        responses: {
            /** @description 草稿已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Plan"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 计划详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Plan"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    discardPlan: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscardDraftRequest"];
            };
        };
        responses: {
            /** @description 已丢弃。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            discarded: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    getPlanAcceptanceReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 验收快照。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AcceptanceReview"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    acceptPlan: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptanceRequest"];
            };
        };
        responses: {
            /** @description 验收结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Plan"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RequirementUnmet"];
        };
    };

    reopenPlan: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReopenRequest"];
            };
        };
        responses: {
            /** @description 重开后的计划。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Plan"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    listTasks: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                planId?: string;
                status?: "draft" | "ready" | "working" | "delivered" | "accepted" | "rework" | "cancelled";
                identityId?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Task"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskDraftRequest"];
            };
        };
        responses: {
            /** @description 草稿已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Task"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Task"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    discardTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscardDraftRequest"];
            };
        };
        responses: {
            /** @description 已丢弃。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            discarded: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    getExecutionMap: {
        parameters: {
            query?: {
                planId?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 执行图。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ExecutionMap"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    startTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTaskRequest"];
            };
        };
        responses: {
            /** @description 已开始。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Task"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RequirementUnmet"];
        };
    };

    listTaskReports: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 报告分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["WorkReport"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createTaskReport: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskReportRequest"];
            };
        };
        responses: {
            /** @description 报告（引用既有 ready 提交时返回原报告）。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WorkReport"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RequirementUnmet"];
        };
    };

    getTaskAcceptanceReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 验收快照。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AcceptanceReview"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    decideTaskAcceptance: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptanceRequest"];
            };
        };
        responses: {
            /** @description 验收结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Task"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            412: components["responses"]["RequirementUnmet"];
        };
    };

    reopenTask: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReopenRequest"];
            };
        };
        responses: {
            /** @description 重开结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Task"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    createFixPropagation: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FixPropagationRequest"];
            };
        };
        responses: {
            /** @description 已生成提案草稿引用。 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** Format: uuid */
                            proposalId: string;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    listProjects: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Project"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    updateProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description 更新后的项目。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    getProjectBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 引导数据。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectBootstrap"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    archiveProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description 已归档。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    restoreProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description 已恢复。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    requestOwnerTransfer: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerTransferRequest"];
            };
        };
        responses: {
            /** @description 已创建转移请求。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OwnerTransfer"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    getOwnerTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                transferId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 转移详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OwnerTransfer"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    decideOwnerTransfer: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                transferId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerTransferDecisionRequest"];
            };
        };
        responses: {
            /** @description 决定结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["OwnerTransfer"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    leaveProject: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                };
            };
        };
        responses: {
            /** @description 已退出。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            left: boolean;
                        };
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 存在活动职责需先处理（details 列明）。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };

    listRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 仓库分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["RepositoryLink"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createRepository: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryDraftRequest"];
            };
        };
        responses: {
            /** @description 已登记。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RepositoryLink"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    updateRepository: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                repositoryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新结果。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RepositoryLink"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    listProposals: {
        parameters: {
            query?: {
                /** @description 分页大小，范围 1-100，默认 50。 */
                limit?: components["parameters"]["LimitParam"];
                /** @description 不透明分页游标，编码范围与过滤条件。 */
                cursor?: components["parameters"]["CursorParam"];
                status?: "draft" | "pending" | "approved" | "cancelled" | "stale";
                kind?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 提案分页。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: components["schemas"]["Proposal"][];
                            nextCursor: string | null;
                        };
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    createProposal: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalDraftRequest"];
            };
        };
        responses: {
            /** @description 草稿已创建。 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Proposal"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };

    updateProposalDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                    reason?: string;
                    changes: components["schemas"]["ProposalChange"][];
                };
            };
        };
        responses: {
            /** @description 更新后的草稿。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Proposal"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };

    submitProposal: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalSubmitRequest"];
            };
        };
        responses: {
            /** @description 冻结后的审阅。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProposalReview"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };

    getProposalReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审阅详情。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProposalReview"];
                        meta: components["schemas"]["RequestMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };

    decideProposal: {
        parameters: {
            query?: never;
            header: {
                /** @description 客户端生成的 UUID；同键同载荷重试返回原结果，同键异载荷返回 409。 */
                "Idempotency-Key": components["parameters"]["IdempotencyKeyParam"];
            };
            path: {
                projectId: components["parameters"]["ProjectIdParam"];
                proposalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalDecisionRequest"];
            };
        };
        responses: {
            /** @description 决定后的审阅状态（全部通过时同事务应用变更）。 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProposalReview"];
                        meta: components["schemas"]["CommandMeta"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
