/** Generated by api/generate-types.mjs. Do not edit. */
import type { SchemaPaths0 } from "./schema-paths-0";
import type { SchemaPaths1 } from "./schema-paths-1";
import type { SchemaSchemaComponentsSchemas0 } from "./schema-SchemaComponentsSchemas-0";
import type { SchemaSchemaComponentsSchemas1 } from "./schema-SchemaComponentsSchemas-1";
import type { SchemaComponents0 } from "./schema-components-0";
import type { SchemaOperations0 } from "./schema-operations-0";
import type { SchemaOperations1 } from "./schema-operations-1";
import type { SchemaOperations2 } from "./schema-operations-2";
import type { SchemaOperations3 } from "./schema-operations-3";
export interface paths extends SchemaPaths0, SchemaPaths1 {}
export type webhooks = Record<string, never>;
export interface SchemaComponentsSchemas extends SchemaSchemaComponentsSchemas0, SchemaSchemaComponentsSchemas1 {}
export interface components extends SchemaComponents0 {}
export type $defs = Record<string, never>;
export interface operations extends SchemaOperations0, SchemaOperations1, SchemaOperations2, SchemaOperations3 {}
