import {Card} from '@heroui/react';
import {useId,useLayoutEffect,useRef,useState,type Dispatch,type SetStateAction,type CSSProperties} from 'react';
import {ArrowRight,Maximize2,Minus,Plus,GitBranch,Scan,LocateFixed,Lock,Clock,Check,CornerDownRight} from 'lucide-react';
import {Button} from '../../components/ui/Button';
import {UIStatus,UIWarning} from '../../components/ui/FormControls';
import {useWork} from '../work/store';
import {Person} from '../work/ui';
import {canWork} from '../work/selectors';
import {taskDisplayStatus} from '../work/runtime';
import {WorkMutationDialog,type WorkMutation} from '../work/WorkMutationDialog';
import {TaskMore} from './TaskActions';
import {taskStatusKey} from './collaborationPresentation';
import {executionLayout,GRAPH} from './executionLayout';
import {useWorkspaceDraft} from './useWorkspaceDraft';
import type {components} from '../../lib/api/schema';
import type {Task} from '../work/types';
export type GraphView={zoom:number;left:number;top:number};
type Props={tasks:Task[];onOpen:(task:Task,section?:'overview'|'records'|'flow')=>void;onDiscuss?:(task:Task)=>void;busyTask?:string;model?:components['schemas']['ExecutionMap'];cooperation?:boolean;planId?:string;onExternal?:(id:string)=>void;onFullscreen?:()=>void;full?:boolean;readOnly?:boolean;selectedTaskId?:string;focusTaskId?:string;view?:GraphView;onView?:Dispatch<SetStateAction<GraphView>>};
export function ExecutionMap({tasks,onOpen,onDiscuss,busyTask,model,cooperation=false,planId,onExternal,onFullscreen,full=false,readOnly=false,selectedTaskId,focusTaskId,view:externalView,onView}:Props){
 const p=useWork(),[stored,setStored]=useWorkspaceDraft('plan-graph:'+(planId??p.route.scopePlanId??'project'),{zoom:cooperation?1:.8,left:0,top:0}),view=externalView??stored,setView=onView??setStored,viewport=useRef<HTMLDivElement>(null),[mutation,setMutation]=useState<WorkMutation>(),arrow='dep'+useId().replaceAll(':',''),drag=useRef<{id:number;x:number;y:number;left:number;top:number}|null>(null);
 const size=cooperation?Object.fromEntries(Object.entries(GRAPH).map(([k,v])=>[k,parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--co-graph-'+k))||v])) as typeof GRAPH:GRAPH;
 const graph=executionLayout(tasks,p.state.handoffs,size);
 if(model){const rows=new Map<number,number>();graph.positions.clear();for(const task of tasks){const rank=model.nodes.find(n=>n.taskId===task.id)?.column??0,n=rows.get(rank)??0;rows.set(rank,n+1);graph.positions.set(task.id,{x:size.pad+rank*size.column,y:size.pad+n*size.row,rank});}graph.width=(Math.max(0,...rows.keys())+1)*size.column+size.pad;graph.height=Math.max(1,...rows.values())*size.row+size.pad;graph.edges=model.edges.filter(e=>e.kind!=='parent'&&tasks.some(t=>t.id===e.fromTaskId)&&tasks.some(t=>t.id===e.toTaskId)).map(e=>({from:e.fromTaskId,to:e.toTaskId,hard:e.kind==='hard',at:e.phase}));for(const e of model.edges)if(e.kind!=='parent'&&tasks.some(t=>t.id===e.toTaskId)&&!tasks.some(t=>t.id===e.fromTaskId))graph.external.set(e.toTaskId,[...(graph.external.get(e.toTaskId)??[]),e.fromTaskId]);}
 if(!model){const originals=graph.edges,skipped=new Set(tasks.filter(t=>t.executionException).map(t=>t.id)),next=originals.filter(e=>!skipped.has(e.from)&&!skipped.has(e.to));const incoming=(id:string,seen=new Set<string>()):string[]=>{if(seen.has(id))return [];seen.add(id);return originals.filter(e=>e.to===id).flatMap(e=>skipped.has(e.from)?incoming(e.from,new Set(seen)):[e.from]);};for(const e of originals)if(skipped.has(e.from)&&!skipped.has(e.to))for(const id of incoming(e.from))if(!next.some(v=>v.from===id&&v.to===e.to))next.push({...e,from:id});graph.edges=[...next,...originals.filter(e=>skipped.has(e.from)||skipped.has(e.to))];}
 useLayoutEffect(()=>{const el=viewport.current;if(el){el.scrollLeft=view.left;el.scrollTop=view.top;}},[planId,full,view.zoom]);
 useLayoutEffect(()=>{const id=focusTaskId??p.route.focusTaskId;if(id)viewport.current?.querySelector('[data-testid="execution-task-'+id+'"]')?.scrollIntoView({block:'nearest',inline:'center'});},[focusTaskId,p.route.focusTaskId,tasks.length]);
 const zoom=view.zoom,fit=()=>{const el=viewport.current;if(el)setView(v=>({...v,zoom:Math.max(.35,Math.min(1,(el.clientWidth-size.pad)/(graph.width),(el.clientHeight-size.pad)/(graph.height+40))),left:0,top:0}));},locate=()=>{const id=selectedTaskId??(p.route.view==='task'?p.route.id:undefined)??focusTaskId??p.route.focusTaskId??tasks.find(t=>(t.businessStatus??t.status)==='working'&&!t.executionException)?.id??tasks[0]?.id;if(id)viewport.current?.querySelector('[data-testid="execution-task-'+id+'"]')?.scrollIntoView({block:'center',inline:'center',behavior:'smooth'});};
 return <section className="judex-execution-map judex-route-graph"><div className="judex-execution-toolbar"><span><GitBranch/>{p.t('coopRoute')}</span><div><Button size="sm" isIconOnly aria-label={p.t('chatZoomOut')} onPress={()=>setView(v=>({...v,zoom:Math.max(.35,v.zoom-.1)}))}><Minus/></Button><small>{Math.round(zoom*100)}%</small><Button size="sm" isIconOnly aria-label={p.t('chatZoomIn')} onPress={()=>setView(v=>({...v,zoom:Math.min(1.2,v.zoom+.1)}))}><Plus/></Button><Button size="sm" onPress={fit}><Scan/>{p.t('taskDetailsFullscreenFit')}</Button><Button size="sm" isIconOnly aria-label={p.t('taskDetailsLocate')} data-focus-key={'route-locate-'+planId} onPress={locate}><LocateFixed/></Button>{!full&&onFullscreen&&<Button size="sm" variant="outline" aria-label={p.t('taskDetailsFullscreenView')} data-focus-key={'route-fullscreen-'+planId} onPress={onFullscreen}><Maximize2/>{p.t('taskDetailsFullscreenView')}</Button>}</div></div>
 {graph.invalid.length>0&&<UIWarning>{p.t('chatCycle')} {graph.invalid.join(', ')}</UIWarning>}
 {!tasks.length?<div className="judex-chat-empty"><GitBranch/><p>{p.t('chatEmptyGraph')}</p></div>:<div className="judex-execution-viewport" data-testid="execution-map" ref={viewport} onScroll={e=>{const el=e.currentTarget;setView(v=>({...v,left:el.scrollLeft,top:el.scrollTop}));}} onPointerDown={e=>{if((e.target as Element).closest('button,.card,.judex-execution-card'))return;const el=e.currentTarget;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,left:el.scrollLeft,top:el.scrollTop};el.setPointerCapture(e.pointerId);el.classList.add('judex-route-dragging');}} onPointerMove={e=>{if(drag.current){e.currentTarget.scrollLeft=drag.current.left+drag.current.x-e.clientX;e.currentTarget.scrollTop=drag.current.top+drag.current.y-e.clientY;}}} onPointerUp={e=>{if(drag.current){e.currentTarget.releasePointerCapture(drag.current.id);drag.current=null;e.currentTarget.classList.remove('judex-route-dragging');}}}>
 <div style={{width:graph.width*zoom,height:(graph.height+40)*zoom}}><div className="judex-execution-canvas" style={{width:graph.width,height:graph.height+40,transform:`scale(${zoom})`,'--graph-card-width':size.width+'px','--graph-card-height':size.height+'px'} as CSSProperties}>{[...new Set([...graph.positions.values()].map(v=>v.rank))].map(rank=><div className="judex-execution-stage" style={{left:size.pad+rank*size.column}} key={rank}>{p.t('chatStage',{n:rank+1})}<ArrowRight/></div>)}
 <svg className="judex-route-edges" width={graph.width} height={graph.height+40} aria-hidden="true"><defs><marker id={arrow} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs>{graph.edges.map((e,i)=>{const a=graph.positions.get(e.from)!,b=graph.positions.get(e.to)!,x=a.x+size.width,y=a.y+40+size.height/2,end=b.y+40+size.height/2,original=model?!!model.edges.find(v=>v.fromTaskId===e.from&&v.toTaskId===e.to&&v.original):tasks.some(t=>t.executionException&&(t.id===e.from||t.id===e.to)),bypass=!original&&b.rank-a.rank>1,path=bypass?`M ${x} ${y} C ${x+20} ${y},${x+20} ${size.pad},${x+44} ${size.pad} L ${b.x-44} ${size.pad} C ${b.x-20} ${size.pad},${b.x-20} ${end},${b.x} ${end}`:`M ${x} ${y} C ${x+36} ${y},${b.x-36} ${end},${b.x} ${end}`;return <path key={e.from+e.to+i} data-from={e.from} data-to={e.to} data-original={original} className={original?'judex-route-edge-original':!e.hard?'judex-execution-edge-soft':''} markerEnd={`url(#${arrow})`} d={path}/>;})}</svg>
 {tasks.map(task=>{const pos=graph.positions.get(task.id)!,display=taskDisplayStatus(task,p.state,model?.nodes.find(n=>n.taskId===task.id)?.blockers?.some(b=>b.phase==='start'||b.phase==='both')),blocked=display==='blocked',Icon=display==='skipped'?CornerDownRight:display==='accepted'?Check:blocked?Lock:Clock,hint=p.t(display==='skipped'?'taskDetailsSkipHint':display==='draft'?'taskDetailsDraftHint':display==='accepted'?'taskDetailsAcceptedHint':blocked?'taskDetailsWait':display==='ready'?'taskDetailsReady':'taskDetailsWorkingHint');return <Card key={task.id} data-testid={'execution-task-'+task.id} data-rank={pos.rank} data-stage={display} className={'judex-execution-card judex-co-task-card'+(canWork(p.state,task)?' judex-co-my-task':'')+(task.executionException?' judex-task-card-skipped':'')+((selectedTaskId??(p.route.view==='task'?p.route.id:undefined))===task.id?' judex-task-card-selected':'')} style={{left:pos.x,top:pos.y+40}}><div className="judex-task-card-top"><UIStatus className={'judex-task-status judex-task-status-'+display}>{p.t(display==='skipped'?'taskDetailsSkipped':display==='discarded'?'taskDetailsDiscarded':taskStatusKey(display))}</UIStatus><TaskMore task={task} onMutation={setMutation} readOnly={readOnly} onSection={section=>onOpen(task,section)}/></div><Button variant="ghost" className="judex-task-card-body judex-co-card-hit" data-focus-key={'route-task-'+task.id} aria-label={p.t('details')+' · '+p.text(task.title)} onPress={()=>onOpen(task)}><strong>{p.text(task.title)}</strong><div className="judex-task-card-people"><Person name={task.participantNames?.[0]} seatId={task.seatIds[0]} small/>{task.seatIds.length>1&&<small>+{task.seatIds.length-1}</small>}</div><p className="judex-task-excerpt">{p.text(task.expected)||p.t('taskDetailsNoDescription')}</p><span className="judex-task-card-hint" title={hint}><Icon/>{hint}</span>{task.parentId&&<small className="judex-task-meta">{p.t('chatParent')} · {p.text(p.state.tasks.find(t=>t.id===task.parentId)?.title??task.parentId)}</small>}</Button>{graph.external.has(task.id)&&<div className="judex-co-external-links">{graph.external.get(task.id)?.map(id=><Button key={id} size="sm" data-focus-key={'route-external-'+task.id+':'+id} onPress={()=>onExternal?.(id)}>{p.t('chatExternal')} · {p.text(p.state.tasks.find(t=>t.id===id)?.title??p.t('details'))}</Button>)}</div>}{onDiscuss&&<div className="judex-co-task-footer"><Button size="sm" variant="ghost" isPending={busyTask===task.id} data-testid={'task-discuss-'+task.id} onPress={()=>onDiscuss(task)}>{p.t('coopDiscussTask')}</Button></div>}</Card>;})}</div></div></div>}
 <div className="judex-route-graph-footnote"><span>{p.t('chatOrderHint')} {p.t('chatGraphConditions')}</span><span>{p.t(tasks.some(t=>t.executionException)?'taskDetailsOriginalEdges':'taskDetailsGraphPan')}</span></div>{mutation&&<WorkMutationDialog mutation={mutation} onClose={()=>setMutation(undefined)}/>}</section>;
}
