import {useLayoutEffect,useRef} from 'react';
import {Tabs,Dropdown,Label} from '@heroui/react';
import {FileText,GitBranch,Files,Plus,X,Maximize2,Minimize2,LayoutGrid,ArrowUpRight} from 'lucide-react';
import {Button} from '../../components/ui/Button';
import {useWork,WorkView} from '../work/store';
import {useWorkspaceTabs} from './useWorkspaceTabs';
import {workspaceKey,type WorkspaceTab} from './workspaceTabModel';
import {useReadingPosition} from './useReadingPosition';
import {WorkspacePanel} from './WorkspacePanel';
export function WorkspaceTabs({expanded,onExpand,onClose}:{expanded:boolean;onExpand:()=>void;onClose:()=>void}){
 const p=useWork(),model=useWorkspaceTabs(),bar=useRef<HTMLDivElement>(null),contextTaskId=p.route.scopeTaskId??(model.current?.view==='task'?model.current.id:undefined),task=p.state.tasks.find(t=>t.id===contextTaskId),planId=task?.planId??p.route.scopePlanId??(model.current?.view==='plan'?model.current.id:undefined);
 const tools:{tab:WorkspaceTab;label:string;icon:typeof FileText;testId:string}[]=[];
 if(contextTaskId)for(const section of ['overview','records','flow'] as const)tools.push({tab:{view:'task',id:contextTaskId,section},label:p.t(section==='overview'?'taskDetailsOverview':section==='records'?'taskDetailsRecords':'taskDetailsFlow'),icon:section==='flow'?GitBranch:FileText,testId:'task-'+section});
 tools.push({tab:planId?{view:'plan',id:planId}:{view:'plans'},label:p.t('coopPlanInfo'),icon:GitBranch,testId:'plans'},{tab:{view:'resources'},label:p.t('chatMaterials'),icon:Files,testId:'resources'});
 const info=(tab:WorkspaceTab)=>{const target=(tab.view==='task'?p.state.tasks:p.state.plans).find(v=>v.id===tab.id&&v.projectId===p.project.id);if(tab.view==='task'){const section=tab.section??'overview',title=p.t(section==='overview'?'taskDetailsOverview':section==='records'?'taskDetailsRecords':'taskDetailsFlow');return {title,objectName:p.text(target?.title??tab.id??''),icon:section==='flow'?GitBranch:FileText,full:title+' · '+p.text(target?.title??tab.id??'')};}const title=tab.view==='resources'?p.t('chatMaterials'):tab.view==='plans'?p.t('coopPlanInfo'):p.text(target?.title??tab.id??'');return {title,objectName:'',full:title,icon:tab.view==='resources'?Files:GitBranch};};
 useLayoutEffect(()=>{const list=bar.current?.querySelector('[role="tablist"]');if(!list)return;const reveal=()=>{const selected=[...list.querySelectorAll<HTMLElement>('[data-testid]')].find(el=>el.dataset.testid==='workspace-tab-'+model.active);selected?.scrollIntoView({block:'nearest',inline:'nearest'});};reveal();const frame=requestAnimationFrame(reveal),size=new ResizeObserver(reveal);size.observe(list);return()=>{cancelAnimationFrame(frame);size.disconnect();};},[model.active]);
 return <Tabs className="judex-workspace-root judex-task-workspace" selectedKey={model.active??'launcher'} onSelectionChange={key=>{if(key==='launcher')model.launcher();else{const tab=model.tabs.find(t=>workspaceKey(t)===key);if(tab)model.open(tab);}}}>
 <div className="judex-conversation-tabstrip judex-workspace-tabstrip" ref={bar}><Tabs.List className="judex-conversation-tabs" aria-label={p.t('chatWorkspaceTabs')}>{model.tabs.map(tab=>{const key=workspaceKey(tab),{title,full,icon:Icon}=info(tab);return <Tabs.Tab id={key} key={key} aria-label={full} data-testid={'workspace-tab-'+key} className={'judex-conversation-tab'+(model.active===key?' judex-conversation-tab-active':'')}><Icon size={14}/><span className="judex-conversation-tab-label" title={full}>{title}</span><Button className="judex-conversation-tab-close" aria-label={p.t('chatCloseTool')+' · '+full} onPointerDown={e=>{e.preventDefault();e.stopPropagation();}} onClick={e=>{e.stopPropagation();model.close(key);}}><X size={13}/></Button></Tabs.Tab>;})}{!model.active&&<Tabs.Tab id="launcher" className="judex-conversation-tab judex-conversation-tab-active" aria-label={p.t('chatChooseTool')}><LayoutGrid size={14}/><span className="judex-conversation-tab-label">{p.t('chatChooseTool')}</span></Tabs.Tab>}</Tabs.List>
 <Dropdown><Button data-testid="workspace-add-tool" aria-label={p.t('chatAddTool')}><Plus size={16}/></Button><Dropdown.Popover><Dropdown.Menu aria-label={p.t('chatChooseTool')} onAction={key=>{const tool=tools.find(t=>t.testId===key);if(tool)model.open(tool.tab);}}>{tools.map(tool=><Dropdown.Item id={tool.testId} key={tool.testId} textValue={tool.label} aria-label={tool.label}><tool.icon size={16}/><Label>{tool.label}</Label></Dropdown.Item>)}</Dropdown.Menu></Dropdown.Popover></Dropdown><div className="judex-workspace-window-controls"><Button data-testid="workspace-maximize" aria-label={p.t(expanded?'chatRestoreWorkspace':'chatMaxWorkspace')} onPress={onExpand}>{expanded?<Minimize2 size={15}/>:<Maximize2 size={15}/>}</Button><Button aria-label={p.t('chatCollapse')} onPress={onClose}><X size={17}/></Button></div></div>
 <Tabs.Panel id={model.active??'launcher'} className="judex-workspace-tab-content">{model.current?<WorkView view={model.current.view} id={model.current.id} section={model.current.section}><WorkspaceContent key={model.scope+':'+model.active} tabKey={model.active!}/></WorkView>:<div className="judex-workspace-launcher" data-testid="workspace-launcher"><div><h2>{p.t('chatChooseTool')}</h2><p>{p.t('chatChooseToolHint')}</p><div className="judex-workspace-launcher-list">{tools.map(tool=><Button key={tool.testId} data-testid={'work-nav-'+tool.testId} onPress={()=>model.open(tool.tab)}><tool.icon size={18}/><span>{tool.label}</span><ArrowUpRight size={14}/></Button>)}</div></div></div>}</Tabs.Panel>
 </Tabs>;
}
function WorkspaceContent({tabKey}:{tabKey:string}){const {project,state}=useWork();const ref=useReadingPosition('workspace:'+project.id+':'+(state.currentUserId??state.currentUser)+':'+tabKey);return <div className="judex-chat-panel-body judex-next-main" ref={ref}><WorkspacePanel/></div>;}
