import {Archive,FileText} from "lucide-react";
import {usePreview} from "./context";
import {Architecture} from "./cards";
import {sheetRows,type Material} from "./data";
export function pageCount(file:Material){return file.local?1:file.format==="pdf"?3:file.format==="pptx"?2:1;}
export function FileContent({file,page=1,zoom=100}:{file:Material;page?:number;zoom?:number}){
 const {locale,t,text}=usePreview(),en=locale==="en";
 if(file.local){
  if(file.format==="png")return <div className="judex-mp-image-reader"><img src={file.url} alt={text(file.name)} style={{maxWidth:zoom+"%"}}/></div>;
  if(file.format==="pdf")return <iframe className="judex-mp-pdf-reader" src={file.url} title={text(file.name)}/>;
  if(file.textContent!==undefined)return <pre className="judex-mp-source-reader">{file.textContent}</pre>;
  return <div className="judex-mp-unavailable"><FileText/><h3>{t("mpUnsupported")}</h3><p>{t("mpUnsupportedHint")}</p></div>;
 }
 if(file.format==="png")return <div className="judex-mp-image-reader"><div style={{width:zoom+"%"}}><Architecture/></div></div>;
 if(file.format==="xlsx")return <div className="judex-mp-spreadsheet"><div className="judex-mp-sheet-heading"><span>{en?"Development & acceptance":"研发与验收清单"}</span><small>{t("mpRows",{count:sheetRows.length})}</small></div><table><thead><tr><th>#</th>{(en?["Work item","Owner","Status","Progress"]:["工作项","负责人","状态","完成度"]).map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{sheetRows.map((row,i)=><tr key={i}><td>{i+1}</td><td>{row[en?1:0]}</td><td>{row[en?3:2]}</td><td><span className={row[6]===100?"judex-mp-cell-done":"judex-mp-cell-progress"}>{row[en?5:4]}</span></td><td><span className="judex-mp-progress-track"><i style={{width:row[6]+"%"}}/></span>{row[6]}%</td></tr>)}</tbody></table><div className="judex-mp-sheet-chart"><strong>{t("mpChartTitle")}</strong>{sheetRows.map((r,i)=><div key={i}><span>{r[en?1:0]}</span><i><b style={{width:r[6]+"%"}}/></i><small>{r[6]}%</small></div>)}</div><div className="judex-mp-sheet-bottom">Sheet 1 · {en?"Acceptance":"验收清单"}</div></div>;
 if(file.format==="json")return <pre className="judex-mp-source-reader">{JSON.stringify({materialId:"mat_shared_001",version:1,name:text(file.name),purpose:en?"Shared file design reference":"共享资料体验设计依据",uploader:{name:text(file.uploader),uploadedAt:file.time},project:{name:t("mpProject")},associations:[{type:"plan",name:t("mpPlanName"),actor:"Zhou Yu",associatedAt:"2026-10-08 10:05"},{type:"task",name:t("mpTaskName"),actor:"Lin Xiao",associatedAt:"2026-10-08 09:45"}],visibility:"project_members"},null,2)}</pre>;
 if(file.format==="zip")return <div className="judex-mp-archive-reader"><div><Archive/><h3>design-assets /</h3></div><p>{t("mpArchiveHint")}</p>{["documents/shared-file-experience.pdf","documents/file-preview-requirements.docx","screenshots/project-library.png","screenshots/discussion-panel.png","screenshots/message-card.png","data/material-example.json","notes/implementation.md","README.md"].map((v,i)=><div className="judex-mp-archive-row" key={v}><FileText/><span>{v}</span><small>{["2.4 MB","386 KB","842 KB","621 KB","492 KB","6 KB","18 KB","2 KB"][i]}</small></div>)}</div>;
 if(file.format==="pptx")return <div className="judex-mp-slide-reader" style={{zoom:zoom/100}}><small>JUDEX / DESIGN REVIEW · 0{page}</small><h1>{page===1?(en?"Files, in context.":"让资料回到工作中。"):(en?"One interaction, everywhere.":"三个入口，一致的交互。")}</h1><p>{page===1?(en?"A file has a purpose, a source, and a place in the conversation.":"每份资料都能说清用途、来源，以及它在工作中的位置。"):(en?"Preview the content. Understand the purpose. Follow the history.":"看内容，知用途，追溯每一次关联。")}</p><div>{(en?["Project library","Discussion panel","Message card"]:["项目资料库","讨论资料栏","会话文件卡片"]).map((v,i)=><section key={v}><strong>0{i+1}</strong><h3>{v}</h3><p>{en?"The same file, with the same interactions.":"同一份文件，同一套操作。"}</p></section>)}</div><footer>COLLABORATION EXPERIENCE / 2026.10</footer></div>;
 if(file.format==="md")return <article className="judex-mp-document" style={{zoom:zoom/100}}><small>IMPLEMENTATION / NOTES</small><h1>{en?"Shared file implementation notes":"共享资料实现约定"}</h1><p>{en?"The library, panel and messages use a single file record.":"资料库、讨论侧栏和消息附件使用同一份文件记录。"}</p><h2>{en?"01 · Stable version references":"01 · 固定版本引用"}</h2><p>{en?"Keep materialId and versionId together. Re-sharing a file adds a usage record and preserves the original uploader.":"文件引用同时保留 materialId 和 versionId。重新分享只新增使用记录，保留原上传人。"}</p><pre>{`FileReference {\n  materialId: string\n  versionId: string\n  purpose: string\n  associations: UsageRecord[]\n}`}</pre><h2>{en?"02 · Consistent interactions":"02 · 一致的交互"}</h2><ul>{(en?["Click the file cover or title to preview.","Details show purpose, source and association history.","Deleted files leave a traceable reference in history."]:["点击文件封面或标题，打开内容预览。","详情展示用途、来源和关联记录。","删除后，讨论历史保留可追溯的引用提示。"]).map(v=><li key={v}>{v}</li>)}</ul><h2>{en?"03 · Preview by format":"03 · 按格式展示内容"}</h2><p>{en?"Documents are paged, spreadsheets preserve rows and columns, images support zoom, and text retains its structure.":"文档按页阅读，表格保留行列，图片支持缩放，文本保持原有结构。"}</p></article>;
 return <article className="judex-mp-document" style={{zoom:zoom/100}}><div className="judex-mp-document-brand">J<span>JUDEX / COLLABORATION</span></div><small>{file.format.toUpperCase()} · {en?"WORKING MATERIAL":"工作材料"}</small><h1>{file.format==="docx"?(en?"File preview requirements":"资料预览需求说明"):page===1?(en?"Shared file experience":"共享资料体验方案"):page===2?(en?"Purpose and associations":"材料用途与关联"):en?"Preview and history":"内容预览与历史记录"}</h1><div className="judex-mp-document-meta">{text(file.uploader)} / 2026.10.08 / v{file.version}</div><p className="judex-mp-document-lead">{page===1?text(file.purpose):en?"Make every file’s purpose and origin readable in context.":"让每一份材料的用途、来源和使用场景清晰可见。"}</p><h2>{en?"01 · One file card":"01 · 统一文件卡片"}</h2><p>{en?"The upper area shows a visual preview. The lower area presents the filename, uploader, time and actions. The three entry points use the same structure.":"卡片上方展示文件缩略图，下方呈现文件名称、上传人、上传时间和操作。项目资料库、讨论侧栏与会话消息使用同一结构。"}</p><div className="judex-mp-document-callout"><strong>{t("mpPurpose")}</strong><p>{text(file.purpose)}</p></div><h2>{en?"02 · Purpose and provenance":"02 · 用途与来源"}</h2><p>{en?"Record the plan and task, the person who made the association, and the timestamp. Keep upload time separate from usage time.":"明确关联的计划和任务，记录关联人及关联时间。上传时间和使用时间分开呈现，能看清资料从哪里来、用到了哪里。"}</p><h2>{en?"03 · Reading experience":"03 · 阅读体验"}</h2><p>{en?"Open a modal to read the material without leaving the conversation. Use one details panel for all file formats.":"在弹窗中阅读材料，保留当前讨论位置。不同格式使用各自的内容展示方式，共用同一套详情。"}</p><footer>Judex · {en?"Collaboration experience":"协同体验优化"}<span>{page.toString().padStart(2,"0")}</span></footer></article>;
}
