import {useState} from "react";
import {ArrowLeft,ArrowUp,ArrowUpRight,Check,ChevronDown,Files,FolderOpen,Maximize2,MessageCircle,Minimize2,PanelRightClose,Paperclip,Plus,Search,ShieldCheck,Sparkles,Upload,X} from "lucide-react";
import {Button} from "../src/components/ui/Button";
import {EmptyState,PersonAvatar} from "../src/components/ui/Presentation";
import {UIInput,UIOption,UISelect,UITextArea} from "../src/components/ui/FormControls";
import type {MaterialPreviewKey} from "../src/i18n/materialPreview";
import {usePreview} from "./context";
import {FileCard} from "./cards";
import type {Material} from "./data";
const filters:[string,MaterialPreviewKey][]=[["all","mpAll"],["documents","mpDocuments"],["sheets","mpSheets"],["images","mpImages"],["other","mpOther"]];
function inCategory(file:Material,filter:string){return filter==="all"||filter==="documents"&&["pdf","docx","md","pptx"].includes(file.format)||filter==="sheets"&&file.format==="xlsx"||filter==="images"&&file.format==="png"||filter==="other"&&["zip","json","other"].includes(file.format);}
export function Library(){
 const p=usePreview(),{t,text}=p,[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[sort,setSort]=useState("type");
 const all=p.files.filter(f=>!f.deleted),files=all.filter(f=>inCategory(f,filter)&&[text(f.name),text(f.uploader),text(f.purpose)].join(" ").toLowerCase().includes(query.toLowerCase()));
 return <main className="judex-mp-library"><div className="judex-mp-project-heading"><div><p className="judex-mp-eyebrow">JUDEX / COLLABORATION</p><h1>{t("mpProject")}</h1><p>{t("mpSubtitle")}</p></div><Button variant="outline" onPress={()=>p.setMode("plan")}><MessageCircle/>{t("mpPlanChat")}<ArrowUpRight/></Button></div>
  <div className="judex-mp-project-tabs"><span><Files/>{t("mpLibrary")}<b>{all.length}</b></span><small><ShieldCheck/>{t("mpProjectShared")}</small></div>
  <div className="judex-mp-library-heading"><div><h2>{t("mpLibrary")}</h2><p>{t("mpScopeHint")}</p></div><Button variant="primary" onPress={()=>p.open({kind:"upload"})}><Upload/>{t("mpUpload")}</Button></div>
  <div className="judex-mp-library-toolbar"><div className="judex-mp-filters">{filters.map(([id,key])=><Button size="sm" key={id} aria-pressed={filter===id} onPress={()=>setFilter(id)}>{t(key)}</Button>)}</div><div className="judex-mp-search"><Search/><UIInput aria-label={t("mpSearch")} placeholder={t("mpSearch")} value={query} onChange={e=>setQuery(e.target.value)}/></div></div>
  <div className="judex-mp-results-heading"><span>{t("mpCount",{count:files.length})}</span><UISelect aria-label={t("mpSort")} value={sort} onChange={e=>setSort(e.target.value)}><UIOption value="type">{t("mpSortType")}</UIOption><UIOption value="recent">{t("mpSortRecent")}</UIOption></UISelect></div>
  {files.length?<div className="judex-mp-library-grid">{[...files].sort((a,b)=>sort==="recent"?b.time.localeCompare(a.time):["pdf","docx","xlsx","png","md","pptx","json","zip","other"].indexOf(a.format)-["pdf","docx","xlsx","png","md","pptx","json","zip","other"].indexOf(b.format)).map(f=><FileCard key={f.id} file={f}/>)}</div>:<EmptyState title={t("mpEmpty")} description={t("mpEmptyHint")} icon={<FolderOpen/>}/>}
 </main>;
}
function SharedPanel({expanded,toggleExpanded,close}:{expanded:boolean;toggleExpanded:()=>void;close:()=>void}){
 const p=usePreview(),{t,text}=p,[scope,setScope]=useState("current"),[query,setQuery]=useState("");
 const files=p.files.filter(f=>!f.deleted&&(scope!=="current"||(p.mode==="task"?f.task:f.usages.length>0))&&[text(f.name),text(f.uploader),text(f.purpose)].join(" ").toLowerCase().includes(query.toLowerCase()));
 return <aside className={"judex-mp-shared-panel"+(expanded?" judex-mp-shared-panel-expanded":"")}><div className="judex-mp-pane-tabs"><span><Files/>{t("mpLibrary")}</span><div><Button size="sm" isIconOnly aria-label={expanded?t("mpCollapsePanel"):t("mpExpandPanel")} onPress={toggleExpanded}>{expanded?<Minimize2/>:<Maximize2/>}</Button><Button size="sm" isIconOnly aria-label={t("mpHidePanel")} onPress={close}><X/></Button></div></div>
  <div className="judex-mp-panel-scroll"><div className="judex-mp-panel-heading"><div><h2>{t("mpLibrary")}</h2><p>{t("mpPanelHint")}</p></div><Button size="sm" isIconOnly variant="primary" aria-label={t("mpUpload")} onPress={()=>p.open({kind:"upload"})}><Plus/></Button></div><div className="judex-mp-panel-scope"><Button size="sm" aria-pressed={scope==="current"} onPress={()=>setScope("current")}>{t("mpRelatedOnly")}</Button><Button size="sm" aria-pressed={scope==="project"} onPress={()=>setScope("project")}>{t("mpAllProject")}</Button></div><div className="judex-mp-search"><Search/><UIInput aria-label={t("mpSearch")} placeholder={t("mpSearch")} value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="judex-mp-results-heading">{t("mpCount",{count:files.length})}</p><div className="judex-mp-panel-grid">{files.map(f=><FileCard compact key={f.id} file={f}/>)}</div>{!files.length&&<EmptyState title={t("mpEmpty")} icon={<FolderOpen/>}/>}</div>
 </aside>;
}
export function Discussion({draft,setDraft,onSend}:{draft:string;setDraft:(draft:string)=>void;onSend:()=>void}){
 const p=usePreview(),{t,text}=p,[panel,setPanel]=useState(true),[expanded,setExpanded]=useState(false),[query,setQuery]=useState("");
 const task=p.mode==="task",messages=p.messages.filter(m=>!task||m.scope==="task");
 return <main className={"judex-mp-discussion"+(panel?"":" judex-mp-panel-hidden")+(expanded?" judex-mp-panel-max":"")}>
  <aside className="judex-mp-sidebar"><Button className="judex-mp-back" size="sm" onPress={()=>p.setMode("library")}><ArrowLeft/>{t("mpBack")}</Button><div className="judex-mp-current-scope"><small>{t("mpRelated")}</small><strong>{t(task?"mpTaskName":"mpPlanName")}</strong><span className="judex-mp-scope-tag">{t(task?"mpTaskLabel":"mpPlanLabel")}</span></div><div className="judex-mp-search"><Search/><UIInput aria-label={t("mpChatSearch")} placeholder={t("mpChatSearch")} value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="judex-mp-sidebar-label">{t("mpNewDiscussion")}<span>2</span></div>{(["plan","task"] as const).filter(scope=>t(scope==="task"?"mpDesignThread":"mpMainThread").toLowerCase().includes(query.toLowerCase())).map(scope=><Button key={scope} className="judex-mp-thread-button" aria-pressed={p.mode===scope} onPress={()=>p.setMode(scope)}><MessageCircle/><span>{t(scope==="task"?"mpDesignThread":"mpMainThread")}</span></Button>)}<div className="judex-mp-sidebar-bottom"><ShieldCheck/><span>{t("mpProjectShared")}</span></div></aside>
  <section className="judex-mp-conversation"><div className="judex-mp-pane-tabs"><span><MessageCircle/>{t(task?"mpDesignThread":"mpPlanName")}<ChevronDown/></span><Button size="sm" isIconOnly aria-label={panel?t("mpHidePanel"):t("mpShowPanel")} onPress={()=>{setPanel(!panel);setExpanded(false);}}>{panel?<PanelRightClose/>:<Plus/>}</Button></div>
   <div className="judex-mp-conversation-heading"><div><h1>{t(task?"mpTaskName":"mpPlanName")}</h1><p>{t(task?"mpTaskDescription":"mpDiscussionDescription")}</p></div><div className="judex-mp-people"><PersonAvatar name={p.locale==="en"?"Lin Xiao":"林晓"} small/><PersonAvatar name={p.locale==="en"?"Zhou Yu":"周屿"} small/><PersonAvatar name={p.locale==="en"?"Chen Mu":"陈沐"} small/><small>{t("mpParticipants")}</small></div></div>
   <div className="judex-mp-messages"><div className="judex-mp-date-separator">{t("mpToday")}</div>{messages.map(message=><article className={"judex-mp-message"+(message.ai?" judex-mp-ai-message":"")} key={message.id}>{message.ai?<span className="judex-mp-ai-avatar"><Sparkles/></span>:<PersonAvatar name={text(message.actor)}/>}<div className="judex-mp-message-body"><div className="judex-mp-message-by"><strong>{text(message.actor)}</strong><time>{message.time}</time>{message.ai&&<span>AI</span>}</div>{text(message.text)&&<p>{text(message.text)}</p>}{!!message.fileIds.length&&<><div className="judex-mp-message-files">{message.fileIds.map(id=>{const file=p.files.find(f=>f.id===id);return file?<FileCard key={id} file={file} compact/>:null;})}</div><small className="judex-mp-file-message-caption"><Paperclip/>{t("mpSharedMessage",{count:message.fileIds.length})} · {t("mpChatFileHint")}</small></>}</div></article>)}</div>
   <div className="judex-mp-composer"><div className="judex-mp-composer-scope"><span>{t("mpRelated")}</span><span className="judex-mp-scope-tag">{t(task?"mpTaskName":"mpPlanName")}</span></div>{!!p.pending.length&&<div className="judex-mp-pending">{p.pending.map(id=>{const f=p.files.find(f=>f.id===id);return f&&!f.deleted?<span key={id}><Paperclip/>{text(f.name)}<Button size="sm" isIconOnly aria-label={t("mpSelectionRemove")} onPress={()=>p.setPending(p.pending.filter(v=>v!==id))}><X/></Button></span>:null;})}</div>}<UITextArea aria-label={t("mpCompose")} placeholder={t("mpCompose")} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.keyCode!==229){e.preventDefault();onSend();}}}/><div className="judex-mp-composer-actions"><Button size="sm" aria-label={t("mpAttach")} onPress={()=>p.open({kind:"choose"})}><Paperclip/>{t("mpAttach")}</Button><Button size="sm" variant="primary" isDisabled={!draft.trim()&&!p.pending.length} onPress={onSend}>{t("mpSend")}<ArrowUp/></Button></div><small>{t("mpChatBoundary")}</small></div>
  </section>
  {panel&&<SharedPanel expanded={expanded} toggleExpanded={()=>setExpanded(!expanded)} close={()=>{setPanel(false);setExpanded(false);}}/>}
 </main>;
}
