const copy={
 coopProjectSettings:["项目设置","Project settings"],
 coopHistoryHint:["选择左侧讨论，或新建项目会话。","Choose a discussion on the left, or start a project conversation."],coopHandoffDetails:["成果交接","Handoff details"],
 coopWholeConversation:["会话整体","Whole conversation"],
 coopPlanInfo:["计划信息","Plan information"],coopNoContext:["选择关联的计划或任务查看资料","Choose a linked plan or task to see its context"],coopLoadedRecords:["已加载 {count} 条记录","{count} records loaded"],coopContextChanged:["所选任务已不在会话范围内，请重新选择。","The selected task is outside this conversation. Choose the context again."],coopDiscussionMenu:["会话操作","Conversation actions"],coopTaskDiscussionScope:["任务讨论","Task discussions"],coopPlanDiscussionScope:["计划讨论","Plan discussions"],coopSameTopic:["同一会话在关联对象中共享","The same conversation is shared across linked objects"],coopDraftAttachmentHint:["正文草稿已保存；刷新后请重新选择附件。","Text draft saved. Select attachments again after a refresh."],
 coopActive:["进行中","Active"],coopStatus:["状态","Status"],
 coopHub:["项目协同","Project collaboration"],coopPlans:["计划","Plans"],coopDecisions:["需要我决定","Needs my decision"],coopDeliveries:["交付与接收","Deliveries & receipts"],coopMaterials:["共享资料","Shared materials"],
 coopHubHint:["从计划进入工作路线或讨论，重要事项由有权人确认。","Open a plan's work route or discussion. Authorized people confirm decisions."],
 coopPlanHint:["点击计划查看任务路线，或进入讨论一起推进。","Open a plan to see its task route, or enter its discussion."],coopRoute:["任务路线","Task route"],coopPreviewRoute:["预览路线","Preview route"],coopDiscuss:["进入讨论","Enter discussion"],coopDiscussTask:["任务讨论","Task discussion"],
 coopAll:["全部","All"],coopMine:["我负责","My work"],coopSearchPlans:["搜索计划…","Search plans…"],coopNoPlans:["暂无计划","No plans yet"],coopEmptyPlanHint:["先登记计划草稿，或从讨论中形成安排。","Register a plan draft or shape an arrangement in a discussion."],coopStartDiscussion:["先讨论","Start a discussion"],coopHistory:["项目讨论记录","Project discussions"],coopScope:["当前讨论范围","Discussion scope"],
 coopNewDiscussion:["新建会话","New conversation"],coopLinkObjects:["关联对象","Linked objects"],coopAssociationHint:["同一会话在所关联的计划和任务中可见，任务归属保持不变。","The same conversation appears in each linked plan and task. Task ownership stays unchanged."],coopImplicitPlan:["随任务关联可见","Visible through linked tasks"],coopLinkConflict:["关联已变化，请核对最新内容后重新提交。","Associations changed. Review the latest objects before submitting again."],
 coopNoDecisions:["当前没有需要你决定的事项","No decisions need your attention"],coopDecisionHint:["安排审批、成果接收、任务验收和计划验收分别处理。","Review arrangements, receipts, task acceptance and plan acceptance separately."],coopArrangement:["提案审批","Proposal review"],coopTaskAcceptance:["任务验收","Task acceptance"],coopPlanAcceptance:["计划验收","Plan acceptance"],coopReceipt:["交接接收","Handoff receipt"],coopReview:["查看并决定","Review & decide"],
 coopDeliveriesHint:["交接接收与任务验收各有明确来源和结果。","Receipts and task acceptance each retain their own evidence and result."],coopDelivery:["任务交付","Task delivery"],coopWaiting:["等待对方","Awaiting recipient"],coopToReceive:["待我接收","Needs my receipt"],coopToRevise:["需我补充","Needs my update"],coopNoDeliveries:["暂无交付与交接记录","No deliveries or handoffs"],
 coopViewRecords:["查看原记录","View original records"],coopTasksAccepted:["已验收 {done} / {total} 项任务","{done} / {total} tasks accepted"],coopMyTasks:["本人待开展或推进 {count} 项","{count} tasks need your work"],coopDraft:["草稿 · 尚未生效","Draft · not active"],coopOwner:["负责人","Owner"],coopBackHub:["返回项目协同","Back to project"],coopBackRoute:["返回任务路线","Back to task route"],coopMain:["主讨论","Main discussion"],coopPreview:["交互预览","Interaction preview"],coopNoConversations:["暂无相关会话","No related conversations"],coopTaskNotFound:["任务不存在或已不可访问","Task unavailable"],coopNoPublishedFlow:["尚未关联已发布流程","No published workflow linked"],coopExternal:["外部依赖","External dependency"],coopPrivateRolePreferences:["我的职位工作偏好","My role work preferences"],coopCancel:["已取消","Cancelled"],coopPending:["等待接收","Pending receipt"],coopNeedsRevision:["需补交","Needs revision"],coopDraftDelivery:["尚未发送","Not sent"],
} as const;
export const cooperationZh=Object.fromEntries(Object.entries(copy).map(([k,v])=>[k,v[0]])) as {[K in keyof typeof copy]:string};
export const cooperationEn=Object.fromEntries(Object.entries(copy).map(([k,v])=>[k,v[1]])) as {[K in keyof typeof copy]:string};
