export const materialsZh={
 matReading:'正在读取文件…',matRegistrationRetry:'原件已上传，登记尚未完成。重试会复用已上传版本。',
 matArchiveCount:'{count} 个文件',matHistoryRetained:'保留历史依据',matNoPreview:'暂无内容预览',matPreviewReady:'预览已就绪',matOriginalUnavailable:'原件暂不可读',
 matFindPlan:'搜索关联计划',matNoTask:'不关联任务',matPlanResolved:'所属计划由所选任务确定。',matContextUnavailable:'工作对象暂不可读取，请重试或重新选择。',
 matShareDraftHint:'选择已有讨论和工作范围，加入待发送附件。',matTargetDiscussion:'目标讨论',matFindDiscussion:'搜索讨论',matChooseDiscussion:'请选择讨论',matWorkScope:'本次使用的工作范围',matLoadedCount:'已加载 {count} 份',matOpenDiscussion:'打开讨论',
 matFailureInvalid:'文件内容损坏或与格式不符，请核对原文件。',matFailureOffice:'Office 文件转换失败，请核对文件后重试。',matFailureUnavailable:'预览服务暂不可用，可以重试或下载原文件。',matFailureLimit:'文件超过内容预览限制，可下载原文件查看。',matFailureUnsafe:'压缩包目录包含不支持的路径，请核对原文件。',
 matRegister:"登记资料",
 matLibrary:"共享资料",matUpload:"上传资料",matPurpose:"这份材料用来做什么",matDetails:"详情",matDelete:"删除",matPreview:"预览",matClose:"关闭",matCancel:"取消",matDownload:"下载原文件",matFileContents:"文件内容",matOrigin:"用途与来源",matInfo:"文件信息",matUses:"使用与关联记录",matUploader:"上传人",matUploaded:"上传时间",matSource:"上传来源",matVersion:"文件版本",matSize:"文件大小",matFormat:"文件格式",matProject:"所属项目",matPlan:"关联计划",matTask:"关联任务",matUnrecorded:"未记录",matNoPurpose:"未填写用途说明",matAll:"全部文件",matDocuments:"文档",matSheets:"表格",matImages:"图片",matOther:"其他",matSearch:"搜索文件、上传人或用途…",matCount:"{count} 份资料",matTypeSort:"按文件类型",matRecent:"最近上传",matMore:"加载更多",matEmpty:"尚无共享资料",matNoMatch:"没有匹配的资料",matScopeHint:"项目成员可见 · 点击文件封面预览内容",matCurrent:"当前工作",matWholeProject:"整个项目",matDeleted:"资料已删除",matDeleteTitle:"删除这份共享资料？",matDeleteHint:"删除后资料库和新附件选择器将移除它。历史消息保留引用，交付与验收使用的原文件仍可追溯。",matConfirmDelete:"确认删除",matPrepare:"准备内容预览",matPending:"内容预览正在处理…",matRetry:"重试",matFailed:"内容预览失败",matUnsupported:"此格式暂不支持内容预览，可下载原文件。",matRegistered:"已登记",matShared:"项目内共享",matChoose:"选择共享资料",matChooseHint:"引用已有文件的固定版本，保留上传人和使用记录。",matChooseConfirm:"添加到消息",matSelected:"已选 {count} 份",matSelectFile:"选择文件",matPurposeInput:"材料用途",matPurposePlaceholder:"说明文件用于什么工作，供哪些人参考。",matNone:"仅登记到项目",matPlanOnly:"仅关联计划",matUploadComplete:"资料已登记",matUploadRecord:"上传登记",matUploadSourceWeb:"网页",matUploadSourceCli:"本地 CLI",matUploadSourceAgent:"平台 AI",matNoUses:"尚无工作关联",matNext:"下一页",matPrevious:"上一页",matZoomIn:"放大",matZoomOut:"缩小",matReadError:"读取文件失败",matSend:"发送到讨论",matSort:"排序",matReady:"原件可读",matRecordProgress:"进度上报",matRecordDelivery:"成果交付",matRecordMessage:"讨论分享",matRecordMaterial:"资料登记",matRecordReference:"显式关联",matVersionChanged:"资料版本发生变化，请重新查看后操作。",matRemove:"移除附件",matReload:"重新加载",
} as const;
export const materialsEn:Record<keyof typeof materialsZh,string>={
 matReading:'Loading file…',matRegistrationRetry:'Original files were uploaded, but registration is incomplete. Retry reuses those versions.',
 matArchiveCount:'{count} files',matHistoryRetained:'Historical evidence retained',matNoPreview:'Preview unavailable',matPreviewReady:'Preview ready',matOriginalUnavailable:'Original unavailable',
 matFindPlan:'Search related plans',matNoTask:'No task',matPlanResolved:'The selected task determines its plan.',matContextUnavailable:'Work objects are unavailable. Retry or choose again.',
 matShareDraftHint:'Choose an existing discussion and work context, then add to the draft.',matTargetDiscussion:'Discussion',matFindDiscussion:'Search discussions',matChooseDiscussion:'Choose a discussion',matWorkScope:'Work context for this use',matLoadedCount:'{count} loaded',matOpenDiscussion:'Open discussion',
 matFailureInvalid:'The file is damaged or does not match its format. Check the original.',matFailureOffice:'Office conversion failed. Check the file and retry.',matFailureUnavailable:'The preview service is unavailable. Retry or download the original.',matFailureLimit:'The file exceeds the preview limit. Download the original to read it.',matFailureUnsafe:'The archive contains unsupported paths. Check the original.',
 matRegister:"Register files",
 matLibrary:"Shared files",matUpload:"Upload files",matPurpose:"What is this material for?",matDetails:"Details",matDelete:"Delete",matPreview:"Preview",matClose:"Close",matCancel:"Cancel",matDownload:"Download original",matFileContents:"File contents",matOrigin:"Purpose & source",matInfo:"File information",matUses:"Usage and associations",matUploader:"Uploaded by",matUploaded:"Uploaded at",matSource:"Upload source",matVersion:"File version",matSize:"File size",matFormat:"Format",matProject:"Project",matPlan:"Plan",matTask:"Task",matUnrecorded:"Not recorded",matNoPurpose:"No purpose supplied",matAll:"All files",matDocuments:"Documents",matSheets:"Spreadsheets",matImages:"Images",matOther:"Other",matSearch:"Search files, people or purpose…",matCount:"{count} files",matTypeSort:"File type",matRecent:"Newest first",matMore:"Load more",matEmpty:"No shared files yet",matNoMatch:"No matching files",matScopeHint:"Visible to project members · Click a cover to preview",matCurrent:"Current work",matWholeProject:"Whole project",matDeleted:"File deleted",matDeleteTitle:"Delete this shared file?",matDeleteHint:"The file will leave the library and attachment picker. Historical messages retain references and original files used in deliveries and acceptance remain traceable.",matConfirmDelete:"Delete file",matPrepare:"Prepare preview",matPending:"Preparing content preview…",matRetry:"Retry",matFailed:"Content preview failed",matUnsupported:"Preview is unavailable for this format. Download the original file.",matRegistered:"Registered",matShared:"Shared in project",matChoose:"Choose shared files",matChooseHint:"Reference an existing version while preserving its uploader and usage history.",matChooseConfirm:"Add to message",matSelected:"{count} selected",matSelectFile:"Choose files",matPurposeInput:"Purpose",matPurposePlaceholder:"Explain the work this file supports and who should use it.",matNone:"Project only",matPlanOnly:"Plan only",matUploadComplete:"Files registered",matUploadRecord:"Uploaded",matUploadSourceWeb:"Web",matUploadSourceCli:"Local CLI",matUploadSourceAgent:"Platform AI",matNoUses:"No work associations yet",matNext:"Next page",matPrevious:"Previous page",matZoomIn:"Zoom in",matZoomOut:"Zoom out",matReadError:"Could not read the file",matSend:"Share in discussion",matSort:"Sort",matReady:"Original available",matRecordProgress:"Progress report",matRecordDelivery:"Delivery",matRecordMessage:"Discussion share",matRecordMaterial:"File registration",matRecordReference:"Explicit association",matVersionChanged:"The file version changed. Review it again before continuing.",matRemove:"Remove attachment",matReload:"Reload",
};
