import {openTaskAction} from './workspace-helpers';
import {expect,test} from "@playwright/test";
import {registerMember,command,arrange} from "./cooperation-business-helpers";
test.setTimeout(120000);
test("COOP-A01 real hub, lazy concurrent task main, shared scopes, association versions and two users",async({browser},info)=>{
 const ca=await browser.newContext({viewport:{width:1440,height:1000}}),cb=await browser.newContext({viewport:{width:1440,height:1000}});
 try{
  const a=await ca.newPage(),b=await cb.newPage();await registerMember(a,"协同甲");const emailB=await registerMember(b,"协同乙");
  const project=await command(a,"post","/projects",{title:"项目协同验收"}),root=`/projects/${project.id}`;
  const flow=await command(a,"post",root+"/workflows",{name:"核对流程",nodes:[{id:"work",name:"实现与核对",responsibility:"核对事实与证据，不自动验收",allowedPositionIds:[],defaultApprovalPolicy:"all"}],advisoryEdges:[]});const version=(await command(a,"get",root+`/workflows/${flow.id}/versions`)).items[0];await command(a,"post",root+`/workflows/${flow.id}/publish`,{expectedVersion:1,draftHash:version.draftHash});
  const role=await command(a,"post",root+"/positions",{name:"核对岗",prompt:"collaboration-e2e-duty：核对事实，不验收",nodeBindings:[{workflowId:flow.id,nodeId:"work"}]});const user=(await command(a,"get","/auth/session")).user;const identity=await command(a,"post",root+"/identities",{positionId:role.id,userId:user.id});
  const invite=await command(a,"post",root+"/invitations",{targetEmail:emailB,positionIds:[role.id]});const offer=(await command(b,"get","/me/invitations")).items.find((v:any)=>v.id===invite.id);await command(b,"post",`/invitations/${invite.id}/accept`,{expectedVersion:offer?.version??1});
  const origin=await command(a,"post",root+"/topics",{title:"形成上线计划",initialMessage:"明确首版目标"});const {plan,task}=await arrange(a,project.id,origin.id,identity.id,flow.id);
  const secondPlan=await command(a,"post",root+"/plans",{title:"体验改进",ownerIdentityId:identity.id});const secondTask=await command(a,"post",root+"/tasks",{title:"错误文案",planId:secondPlan.id,participantIdentityIds:[identity.id],reviewerIdentityId:identity.id});
  const hubRequests:string[]=[];const track=(r:any)=>{if(r.method()==="GET"&&new RegExp("/api/v1/projects/"+project.id+"/tasks/[^/?]+(?:\\?|$)").test(r.url()))hubRequests.push(r.url());};a.on("request",track);
  await a.goto("/");await a.getByTestId("project-enter-"+project.id).click();await expect(a.getByTestId("hub-tab-plans")).toBeVisible();await expect(a.getByTestId("plan-card-"+plan.id)).toBeVisible();await expect(a.getByRole("button",{name:"模拟本地推送",exact:true})).toHaveCount(0);
  a.off("request",track);expect(hubRequests).toEqual([]);
  const before=(await command(a,"get",root+"/topics")).totalCount;expect((await command(a,"get",root+`/tasks/${task.id}`)).mainTopicId).toBeNull();
  await a.getByTestId("plan-card-"+plan.id).locator(".judex-co-card-hit").click();await expect(a.getByTestId("execution-task-"+task.id)).toBeVisible();await a.getByTestId("task-discuss-"+task.id).click();await expect(a).toHaveURL(new RegExp(`/tasks/${task.id}/chat/`));await expect(a.getByTestId("work-discussion-input")).toBeVisible();
  const main=(await command(a,"get",root+`/tasks/${task.id}`)).mainTopicId;const replay=await Promise.all([command(a,"post",root+`/tasks/${task.id}/main-topic`),command(b,"post",root+`/tasks/${task.id}/main-topic`)]);expect(replay.every(v=>v.mainTopicId===main)).toBe(true);expect((await command(a,"get",root+"/topics")).totalCount).toBe(before+1);
  await a.getByTestId("work-discussion-input").fill("仅保存在甲的草稿");await ca.setOffline(true);await a.getByTestId("send-work-message").click();await expect(a.getByTestId("work-discussion-input")).toHaveValue("仅保存在甲的草稿");await ca.setOffline(false);await b.goto(`/projects/${project.id}/tasks/${task.id}/chat/${main}`);await expect(b.getByTestId("work-discussion-input")).toHaveValue("");
  const shared=await command(a,"post",root+"/topics",{title:"共同核对",links:[{objectType:"task",objectId:task.id},{objectType:"task",objectId:secondTask.id}]});
  await command(a,"post",root+"/submissions",{clientSubmissionId:crypto.randomUUID(),purpose:"message",topicId:shared.id,text:"跨两个计划的同一条公开消息"});
  await a.goto(`/projects/${project.id}/plans/${plan.id}/chat/${shared.id}`);await b.goto(`/projects/${project.id}/plans/${secondPlan.id}/chat/${shared.id}`);await expect(a.getByTestId("scoped-topic-"+shared.id)).toBeVisible();await expect(b.getByTestId("scoped-topic-"+shared.id)).toBeVisible();await expect(b.getByTestId("chat-thread")).toContainText("跨两个计划的同一条公开消息");
  const updated=await command(a,"put",root+`/topics/${shared.id}/links`,{expectedLinksVersion:shared.linksVersion,targetRefs:[{objectType:"task",objectId:task.id},{objectType:"task",objectId:secondTask.id},{objectType:"plan",objectId:secondPlan.id}]});expect(updated.linksVersion).toBe(shared.linksVersion+1);
  const sb=await command(b,"get","/auth/session");const stale=await b.request.put("/api/v1"+root+`/topics/${shared.id}/links`,{headers:{"X-CSRF-Token":sb.csrfToken,"Idempotency-Key":crypto.randomUUID()},data:{expectedLinksVersion:shared.linksVersion,targetRefs:[]}});expect(stale.status()).toBe(409);
  expect((await command(a,"get",root+`/tasks/${task.id}`)).planId).toBe(plan.id);expect((await command(a,"get",root+`/tasks/${secondTask.id}`)).planId).toBe(secondPlan.id);
  const scoped=await command(a,"get",root+`/topics?planId=${secondPlan.id}&q=共同&limit=1`);expect(scoped.totalCount).toBe(1);expect(scoped.items[0].id).toBe(shared.id);
  await a.screenshot({path:info.outputPath("cooperation-two-user-chat.png"),fullPage:true});await info.attach("cooperation-proof",{body:JSON.stringify({projectId:project.id,planId:plan.id,taskId:task.id,taskMainTopicId:main,sharedTopicId:shared.id,linksVersion:updated.linksVersion,taskStatus:(await command(a,"get",root+`/tasks/${task.id}`)).status}),contentType:"application/json"});
 }finally{await ca.close();await cb.close();}
});
test("COOP-A02 acceptance rejects changed snapshots and closes task then owner plan acceptance",async({browser},info)=>{
 const context=await browser.newContext();try{
  const page=await context.newPage();await registerMember(page,"固定验收核对");
  const project=await command(page,"post","/projects",{title:"验收快照验证"}),root=`/projects/${project.id}`;
  const flow=await command(page,"post",root+"/workflows",{name:"核对",nodes:[{id:"work",name:"核对",responsibility:"核对固定证据",allowedPositionIds:[],defaultApprovalPolicy:"all"}],advisoryEdges:[]});const v=(await command(page,"get",root+`/workflows/${flow.id}/versions`)).items[0];await command(page,"post",root+`/workflows/${flow.id}/publish`,{expectedVersion:1,draftHash:v.draftHash});
  const role=await command(page,"post",root+"/positions",{name:"核对岗"}),user=(await command(page,"get","/auth/session")).user,identity=await command(page,"post",root+"/identities",{positionId:role.id,userId:user.id});
  const origin=await command(page,"post",root+"/topics",{title:"固定来源",initialMessage:"固定范围"});const {task}=await arrange(page,project.id,origin.id,identity.id,flow.id);
  await command(page,"post",root+`/tasks/${task.id}/start`,{expectedVersion:task.version,identityId:identity.id});const working=await command(page,"get",root+`/tasks/${task.id}`);
  await command(page,"post",root+`/tasks/${task.id}/reports`,{kind:"delivery",text:"FROZEN_ORIGINAL_REPORT 固定交付正文",identityId:identity.id,expectedTaskVersion:working.version});
  await page.goto(`/projects/${project.id}?tab=decisions`);await page.getByTestId("decision-open-"+task.id).click();await expect(page.getByRole("dialog")).toContainText("FROZEN_ORIGINAL_REPORT");
  const frozenButton=page.getByTestId("confirm-final-acceptance");await expect(frozenButton).toBeEnabled();
  const current=await command(page,"get",root+`/tasks/${task.id}`);const draft=await command(page,"post",root+"/proposals",{kind:"work_change",reason:"变更完成条件以验证旧快照",changes:[{operation:"update_scope",targetType:"task",targetId:task.id,expectedVersion:current.version,fields:{acceptanceCriteria:"新的完成条件"}}]});const initial=await command(page,"get",root+`/proposals/${draft.id}/review`);await command(page,"post",root+`/proposals/${draft.id}/submit`,{expectedVersion:draft.version,draftHash:initial.reviewHash});const review=await command(page,"get",root+`/proposals/${draft.id}/review`);await command(page,"post",root+`/proposals/${draft.id}/decisions`,{decision:"approve",expectedVersion:review.version,reviewId:review.reviewId,reviewHash:review.reviewHash,slotIds:review.slots.filter((s:any)=>s.canDecide).map((s:any)=>s.id),actingBindingVersions:review.slots.filter((s:any)=>s.canDecide&&s.authorityType==="identity").map((s:any)=>({identityId:s.authorityId,bindingVersion:s.bindingVersion}))});
  // Hold the old displayed snapshot even if the overview refreshes in the background.
  await expect(page.getByRole("dialog")).toContainText("FROZEN_ORIGINAL_REPORT");await expect.poll(async()=> (await command(page,"get",root+`/tasks/${task.id}`)).status).not.toBe("accepted");
  if(await frozenButton.isEnabled()){const response=page.waitForResponse(r=>r.url().endsWith(`/tasks/${task.id}/acceptances`)&&r.request().method()==="POST");await frozenButton.click();expect((await response).status()).toBe(409);}else await expect(frozenButton).toBeDisabled();
  expect((await command(page,"get",root+`/tasks/${task.id}`)).status).not.toBe("accepted");await page.screenshot({path:info.outputPath("stale-acceptance-snapshot.png"),fullPage:true});
  await page.getByRole("dialog").getByRole("button",{name:"关闭",exact:true}).click();let revised=await command(page,"get",root+`/tasks/${task.id}`);if(revised.status==="ready"){await command(page,"post",root+`/tasks/${task.id}/start`,{expectedVersion:revised.version,identityId:identity.id});revised=await command(page,"get",root+`/tasks/${task.id}`);}
  await command(page,"post",root+`/tasks/${task.id}/reports`,{kind:"delivery",text:"FRESH_DELIVERY 新条件下的交付",identityId:identity.id,expectedTaskVersion:revised.version});
  await page.getByTestId("decision-open-"+task.id).click();await expect(page.getByRole("dialog")).toContainText("FRESH_DELIVERY");await page.getByTestId("confirm-final-acceptance").click();await expect.poll(async()=> (await command(page,"get",root+`/tasks/${task.id}`)).status).toBe("accepted");
  const plan=(await command(page,"get",root+"/plans")).items.find((p:any)=>p.title==="首版上线");await page.getByTestId("decision-open-"+plan.id).click();await page.getByTestId("confirm-final-acceptance").click();await expect.poll(async()=> (await command(page,"get",root+`/plans/${plan.id}`)).status).toBe("accepted");

 }finally{await context.close();}
});
test("COOP-A03 empty project can register a draft and blank main discussion without activating work",async({browser})=>{
 const context=await browser.newContext();try{
  const page=await context.newPage();await registerMember(page,"空项目起步");const project=await command(page,"post","/projects",{title:"空项目"}),root=`/projects/${project.id}`;await page.goto(`/projects/${project.id}`);
  await page.getByRole("button",{name:/开启一个计划|New plan/,exact:true}).first().click();await page.getByTestId("new-work-title").fill("先登记目标");await page.getByTestId("create-work-draft").click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page).toHaveURL(/\/plans\/[^/]+\/route/);
  const plans=(await command(page,"get",root+"/plans")).items;expect(plans).toHaveLength(1);expect(plans[0].status).toBe("draft");expect(plans[0].mainTopicId).toBeTruthy();const history=await command(page,"get",root+`/topics/${plans[0].mainTopicId}/messages`);expect(history.items).toEqual([]);expect((await command(page,"get",root+"/tasks")).items).toEqual([]);
 }finally{await context.close();}
});

test("COOP-A04 real handoff rejection, resubmission and receipt preserve formal task acceptance",async({browser},info)=>{
 const ca=await browser.newContext(),cb=await browser.newContext();try{
  const a=await ca.newPage(),b=await cb.newPage();await registerMember(a,"发送者");const email=await registerMember(b,"接收者"),user=(await command(a,"get","/auth/session")).user;
  const project=await command(a,"post","/projects",{title:"交接闭环"}),root=`/projects/${project.id}`;
  const flow=await command(a,"post",root+"/workflows",{name:"交付核对",nodes:[{id:"work",name:"核对",responsibility:"固定版本独立接收",allowedPositionIds:[],defaultApprovalPolicy:"all"}],advisoryEdges:[]}),fv=(await command(a,"get",root+`/workflows/${flow.id}/versions`)).items[0];await command(a,"post",root+`/workflows/${flow.id}/publish`,{expectedVersion:1,draftHash:fv.draftHash});
  const role=await command(a,"post",root+"/positions",{name:"协作职责",nodeBindings:[{workflowId:flow.id,nodeId:"work"}]}),sender=await command(a,"post",root+"/identities",{positionId:role.id,userId:user.id});const invite=await command(a,"post",root+"/invitations",{targetEmail:email,positionIds:[role.id]});const offer=(await command(b,"get","/me/invitations")).items.find((v:any)=>v.id===invite.id);await command(b,"post",`/invitations/${invite.id}/accept`,{expectedVersion:offer?.version??1});const receiver=(await command(a,"get",root+"/identities")).items.find((v:any)=>v.currentBinding?.userId!==(user.id)&&v.templateId===role.id);
  const origin=await command(a,"post",root+"/topics",{title:"明确交接",initialMessage:"先交付，再确认来源"}),{task}=await arrange(a,project.id,origin.id,sender.id,flow.id);await command(a,"post",root+`/tasks/${task.id}/reports`,{kind:"delivery",text:"FIXED_HANDOFF_REPORT 原始交付不会被接收替代",identityId:sender.id,expectedTaskVersion:task.version});
  const handoff=await command(a,"post",root+"/handoffs",{title:"交接核对",kind:"stage",targetTaskId:task.id,receiverIdentityId:receiver.id,sources:[{sourceTaskId:task.id,senderIdentityId:sender.id}]}),source=(await command(a,"get",root+"/handoffs")).items.find((h:any)=>h.id===handoff.id).sources[0];
  await a.goto(`/projects/${project.id}?tab=deliveries&view=handoff&item=${handoff.id}`);await a.getByTestId("send-"+source.id).click();await b.goto(`/projects/${project.id}?tab=decisions&view=handoff&item=${handoff.id}`);await b.getByTestId("reject-"+source.id).click();await b.getByTestId("work-reason").fill("请补充核对范围");await b.getByTestId("confirm-work-reason").click();await expect.poll(async()=> (await command(a,"get",root+"/handoffs")).items.find((h:any)=>h.id===handoff.id).sources[0].state).toBe("rejected");
  expect((await command(a,"get",root+`/tasks/${task.id}`)).status).toBe("rework");await a.goto(`/projects/${project.id}?tab=deliveries&view=task&item=${task.id}`);await openTaskAction(a,"提交交付");await a.getByTestId("collaboration-report-body").fill("REVISED_HANDOFF_REPORT 新版正式交付");await a.getByTestId("collaboration-submit-record").click();await expect(a.getByTestId("collaboration-report-body")).toHaveCount(0);await expect.poll(async()=>(await command(a,"get",root+`/tasks/${task.id}`)).status).toBe("delivered");await a.goto(`/projects/${project.id}?tab=deliveries&view=handoff&item=${handoff.id}`);
  await a.getByTestId("revise-"+source.id).click();await a.getByTestId("report-body").fill("补充核对范围，引用新版固定交付");await a.getByTestId("submit-report").click();await expect.poll(async()=> (await command(a,"get",root+"/handoffs")).items.find((h:any)=>h.id===handoff.id).sources[0].state).toBe("pending");await b.getByTestId("receive-"+source.id).click();await expect.poll(async()=> (await command(a,"get",root+"/handoffs")).items.find((h:any)=>h.id===handoff.id).sources[0].state).toBe("accepted");
  expect((await command(a,"get",root+`/tasks/${task.id}`)).status).toBe("delivered");expect((await command(a,"get",root+`/tasks/${task.id}/reports`)).items.some((r:any)=>r.text.includes("FIXED_HANDOFF_REPORT"))).toBe(true);await b.reload();await expect(b.getByRole("dialog")).toContainText("补充核对范围");await info.attach("handoff-proof",{body:JSON.stringify({projectId:project.id,taskId:task.id,handoffId:handoff.id,sources:(await command(a,"get",root+"/handoffs")).items.find((h:any)=>h.id===handoff.id).sources}),contentType:"application/json"});
 }finally{await ca.close();await cb.close();}
});

test("COOP-A05 lists beyond fifty restore pages and search before paging without task fanout",async({browser},info)=>{
 const c=await browser.newContext();try{const page=await c.newPage();await registerMember(page,"分页核对");const project=await command(page,"post","/projects",{title:"分页规模"}),root=`/projects/${project.id}`;const plans:any[]=[];for(let i=0;i<55;i++)plans.push(await command(page,"post",root+"/plans",{title:`规模计划 ${i}`}));
  const requests:string[]=[];page.on("request",r=>{if(r.method()==="GET"&&r.url().includes(root+"/tasks/"))requests.push(r.url());});await page.goto(root);await expect(page.locator('[data-testid^="plan-card-"]')).toHaveCount(50);await page.getByRole("button",{name:"加载更多",exact:true}).click();await expect(page.locator('[data-testid^="plan-card-"]')).toHaveCount(55);await page.reload();await expect(page.locator('[data-testid^="plan-card-"]')).toHaveCount(55);expect(requests).toEqual([]);await page.getByRole("textbox",{name:"搜索计划…",exact:true}).fill("规模计划 0");await expect(page.locator('[data-testid^="plan-card-"]')).toHaveCount(1);
  const plan=plans[0],topics:any[]=[];for(let i=0;i<55;i++)topics.push(await command(page,"post",root+"/topics",{title:`范围会话 ${i}`,links:[{objectType:"plan",objectId:plan.id}]}));await page.goto(`${root}/plans/${plan.id}/chat/${plan.mainTopicId}`);await page.getByTestId("work-discussion-input").fill("分页与搜索保留草稿");await page.locator(".judex-collab-search input").fill("范围会话 0");await expect(page.getByTestId("scoped-topic-"+topics[0].id)).toBeVisible();await expect(page.locator('[data-testid^="scoped-topic-"]')).toHaveCount(1);await expect(page.getByTestId("work-discussion-input")).toHaveValue("分页与搜索保留草稿");expect(page.url()).toContain(plan.mainTopicId);await info.attach("paging-proof",{body:JSON.stringify({plans:55,topics:55,taskDetailRequests:requests}),contentType:"application/json"});
 }finally{await c.close();}
});
