import {test,expect,type Page} from "@playwright/test";
import {createHash,randomUUID} from "node:crypto";
import {execFileSync} from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import {command,registerMember,setupCooperation} from "./cooperation-business-helpers";
test.setTimeout(180000);
const fixtures=path.resolve("tests/fixtures/materials");
async function upload(page:Page,root:string,name:string){
 const raw=fs.readFileSync(path.join(fixtures,name)),checksum=createHash("sha256").update(raw).digest("hex"),session=await command(page,"get","/auth/session");
 const up=await command(page,"post",root+"/uploads",{name,size:raw.length,sha256:checksum,mime:"application/octet-stream",kind:"file",purpose:"用于真实资料验收"});
 for(let n=0;n<up.partCount;n++){const part=raw.subarray(n*up.partSize,(n+1)*up.partSize);const response=await page.request.put("/api/v1"+root+`/uploads/${up.id}/parts/${n+1}`,{data:part,headers:{"X-CSRF-Token":session.csrfToken,"X-Judex-Part-SHA256":createHash("sha256").update(part).digest("hex")}});expect(response.ok(),await response.text()).toBe(true);}
 return command(page,"post",root+`/uploads/${up.id}/complete`,{});
}
async function remove(page:Page,root:string,file:any){const session=await command(page,"get","/auth/session");return page.request.delete("/api/v1"+root+`/materials/${file.materialId??file.id}`,{headers:{"X-CSRF-Token":session.csrfToken,"Idempotency-Key":randomUUID()},data:{expectedCurrentVersionId:file.versionId??file.id}});}
test("MAT01 real files preview, two-sheet Office conversion, Range and failure retry",async({browser},info)=>{
 const context=await browser.newContext(),page=await context.newPage();try{
  await registerMember(page,"格式预览验收");const project=await command(page,"post","/projects",{title:"真实文件预览"}),root=`/projects/${project.id}`;
  for(const ext of ["pdf","docx","xlsx","png","md","pptx","json","zip"]){const name="acceptance."+ext,file=await upload(page,root,name);await command(page,"post",root+`/material-versions/${file.id}/preview`);await expect.poll(async()=>(await command(page,"get",root+`/material-versions/${file.id}/preview`)).status,{timeout:120000}).toBe("ready");const content=await page.request.get("/api/v1"+root+`/material-versions/${file.id}/preview/content`);expect(content.ok()).toBe(true);const bytes=await content.body();if(["pdf","docx","xlsx","pptx"].includes(ext))expect(bytes.subarray(0,5).toString()).toBe("%PDF-");if(ext==="md")expect(bytes.toString()).toContain("MARKDOWN_SOURCE_UNIQUE");if(ext==="json")expect(bytes.toString()).toContain("JSON_SOURCE_UNIQUE");if(ext==="zip")expect(bytes.toString()).toContain("nested/manifest.json");
   const range=await page.request.get("/api/v1"+root+`/material-versions/${file.id}/content`,{headers:{Range:"bytes=0-15"}});expect(range.status()).toBe(206);expect((await range.body()).length).toBe(16);
  }
  let cursor="";const seen=new Set<string>();do{const result=await command(page,"get",root+"/materials?limit=2&sort=type"+(cursor?"&cursor="+encodeURIComponent(cursor):""));for(const item of result.items){expect(seen.has(item.id)).toBe(false);seen.add(item.id);}cursor=result.nextCursor??"";}while(cursor);expect(seen.size).toBe(8);
  await page.goto(`/projects/${project.id}?tab=materials`);await expect(page.locator(".judex-material-grid>.judex-material-card")).toHaveCount(8);await page.screenshot({path:info.outputPath("real-library.png"),fullPage:true});
  const xlsx=page.locator(".judex-material-grid .judex-material-card").filter({hasText:"acceptance.xlsx"});await xlsx.locator(".judex-material-cover").click();await expect(page.getByRole("dialog").locator(".judex-material-reader-toolbar")).toContainText("1 / 2",{timeout:30000});await page.getByRole("button",{name:"下一页",exact:true}).click();await expect(page.getByRole("dialog").locator(".judex-material-reader-toolbar")).toContainText("2 / 2");await page.screenshot({path:info.outputPath("real-xlsx-second-sheet.png")});await page.getByRole("button",{name:"关闭",exact:true}).last().click();
  for(const name of ["unsafe.zip","corrupt.docx"]){const file=await upload(page,root,name);await command(page,"post",root+`/material-versions/${file.id}/preview`);await expect.poll(async()=>(await command(page,"get",root+`/material-versions/${file.id}/preview`)).status,{timeout:120000}).toBe("failed");const original=await page.request.get("/api/v1"+root+`/material-versions/${file.id}/content`);expect(original.ok()).toBe(true);expect((await original.body()).equals(fs.readFileSync(path.join(fixtures,name)))).toBe(true);await command(page,"post",root+`/material-versions/${file.id}/preview`);await expect.poll(async()=>(await command(page,"get",root+`/material-versions/${file.id}/preview`)).status,{timeout:120000}).toBe("failed");await page.goto(`/projects/${project.id}?tab=materials`);const status=page.locator('.judex-material-card').filter({hasText:name}).locator('.judex-material-status');await expect(status).toHaveAttribute('data-original-status','ready');await expect(status).toHaveAttribute('data-preview-status','failed');await expect(status).toContainText('原件可读');await expect(status).toContainText('内容预览失败');}
 }finally{await context.close();}
});
test("MAT02 task progress links files to its actual plan, picker reuses a version, delete preserves history",async({browser},info)=>{
 const f=await setupCooperation(browser),{a,b,ca,cb,root,project,task,plan,identity}=f;try{
  await command(a,"post",root+`/tasks/${task.id}/start`,{expectedVersion:task.version,identityId:identity.id});const working=await command(a,"get",root+`/tasks/${task.id}`),file=await upload(a,root,"acceptance.md");
  const topicsBefore=(await command(a,"get",root+"/topics")).items.length;
  await command(a,"post",root+`/tasks/${task.id}/reports`,{kind:"progress",text:"LOCAL_PROGRESS_MATERIAL_EVIDENCE",identityId:identity.id,expectedTaskVersion:working.version,materialVersionIds:[file.id]});
  expect((await command(a,"get",root+"/topics")).items.length).toBe(topicsBefore);const library=(await command(a,"get",root+`/materials?linkedObjectType=plan&linkedObjectId=${plan.id}`)).items;expect(library).toHaveLength(1);expect(library[0].associations).toEqual(expect.arrayContaining([expect.objectContaining({type:"task",id:task.id}),expect.objectContaining({type:"plan",id:plan.id})]));
  const main=(await command(a,"post",root+`/tasks/${task.id}/main-topic`,{})).topic;
  await a.goto(`/projects/${project.id}/tasks/${task.id}/chat/${main.id}`);await a.getByRole("button",{name:"添加资料",exact:true}).click();await a.getByRole("button",{name:"选择共享资料",exact:true}).click();await a.getByRole("dialog").locator('.judex-material-picker-card>strong').filter({hasText:/^acceptance\.md$/}).click();await a.getByRole("button",{name:"添加到消息",exact:true}).click();await a.getByTestId("work-discussion-input").fill("DISCUSSION_SAME_VERSION");await a.getByTestId("send-work-message").click();
  await expect.poll(async()=>(await command(a,"get",root+`/material-versions/${file.id}/usages`)).items.some((u:any)=>u.kind==="message"&&u.topicId===main.id)).toBe(true);expect((await command(a,"get",root+"/materials")).items).toHaveLength(1);const usages=(await command(a,"get",root+`/material-versions/${file.id}/usages`)).items;expect(usages.some((u:any)=>u.kind==="progress"&&u.taskId===task.id)).toBe(true);
  await b.goto(`/projects/${project.id}?tab=materials`);const other=await remove(b,root,{materialId:file.materialId,versionId:file.id});expect(other.status()).toBe(403);
  await a.goto(`/projects/${project.id}?tab=materials`);await a.locator(".judex-material-card").getByRole("button",{name:"详情",exact:true}).click();await expect(a.getByRole("dialog")).toContainText("LOCAL_PROGRESS_MATERIAL_EVIDENCE");await expect(a.getByRole("dialog")).toContainText(plan.title);await a.screenshot({path:info.outputPath("actual-purpose-and-history.png")});await a.getByRole("button",{name:"关闭",exact:true}).last().click();await a.locator(".judex-material-card").getByRole("button",{name:"删除",exact:true}).click();await a.getByRole("button",{name:"确认删除",exact:true}).click();await expect(a.locator(".judex-material-card")).toHaveCount(0);
  const content=await a.request.get("/api/v1"+root+`/material-versions/${file.id}/content`);expect(content.ok()).toBe(true);await a.goto(`/projects/${project.id}/tasks/${task.id}/chat/${main.id}`);await expect(a.locator(".judex-material-message-grid").filter({hasText:"acceptance.md"}).first()).toContainText("资料已删除");expect((await command(a,"get",root+`/tasks/${task.id}`)).planId).toBe(plan.id);expect((await command(a,"get",root+`/tasks/${task.id}`)).status).toBe("working");
 }finally{await ca.close();await cb.close();}
});
test("MAT04 native CLI task reports and context registration reuse fixed versions and stable retries",async({browser},info)=>{
 const f=await setupCooperation(browser),{a,ca,cb,root,project,task,plan,identity}=f;try{
  await command(a,"post",root+`/tasks/${task.id}/start`,{expectedVersion:task.version,identityId:identity.id});
  const scopes=["projects:read","context:read","materials:read","materials:write","submissions:write","reports:write"];
  const device=await command(a,"post","/auth/device/authorizations",{deviceName:"material-cli-test",requestedScopes:scopes,projectScope:[project.id]});await command(a,"post","/auth/device/confirm",{userCode:device.userCode,approved:true,scopes,projectScope:[project.id]});const credentials=await command(a,"post","/auth/device/token",{deviceCode:device.deviceCode});
  const config=info.outputPath("cli-context");fs.mkdirSync(config,{recursive:true});const env={...process.env,JUDEX_TOKEN:credentials.accessToken,JUDEX_CONFIG_DIR:config};
  const args=(values:string[])=>["--server",process.env.JUDEX_E2E_BASE_URL!,"--project",project.id,"--json",...values];
  const invoke=(values:string[])=>JSON.parse(execFileSync(process.env.JUDEX_E2E_CLI!,args(values),{encoding:"utf8",env,windowsHide:true,timeout:60000})).data;
  const uploaded=invoke(["material","upload",path.join(fixtures,"acceptance.md"),"--task",task.id,"--purpose","CLI_TASK_FILE_PURPOSE"]);expect(uploaded.registrationStatus).toBe("committed");const repeated=invoke(["material","upload",path.join(fixtures,"acceptance.md"),"--task",task.id,"--purpose","CLI_TASK_FILE_PURPOSE"]);expect(repeated.versionId).toBe(uploaded.versionId);
  const working=await command(a,"get",root+`/tasks/${task.id}`),reportPath=info.outputPath("report.json");fs.writeFileSync(reportPath,JSON.stringify({text:"NATIVE_CLI_PROGRESS_WITH_FILES",identityId:identity.id,expectedTaskVersion:working.version,materialVersionIds:[uploaded.versionId]}));invoke(["report","--task",task.id,"--file",reportPath]);
  const meta=(await command(a,"get",root+`/material-versions/${uploaded.versionId}`)).library;expect(meta.source).toBe("cli");expect(meta.associations).toEqual(expect.arrayContaining([expect.objectContaining({type:"task",id:task.id}),expect.objectContaining({type:"plan",id:plan.id})]));const usages=(await command(a,"get",root+`/material-versions/${uploaded.versionId}/usages`)).items;expect(usages.some((u:any)=>u.kind==="progress"&&u.source==="cli")).toBe(true);
  const failing=["material","upload",path.join(fixtures,"acceptance.json"),"--task","invalid-task-id","--purpose","FAILED_CONTEXT_RETRY"];
  const failed=()=>{try{invoke(failing);throw Error("expected registration failure");}catch(e:any){expect(e.status).not.toBe(0);const output=JSON.parse(e.stdout);expect(output.data.uploadStatus).toBe("ready");expect(output.data.registrationStatus).toBe("failed");return output.data;}};
  const first=failed(),second=failed();expect(first.versionId).toBe(second.versionId);expect((await command(a,"get",root+"/materials")).items).toHaveLength(2);expect((await command(a,"get",root+`/tasks/${task.id}`)).status).toBe("working");
  await info.attach("native-cli-material-proof",{body:JSON.stringify({versionId:uploaded.versionId,taskId:task.id,planId:plan.id,retryVersion:first.versionId,usageKinds:usages.map((u:any)=>u.kind)}),contentType:"application/json"});
 }finally{await ca.close();await cb.close();}
});
test("MAT03 desktop layouts and shared preview remain inside the viewport",async({browser},info)=>{
 const context=await browser.newContext(),page=await context.newPage();try{await registerMember(page,"桌面资料核对");const project=await command(page,"post","/projects",{title:"资料桌面验收"}),root=`/projects/${project.id}`;for(const name of ["acceptance.pdf","acceptance.png","acceptance.json","acceptance.md"])await upload(page,root,name);
  for(const width of [1120,1440,1920,3840])for(const locale of ["zh-CN","en"])for(const theme of ["light","dark"]){await page.setViewportSize({width,height:1000});await page.goto(`/projects/${project.id}?tab=materials`);await page.evaluate(({locale,theme})=>{localStorage.setItem("argus.locale",locale);localStorage.setItem("judex.theme",theme);}, {locale,theme});await page.reload();await expect(page.locator(".judex-material-card")).toHaveCount(4);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator(".judex-material-card .judex-material-cover").first().click();await expect(page.getByRole("dialog")).toBeVisible();await expect(page.locator(".judex-dialog-container[data-entering]")).toHaveCount(0);const box=await page.getByRole("dialog").boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(width);await page.screenshot({path:info.outputPath(`material-${width}-${locale}-${theme}.png`)});await page.getByRole("button",{name:locale==="en"?"Close":"关闭",exact:true}).last().click();}
 }finally{await context.close();}
});
