import {test,expect} from '@playwright/test';
import {seedWork} from '../../web/src/features/work/seed';
import {ensureDemoMainTopics} from '../../web/src/features/chat/demoCollaboration';
import {openChat,demoState} from './cooperation-helpers';
import {openTool,selectPerson} from './workspace-helpers';
test.beforeEach(async({page})=>{const s=ensureDemoMainTopics(seedWork());s.currentUser='林然';const topic=s.topics.find(v=>v.id==='labels')!;for(let i=0;i<30;i++)topic.messages.push({id:'history-'+i,seq:i+3,actor:'林然',kind:'person',text:{zh:'历史消息 '+i+'：保留公开来源和草稿',en:'Public history '+i},at:Date.now()});await page.addInitScript(s=>localStorage.getItem('judex.web.preview.v1')||localStorage.setItem('judex.web.preview.v1',JSON.stringify(s)),s);});
test('conversations retain separate drafts, attachments and nonzero reading positions',async({page})=>{
 await openChat(page);await page.getByTestId('work-discussion-input').fill('首个聊天草稿');await page.getByRole('button',{name:'添加资料',exact:true}).click();await page.getByTestId('work-files').setInputFiles({name:'未发送.md',mimeType:'text/markdown',buffer:Buffer.from('留在此聊天')});
 const top=await page.getByTestId('chat-thread').evaluate(el=>{el.scrollTop=180;el.dispatchEvent(new Event('scroll'));return el.scrollTop;});expect(top).toBeGreaterThan(0);await page.getByTestId('new-discussion').click();await page.getByTestId('discussion-title').fill('第二个聊天');await page.getByTestId('create-discussion').click();await page.getByTestId('work-discussion-input').fill('第二份草稿');await expect(page.locator('.judex-chat-main').getByRole('tab')).toHaveCount(2);
 await page.getByTestId('scoped-topic-labels').click();await expect(page.getByTestId('work-discussion-input')).toHaveValue('首个聊天草稿');await expect(page.getByText('未发送.md',{exact:true})).toBeVisible();await expect.poll(()=>page.getByTestId('chat-thread').evaluate(el=>el.scrollTop)).toBeCloseTo(top,0);await page.getByTestId('scoped-topic-labels').click();await expect(page.locator('.judex-chat-main').getByRole('tab')).toHaveCount(2);await page.getByRole('tab',{name:'第二个聊天',exact:true}).click();await page.reload();await expect(page.getByTestId('work-discussion-input')).toHaveValue('第二份草稿');
});
test('closing a tab preserves neighboring drafts and does not delete business records',async({page})=>{
 await openChat(page);const before=await demoState(page);await page.getByTestId('new-discussion').click();await page.getByTestId('discussion-title').fill('临时协商');await page.getByTestId('create-discussion').click();await page.getByTestId('work-discussion-input').fill('邻居草稿');await page.getByRole('button',{name:'关闭标签 · 首版需要标签吗？',exact:true}).click();await expect(page.getByTestId('work-discussion-input')).toHaveValue('邻居草稿');const after=await demoState(page);expect(after.tasks).toEqual(before.tasks);expect(after.handoffs).toEqual(before.handoffs);expect(after.topics.find((v:any)=>v.id==='labels')).toEqual(before.topics.find((v:any)=>v.id==='labels'));await page.getByTestId('scoped-topic-labels').click();await expect(page.getByTestId('work-discussion-input')).toBeEnabled();await page.getByTestId('tab-topic:labels').focus();await page.keyboard.press('ArrowLeft');await expect(page.locator('.judex-chat-main [aria-selected=true]')).toHaveCount(1);
});
test('project tabs stay isolated and connection downloads remain reachable',async({page})=>{
 await openChat(page);await page.locator('.judex-co-brand').click();await page.getByTestId('project-enter-wild').click();await page.getByRole('button',{name:'项目讨论记录',exact:true}).click();await page.getByRole('button',{name:'怎样表达自然的松弛感？',exact:true}).click();await expect(page.getByTestId('tab-topic:labels')).toHaveCount(0);await page.locator('.judex-co-brand').click();await page.getByTestId('project-enter-leaf').click();await page.getByTestId('plan-discuss-leaf-first').click();await expect(page.getByRole('tab',{name:'怎样表达自然的松弛感？',exact:true})).toHaveCount(0);await openTool(page,'local');for(const id of ['download-cli-windows','download-cli-macos','download-skills'])await expect(page.getByTestId(id)).toBeVisible();await expect(page.locator('.judex-settings-content')).not.toContainText('尚未接入真实');
});
