import {expect,test} from "@playwright/test";
import {chooseValue,toggleLanguage,toggleTheme} from "./workspace-helpers";
test("collaboration navigation, task activity, human choice, nested fork and fixed source",async({page},info)=>{
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 await page.goto("/?project=leaf&view=topic&item=labels");
 await expect(page.getByTestId("work-discussion-input")).toBeVisible();
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem("judex.web.preview.v1")!);s.currentUser="顾言";s.tasks.find((t:any)=>t.id==="build").status="working";s.topics.find((t:any)=>t.id==="main:leaf-first").messages=[{id:"fixed-origin",seq:1,actor:"林然",kind:"person",text:{zh:"固定来源消息",en:"Fixed source message"},at:1}];localStorage.setItem("judex.web.preview.v1",JSON.stringify(s));});
 await page.goto("/?project=leaf&view=task&item=build&chat=main:leaf-first");
 await page.getByTestId("work-discussion-input").fill("每份会话独立草稿");
 await chooseValue(page,"collaboration-compose-task","build");
 await page.reload();
 await expect(page.getByTestId("work-discussion-input")).toHaveValue("每份会话独立草稿");
 await expect(page.getByTestId("collaboration-compose-task")).toHaveAttribute("data-value","build");
 const before=await page.evaluate(()=>JSON.parse(localStorage.getItem("judex.web.preview.v1")!).topics.length);
 await page.locator(".judex-collab-search input").fill("无匹配");
 await expect(page.getByTestId("work-discussion-input")).toHaveValue("每份会话独立草稿");
 await page.locator(".judex-collab-search input").fill("");
 const inspector=page.locator(".judex-collab-inspector");
 await inspector.getByRole("button",{name:"上报进展",exact:true}).click();
 await page.getByTestId("collaboration-report-body").fill("普通进展保留在任务记录");
 await page.getByTestId("collaboration-submit-record").click();await expect(page.getByRole("dialog")).toHaveCount(0);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("judex.web.preview.v1")!).topics.length)).toBe(before);
 await inspector.getByRole("button",{name:"上报进展",exact:true}).click();
 await chooseValue(page,"collaboration-input-kind","question");
 await page.getByTestId("collaboration-report-body").fill("多方核对持续问题");
 await page.getByTestId("collaboration-submit-record").click();await expect(page.getByRole("dialog")).toHaveCount(0);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("judex.web.preview.v1")!).topics.length)).toBe(before);
 await page.getByRole("button",{name:"单独讨论",exact:true}).click();
 await page.getByTestId("collaboration-resolve-suggestion").click();await expect(page.getByRole("dialog")).toHaveCount(0);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("judex.web.preview.v1")!).topics.length)).toBe(before+1);
 await expect(page.getByTestId("chat-thread")).toContainText("固定来源消息");
 await page.getByRole("button",{name:"从此处分叉 · 1",exact:true}).click();await page.getByRole("menuitem",{name:"从此处分叉",exact:true}).click();
 await page.getByTestId("collaboration-create-fork").click();await expect(page.getByRole("dialog")).toHaveCount(0);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("judex.web.preview.v1")!).topics.length)).toBe(before+2);
 await expect(page.getByTestId("chat-thread")).toContainText("共享历史");
 await page.locator(".judex-collab-lineage").getByRole("button").click();
 await expect(page.locator('.judex-collab-message-focus[data-message-seq="1"]')).toBeVisible();
 await inspector.getByRole("button",{name:"流程参考",exact:true}).click();await expect(inspector).toContainText("从想法到交付");
 await toggleTheme(page);await toggleLanguage(page);await page.setViewportSize({width:1120,height:900});
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:info.outputPath("collaboration-dark-en.png"),fullPage:true});
 expect(errors).toEqual([]);
});
