import {seedWork} from '../../web/src/features/work/seed';
import {ensureDemoMainTopics} from '../../web/src/features/chat/demoCollaboration';
import {words,type Task} from '../../web/src/features/work/types';
export function demo4Fixture(){
 const s=ensureDemoMainTopics(seedWork()),plan=s.plans.find(v=>v.id==='leaf-first')!,base=s.tasks.find(v=>v.id==='build')!;
 s.currentUser='林然';plan.title=words('首版桌面协同体验','First desktop collaboration release');plan.goal=words('让计划、任务与讨论之间的切换清晰自然。','Make moving between plans, tasks, and discussions clear and natural.');plan.criteria=[words('核心协作链路可以从创建到验收完整走通','Complete the core collaboration journey from creation to acceptance'),words('中英文、深浅色下保持一致的桌面体验','Consistent desktop experience in both languages and themes')];plan.status='active';plan.revision=3;plan.createdBy='林然';plan.referenceTaskIds=[];
 const node=(id:string,title:string,en:string,description:string,english:string,status:Task['status'],before:string[],person='顾言'):Task=>({...structuredClone(base),id,planId:plan.id,title:words(title,en),expected:words(description,english),status,businessStatus:status,revision:1,createdBy:'林然',seatIds:[s.seats.find(v=>v.person===person&&s.positions.some(p=>p.id===v.positionId&&p.projectId==='leaf'))?.id??base.seatIds[0]],criteria:[words('成果清晰可核对，相关问题已有明确处理','Output is reviewable and related issues are explicitly addressed')],requirements:before.map((ref,i)=>({id:id+'-req-'+i,kind:'task',ref,hard:true,at:'start',label:words(ref,ref)})),files:[],mainTopicId:undefined,parentId:undefined});
 const tasks=[node('demo4-needs','需求确认','Confirm requirements','整理用户反馈，明确本轮范围、交付内容与验收标准。','Review user feedback and agree on scope, outputs, and acceptance criteria.','accepted',[],'林然'),node('demo4-review','交互评审','Review interactions','评审任务详情、讨论侧栏和路线查看，收敛关键交互。','Review task details, discussion panels, and route exploration.','working',['demo4-needs']),node('build','功能开发','Implement features','完成任务生命周期与共用详情面板，接入正式业务接口。','Implement task lifecycle and shared detail panels using formal APIs.','ready',['demo4-review']),node('demo4-contract','数据契约核对','Check data contracts','对照页面需要的信息，核对状态、权限和依赖的数据契约。','Check state, permission, and dependency contracts against UI needs.','ready',['demo4-review'],'林然'),node('demo4-acceptance','联调与验收','Integration and acceptance','验证完整协作链路，检查中英文、深浅色和关键异常路径。','Verify the collaboration journey, both themes and languages, and exception paths.','ready',['build','demo4-contract'],'林然'),node('demo4-draft','补充性能检查','Additional performance checks','检查大计划路线、长记录与多标签切换，明确性能目标。','Check large routes, long histories, and tab switching against performance goals.','draft',['build'])];
 s.tasks=[...s.tasks.filter(v=>v.planId!==plan.id),...tasks];s.handoffs=s.handoffs.filter(h=>!h.sources.some(v=>tasks.some(t=>t.id===v.taskId)));
 s.taskActivities=[{id:'demo4-record',taskId:'demo4-review',kind:'progress',sourceType:'report',source:'cli',text:'任务卡片与详情抽屉方案已整理，正在核对跳过后的后继条件。\n原始报告：保留当前任务范围，按职责确认正式变更。',actorUserId:null,actorName:'顾言',identityId:tasks[1].seatIds[0],createdAt:'2026-10-08T14:20:00+08:00',materialVersionIds:[],materials:[],topicIds:[],analysis:null}];
 return ensureDemoMainTopics(s);
}
