import {test,expect,type Page} from '@playwright/test';
import fs from 'node:fs';
import {demo4Fixture} from './demo4-fixture';
import {chooseValue} from './workspace-helpers';
const before=process.env.JUDEX_DEMO4_BASELINE==='1',dir='.cache/demo4-implementation/visual/'+(before?'before':'after');
fs.mkdirSync(dir,{recursive:true});
test.beforeEach(async({page})=>{await page.addInitScript(s=>{if(!localStorage.getItem('judex.web.preview.v1'))localStorage.setItem('judex.web.preview.v1',JSON.stringify(s));},demo4Fixture());});
for(const width of [1120,1440,1920])for(const locale of ['zh-CN','en'])for(const theme of ['light','dark'])test(`compare task surfaces ${width} ${locale} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:1000});const suffix=width+'-'+locale+'-'+theme;
 await page.addInitScript(({locale,theme})=>{localStorage.setItem('argus.locale',locale);localStorage.setItem('judex.theme',theme);},{locale,theme});
 await page.goto('/');await expect(page.getByTestId('project-enter-leaf')).toBeVisible();await page.screenshot({path:dir+'/projects-'+suffix+'.png',fullPage:true,animations:'disabled'});await page.getByTestId('project-enter-leaf').click();await page.screenshot({path:dir+'/plans-'+suffix+'.png',fullPage:true,animations:'disabled'});
 await page.goto('/projects/leaf/plans/leaf-first/route');await expect(page.getByTestId('execution-task-demo4-review')).toBeVisible();await page.screenshot({path:dir+'/route-'+suffix+'.png',fullPage:true,animations:'disabled'});
 await page.getByTestId('execution-task-demo4-review').locator('.judex-co-card-hit').click();await page.screenshot({path:dir+'/drawer-'+suffix+'.png',fullPage:true,animations:'disabled'});if(!before){await expect(page.getByTestId('task-details-drawer')).toBeVisible();const drawer=await page.getByTestId('task-details-drawer').boundingBox();expect(drawer!.width).toBeLessThanOrEqual(440);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('tab',{name:locale==='en'?'Workflow reference':'流程参考',exact:true}).click();await page.screenshot({path:dir+'/flow-'+suffix+'.png',fullPage:true,animations:'disabled'});await page.getByRole('button',{name:locale==='en'?'View fullscreen':'全屏查看',exact:true}).click();await expect(page.getByTestId('route-fullscreen')).toBeVisible();await page.screenshot({path:dir+'/fullscreen-'+suffix+'.png',fullPage:true,animations:'disabled'});await page.getByTestId('exit-route-fullscreen').click();await page.getByTestId('task-more-demo4-draft').click();await page.getByRole('menuitem',{name:locale==='en'?'Edit draft task':'编辑草稿任务',exact:true}).click();await page.screenshot({path:dir+'/form-'+suffix+'.png',fullPage:true,animations:'disabled'});await page.keyboard.press('Escape');}
 await page.goto('/projects/leaf/plans/leaf-first/chat/main%3Aleaf-first');await expect(page.getByTestId('work-discussion-input')).toBeVisible();await page.screenshot({path:dir+'/plan-context-'+suffix+'.png',fullPage:true,animations:'disabled'});
 if(!before){await page.locator('.judex-co-context-task').filter({hasText:locale==='en'?'Review interactions':'交互评审'}).click();await page.getByTestId('workspace-add-tool').click();await page.getByRole('menuitem',{name:locale==='en'?'Task records':'任务记录',exact:true}).click();await expect(page.getByTestId('task-section-records')).toBeVisible();await page.screenshot({path:dir+'/records-'+suffix+'.png',fullPage:true,animations:'disabled'});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
});
test('formal component tree supports draft editing and administrator exception review',async({page})=>{
 test.skip(before);await page.goto('/projects/leaf/plans/leaf-first/route');await page.getByTestId('task-more-demo4-draft').click();await page.getByRole('menuitem',{name:'编辑草稿任务',exact:true}).click();await page.getByTestId('edit-work-title').fill('长记录性能检查');await page.getByTestId('save-work-edit').click();await expect(page.getByTestId('execution-task-demo4-draft')).toContainText('长记录性能检查');
 await page.getByTestId('task-more-demo4-review').click();await page.getByRole('menuitem',{name:'临时跳过',exact:true}).click();await page.getByTestId('execution-exception-reason').fill('已完成充分评审，继续下一环节');await page.getByTestId('exception-waiver-build').click();await page.getByTestId('exception-waiver-demo4-contract').click();await page.getByTestId('confirm-work-mutation').click();await expect(page.getByTestId('execution-task-demo4-review')).toHaveAttribute('data-stage','skipped');await expect(page.getByTestId('execution-task-build')).toHaveAttribute('data-stage','ready');await page.screenshot({path:dir+'/skipped.png',fullPage:true,animations:'disabled'});
});
test('fullscreen preserves original view and discussion tools keep the conversation draft',async({page})=>{
 test.skip(before);await page.goto('/projects/leaf/plans/leaf-first/route');await page.getByTestId('execution-task-demo4-review').locator('.judex-co-card-hit').click();await page.getByRole('button',{name:'缩小',exact:true}).click();await page.getByRole('button',{name:'全屏查看',exact:true}).click();await expect(page.getByTestId('route-fullscreen')).toBeVisible();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(true);await page.getByRole('button',{name:'适应画布',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByTestId('route-fullscreen')).toHaveCount(0);await expect(page.getByTestId('task-details-drawer')).toBeVisible();await expect(page.locator('.judex-execution-toolbar small')).toHaveText('90%');
 await page.getByTestId('task-discuss-demo4-review').click();await page.getByTestId('work-discussion-input').fill('保留当前讨论草稿');for(const label of ['任务记录','流程参考','流程参考']){await page.getByTestId('workspace-add-tool').click();await page.getByRole('menuitem',{name:label,exact:true}).click();}await expect(page.getByTestId('workspace-tab-task:demo4-review:flow')).toHaveCount(1);await expect(page.getByTestId('work-discussion-input')).toHaveValue('保留当前讨论草稿');
});
test('fullscreen fallback restores source filter and record position; confirmation closes independently',async({page})=>{
 test.skip(before);await page.addInitScript(()=>{Object.defineProperty(document,'fullscreenEnabled',{configurable:true,get:()=>false});});await page.goto('/projects/leaf/plans/leaf-first/route?task=demo4-review&section=records&activity=demo4-record');await expect(page.getByTestId('task-section-records')).toBeVisible();await expect(page.locator('.judex-task-original')).toContainText('原始报告');await chooseValue(page,'task-record-source','cli');await page.getByRole('button',{name:'全屏查看',exact:true}).click();await expect(page.getByTestId('route-fullscreen')).toBeVisible();expect(await page.evaluate(()=>document.fullscreenElement)).toBeNull();await expect(page.getByTestId('task-record-source')).toHaveAttribute('data-value','cli');await chooseValue(page,'task-record-source','web');await page.getByTestId('task-inspector').getByTestId('task-more-demo4-review').click();await page.getByRole('menuitem',{name:'临时跳过',exact:true}).click();await expect(page.locator('.judex-dialog-content')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.judex-dialog-content')).toHaveCount(0);await expect(page.getByTestId('route-fullscreen')).toBeVisible();await page.getByTestId('exit-route-fullscreen').click();await expect(page.getByTestId('task-record-source')).toHaveAttribute('data-value','cli');await expect(page.locator('.judex-task-original')).toContainText('原始报告');
});
test('fullscreen restores a nonzero record reading position with the source selected',async({page})=>{
 test.skip(before);await page.goto('/projects/leaf/plans/leaf-first/route?task=demo4-review&section=records&activity=demo4-record');await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('judex.web.preview.v1')!),row=s.taskActivities[0];s.taskActivities.push(...Array.from({length:40},(_,i)=>({...row,id:'record-'+i,text:'详细说明、固定来源与核对内容。'.repeat(15),createdAt:new Date(Date.UTC(2026,9,8,8,i)).toISOString()})));localStorage.setItem('judex.web.preview.v1',JSON.stringify(s));});await page.reload();await expect(page.locator('[data-activity]')).toHaveCount(41);const scroller=page.locator('.judex-task-scroll');await scroller.evaluate(el=>{el.scrollTop=200;el.dispatchEvent(new Event('scroll'));});await expect.poll(()=>scroller.evaluate(el=>el.scrollTop)).toBe(200);await page.getByRole('button',{name:'全屏查看',exact:true}).click();await expect(page.getByTestId('route-fullscreen')).toBeVisible();await scroller.evaluate(el=>{el.scrollTop=0;el.dispatchEvent(new Event('scroll'));});await page.getByTestId('exit-route-fullscreen').click();await expect.poll(()=>scroller.evaluate(el=>el.scrollTop)).toBe(200);await expect(page.locator('[data-activity="demo4-record"] .judex-task-original')).toContainText('原始报告');
});
test('selected task section stays visible in the tool tab strip',async({page})=>{
 test.skip(before);await page.goto('/projects/leaf/plans/leaf-first/chat/main%3Aleaf-first');await page.locator('.judex-co-context-task').filter({hasText:'交互评审'}).click();await page.getByTestId('workspace-add-tool').click();await page.getByRole('menuitem',{name:'任务记录',exact:true}).click();await expect(page.getByTestId('task-section-records')).toBeVisible();const metrics=await page.getByTestId('workspace-tab-task:demo4-review:records').evaluate(el=>{const list=el.closest('[role="tablist"]')!,a=el.getBoundingClientRect(),b=list.getBoundingClientRect();return {selected:el.getAttribute('aria-selected'),tabLeft:a.left,tabRight:a.right,listLeft:b.left,listRight:b.right,scroll:list.scrollLeft};});expect(metrics.selected).toBe('true');expect(metrics.tabLeft).toBeGreaterThanOrEqual(metrics.listLeft-1);expect(metrics.tabRight).toBeLessThanOrEqual(metrics.listRight+1);
});
