import {test,expect} from '@playwright/test';
import {openChat} from './cooperation-helpers';
import {openTool,toggleTheme,toggleLanguage} from './workspace-helpers';
test('workspace context tabs preserve reading position and central chat',async({page})=>{
 await openChat(page,'main:leaf-first','leaf','leaf-first');await page.getByTestId('work-discussion-input').fill('中央草稿不受影响');await openTool(page,'plans');await page.setViewportSize({width:1440,height:550});const body=page.locator('.judex-chat-panel-body');const top=await body.evaluate(el=>{el.scrollTop=80;el.dispatchEvent(new Event('scroll'));return el.scrollTop;});expect(top).toBeGreaterThan(0);await openTool(page,'resources');await page.getByTestId('workspace-tab-plan:leaf-first').click();await expect.poll(()=>body.evaluate(el=>el.scrollTop)).toBeCloseTo(top,0);await expect(page.getByTestId('work-discussion-input')).toHaveValue('中央草稿不受影响');await page.reload();await expect(page.getByTestId('work-discussion-input')).toHaveValue('中央草稿不受影响');await page.getByRole('button',{name:'关闭功能标签 · 共享资料',exact:true}).click();await page.getByRole('button',{name:'关闭功能标签 · 把轻笺的第一版交到大家手里',exact:true}).click();await expect(page.getByTestId('workspace-launcher')).toBeVisible();
});
test('task details have compact independent tabs and project switching isolates the inspector',async({page})=>{
 await openChat(page,'main:leaf-first','leaf','leaf-first');await page.locator('.judex-co-context-task').filter({hasText:'让任务创建和列表顺畅可用'}).click();await expect(page.getByTestId('workspace-tab-task:build:overview')).toBeVisible();await page.getByTestId('workspace-tab-plan:leaf-first').click();for(const tab of await page.getByRole('tab').all()){const box=(await tab.boundingBox())!;expect(box.width).toBeLessThanOrEqual(231);expect(box.height).toBeLessThanOrEqual(42);expect(await tab.evaluate(el=>getComputedStyle(el).backgroundColor)).not.toBe('rgba(0, 0, 0, 0)');}await page.locator('.judex-co-brand').click();await page.getByTestId('project-enter-wild').click();await page.getByRole('button',{name:'项目讨论记录',exact:true}).click();await expect(page.getByTestId('workspace-tab-task:build:overview')).toHaveCount(0);await toggleTheme(page);await toggleLanguage(page);await page.setViewportSize({width:1120,height:900});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
