import {Input} from "@heroui/react";
import {Plus,Search,MessageCircle,ArrowUpRight} from "lucide-react";
import {Button} from "../../components/ui/Button";
import {EmptyState} from "../../components/ui/Presentation";
import {UIWarning} from "../../components/ui/FormControls";
import {usePreferences} from "../../stores/preferences";
import {translate} from "../../i18n";
import {ProjectCards,type ProjectCardData} from "./ProjectCards";
type Recent={projectId:string;topicId:string;title:string;projectTitle:string;lastActivityAt:string};
export function ProjectListPage({items,recent=[],pending,error,recentPending,recentError,onRetry,onRecentRetry,search,setSearch,ownership,setOwnership,onEnter,onInvite,onSettings,onCreate,more}:{items:ProjectCardData[];recent?:Recent[];pending?:boolean;error?:string;recentPending?:boolean;recentError?:string;onRetry?:()=>void;onRecentRetry?:()=>void;search:string;setSearch:(v:string)=>void;ownership:string;setOwnership:(v:"all"|"owned"|"joined")=>void;onEnter:(id:string,topic?:string)=>void;onInvite:(id:string)=>void;onSettings:(id:string)=>void;onCreate:()=>void;more?:React.ReactNode}){
 const {locale}=usePreferences(),t=(key:Parameters<typeof translate>[1])=>translate(locale,key);
 return <div className="judex-co-scroll"><main className="judex-co-main"><div className="judex-co-page-heading"><div><div><h1>{t("portalProjects")}</h1><p>{t("portalProjectHint")}</p></div><Button variant="primary" data-testid="workspace-new-project" onPress={onCreate}><Plus/>{t("workspaceNewProject")}</Button></div></div><div className="judex-co-toolbar"><div className="judex-co-actions">{(["all","owned","joined"] as const).map(v=><Button size="sm" variant="ghost" key={v} aria-pressed={ownership===v} onPress={()=>setOwnership(v)}>{t(v==="all"?"portalAll":v==="owned"?"portalOwned":"portalJoined")}</Button>)}</div><div className="judex-co-search"><Search/><Input aria-label={t("portalSearch")} placeholder={t("portalSearch")} value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
 {pending?<p role="status">{t("shellLoading")}</p>:error?<UIWarning>{error}<Button onPress={onRetry}>{t("shellRetry")}</Button></UIWarning>:<><ProjectCards items={items} onEnter={onEnter} onInvite={onInvite} onSettings={onSettings}/>{!items.length&&<EmptyState title={t(search||ownership!=="all"?"portalNoResults":"workspaceEmpty")} description={t(search||ownership!=="all"?"portalNoResultsHint":"workspaceEmptyHint")}/>} {more}</>}
 <section className="judex-project-recent"><div className="judex-section-heading"><h2>{t("portalRecent")}</h2></div>{recentPending?<p role="status">{t("shellLoading")}</p>:recentError?<UIWarning>{recentError}<Button onPress={onRecentRetry}>{t("shellRetry")}</Button></UIWarning>:recent.length?<div className="judex-recent-list">{recent.map(v=><Button variant="ghost" className="judex-recent-row" key={v.topicId} onPress={()=>onEnter(v.projectId,v.topicId)}><MessageCircle/><span><strong>{v.title}</strong><small>{v.projectTitle}</small></span><time>{new Date(v.lastActivityAt).toLocaleString(locale,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</time><ArrowUpRight/></Button>)}</div>:<p className="judex-co-meta">{t("portalNoRecent")}</p>}</section><footer className="judex-co-secondary">{t("portalAIHint")}</footer></main></div>;
}
