import {test,expect,type Page} from '@playwright/test';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
const state=(page:Page)=>page.evaluate(()=>JSON.parse(localStorage.getItem('judex.demo4.v1')??'null'));
async function menu(page:Page,id:string,label:string){await page.getByTestId('d4-task-menu-'+id).first().click();await page.getByRole('menuitem',{name:label,exact:true}).click();}
async function skip(page:Page,id='review',waive=true){await menu(page,id,'临时跳过');await page.getByTestId('d4-skip-reason').fill('本轮已有明确方案，先继续后续核对');if(waive&&id==='review')await page.getByTestId('d4-waive-build-review').click();await page.getByTestId('d4-confirm-skip').click();}
test.beforeEach(async({page})=>{await page.goto('/demo4.html#route/launch');});
test('task cards contain summaries and open a drawer with separate record and workflow sections',async({page})=>{
 await expect(page.getByTestId('d4-task-review')).toContainText('评审任务详情、讨论侧栏和路线查看');await page.getByRole('button',{name:'查看任务 · 交互评审',exact:true}).click();await expect(page.getByTestId('d4-drawer')).toBeVisible();await expect(page.locator('.judex-dialog-content')).toHaveCount(0);
 await page.getByRole('tab',{name:'任务记录',exact:true}).click();await expect(page.getByTestId('d4-section-records')).toContainText('本地 CLI 上报');await page.getByRole('button',{name:'展开原始报告',exact:true}).first().click();await expect(page.getByTestId('d4-section-records')).toContainText('待确认：跳过任务时');await page.getByRole('tab',{name:'流程参考',exact:true}).click();await expect(page.getByTestId('d4-section-flow')).toContainText('已发布 · v3');await expect(page.getByTestId('d4-drawer').getByRole('combobox')).toHaveCount(0);
});
test('draft editing preserves data and withdraws the old review',async({page})=>{
 await menu(page,'draft-check','编辑草稿任务');await expect(page.locator('.judex-dialog-content')).toContainText('旧审阅版本会撤回');await page.getByTestId('d4-edit-title').fill('补充长记录性能检查');await page.getByTestId('d4-edit-description').fill('核对一百条记录和标签切换，给出明确响应目标。');await page.getByTestId('d4-save-edit').click();await expect(page.getByTestId('d4-task-draft-check')).toContainText('核对一百条记录');const s=await state(page);expect(s.tasks.find((t:any)=>t.id==='draft-check').pending).toBe(false);expect(s.tasks.find((t:any)=>t.id==='draft-check').version).toBe(2);
});
test('create and delete an owned draft without deleting existing records',async({page})=>{
 const before=await state(page);await page.getByTestId('d4-new-task').click();await page.getByTestId('d4-edit-title').fill('可删除的草稿');await page.getByTestId('d4-edit-description').fill('整理一组独立的检查示例。');await page.getByTestId('d4-edit-criteria').fill('检查结果可以复现');await page.getByTestId('d4-save-edit').click();const created=(await state(page)).tasks.find((t:any)=>t.title.zh==='可删除的草稿');await page.getByTestId('d4-close-drawer').click();await menu(page,created.id,'删除草稿任务');await page.getByTestId('d4-confirm-delete').click();const after=await state(page);expect(after.tasks.length).toBe(before.tasks.length);expect(after.records).toEqual(before.records);
});
test('draft plan deletion explicitly includes its own drafts',async({page})=>{
 await page.goto('/demo4.html#route/quality');await page.getByTestId('d4-plan-menu-quality').click();await page.getByRole('menuitem',{name:'删除草稿计划',exact:true}).click();await expect(page.locator('.judex-dialog-content')).toContainText('2 项草稿任务');await page.getByTestId('d4-confirm-delete').click();const s=await state(page);expect(s.plans.some((v:any)=>v.id==='quality')).toBe(false);expect(s.tasks.filter((v:any)=>v.planId==='quality')).toHaveLength(0);expect(s.records).toHaveLength(3);await expect(page.getByTestId('d4-plan-launch')).toBeVisible();
});
test('skipping bypasses order while retaining an unwaived acceptance requirement',async({page})=>{
 await skip(page,'review',false);await expect(page.getByTestId('d4-task-review')).toHaveAttribute('data-stage','skipped');await expect(page.getByTestId('d4-task-build')).toHaveAttribute('data-stage','blocked');await expect(page.getByTestId('d4-task-contract')).toHaveAttribute('data-stage','ready');await expect(page.locator('path[data-from="needs"][data-to="build"][data-original="false"]')).toHaveCount(1);const s=await state(page);expect(s.tasks.find((t:any)=>t.id==='review').status).toBe('working');expect(s.records).toHaveLength(4);
});
test('explicit waiver unlocks a successor without starting it or accepting the skipped task',async({page})=>{
 await skip(page);await expect(page.getByTestId('d4-task-build')).toHaveAttribute('data-stage','ready');await expect(page.getByTestId('d4-task-acceptance')).toHaveAttribute('data-stage','blocked');const s=await state(page);expect(s.tasks.filter((t:any)=>t.status==='accepted')).toHaveLength(1);expect(s.tasks.find((t:any)=>t.id==='build').status).toBe('ready');await page.getByRole('button',{name:'查看任务 · 交互评审',exact:true}).click();await page.getByRole('tab',{name:'任务记录',exact:true}).click();await expect(page.getByTestId('d4-section-records')).toContainText('管理员临时跳过');
});
test('multiple predecessors and consecutive skips retain other dependencies',async({page})=>{
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('judex.demo4.v1')!);s.tasks.find((t:any)=>t.id==='build').before.push('contract');localStorage.setItem('judex.demo4.v1',JSON.stringify(s));});await page.reload();await skip(page);await expect(page.getByTestId('d4-task-build')).toHaveAttribute('data-stage','blocked');await skip(page,'contract',false);await expect(page.getByTestId('d4-task-build')).toHaveAttribute('data-stage','ready');const s=await state(page);expect(s.tasks.filter((t:any)=>t.skip)).toHaveLength(2);expect(s.tasks.filter((t:any)=>t.status==='accepted')).toHaveLength(1);
});
test('restoring a skipped task reviews started successors and preserves their stage',async({page})=>{
 await skip(page);await page.getByRole('button',{name:'查看任务 · 数据契约核对',exact:true}).click();await page.getByTestId('d4-drawer').getByRole('button',{name:'开始任务',exact:true}).click();await page.getByTestId('d4-close-drawer').click();await menu(page,'review','恢复执行');await page.getByTestId('d4-skip-reason').fill('补充条件需要重新核对');await expect(page.getByTestId('d4-confirm-skip')).toBeDisabled();await expect(page.locator('.judex-dialog-content')).toContainText('数据契约核对');await page.getByTestId('d4-restore-ack').click();await page.getByTestId('d4-confirm-skip').click();const s=await state(page);expect(s.tasks.find((t:any)=>t.id==='review').skip).toBeUndefined();expect(s.tasks.find((t:any)=>t.id==='contract').status).toBe('working');await expect(page.getByTestId('d4-task-build')).toHaveAttribute('data-stage','blocked');
});
test('member permissions hide administrator skip actions',async({page})=>{
 await page.getByTestId('d4-account').click();await page.getByRole('menuitem',{name:'体验成员权限',exact:true}).click();await page.getByTestId('d4-task-menu-review').click();await expect(page.getByRole('menuitem',{name:'临时跳过',exact:true})).toHaveCount(0);await expect(page.getByRole('menuitem',{name:'修改任务安排',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');await menu(page,'draft-check','编辑草稿任务');await expect(page.locator('.judex-dialog-content')).toBeVisible();
});
test('active arrangement edits require explicit confirmation',async({page})=>{
 await menu(page,'review','修改任务安排');await page.getByTestId('d4-edit-title').fill('交互与边界评审');await page.getByTestId('d4-save-edit').click();let s=await state(page);expect(s.tasks.find((t:any)=>t.id==='review').title.zh).toBe('交互评审');expect(s.changes).toHaveLength(1);await menu(page,'review','查看修改');await expect(page.locator('.judex-dialog-content')).toContainText('当前正式内容');await page.getByTestId('d4-confirm-change').click();s=await state(page);expect(s.tasks.find((t:any)=>t.id==='review').title.zh).toBe('交互与边界评审');expect(s.changes).toHaveLength(0);
});
test('true fullscreen retains zoom and list preview retains filters',async({page})=>{
 await page.getByRole("button",{name:"查看任务 · 交互评审",exact:true}).click();await page.getByRole("button",{name:"缩小",exact:true}).click();await page.getByTestId("d4-fullscreen").click();await expect(page.getByTestId('d4-fullscreen-view')).toBeVisible();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(true);await expect(page.locator('.judex-dialog-content')).toHaveCount(0);await page.getByRole("button",{name:"适应画布",exact:true}).click();await page.keyboard.press("Escape");await expect(page.locator(".judex-d4-zoom")).toHaveText("90%");await expect(page.getByTestId("d4-drawer")).toContainText("交互评审");await page.goto('/demo4.html#plans/product');await page.getByRole('textbox',{name:'搜索计划…',exact:true}).fill('首版');await page.getByTestId('d4-preview-launch').click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(true);await page.getByTestId('d4-exit-fullscreen').click();await expect(page.getByRole('textbox',{name:'搜索计划…',exact:true})).toHaveValue('首版');await expect(page.getByTestId('d4-plan-quality')).toHaveCount(0);
});
test('discussion plus opens task records and workflow reference once without nested tabs',async({page})=>{
 await page.goto('/demo4.html#chat/launch/review');await page.getByTestId('d4-add-panel').click();await page.getByRole('menuitem',{name:'任务记录',exact:true}).click();await expect(page.getByTestId('d4-section-records')).toBeVisible();await page.getByTestId('d4-add-panel').click();await page.getByRole('menuitem',{name:'流程参考',exact:true}).click();await expect(page.getByTestId('d4-section-flow')).toBeVisible();await page.getByTestId('d4-add-panel').click();await page.getByRole('menuitem',{name:'流程参考',exact:true}).click();await expect(page.getByTestId('d4-tool-flow-review')).toHaveCount(1);await expect(page.getByTestId('d4-workspace').getByRole('tablist')).toHaveCount(1);
});
test('discussion draft and selected tool survive expansion and a fullscreen route visit',async({page})=>{
 await page.goto('/demo4.html#chat/launch/review');await page.getByTestId('d4-chat-input').fill('保留这段讨论草稿');await page.getByTestId('d4-expand-panel').click();await expect(page.locator('.judex-d4-conversation')).toBeHidden();await page.getByTestId('d4-expand-panel').click();await expect(page.getByTestId('d4-chat-input')).toHaveValue('保留这段讨论草稿');await page.getByTestId('d4-add-panel').click();await page.getByRole('menuitem',{name:'流程参考',exact:true}).click();await page.getByRole('button',{name:'在计划路线中定位',exact:true}).click();await page.getByTestId('d4-exit-fullscreen').click();await expect(page.getByTestId('d4-chat-input')).toHaveValue('保留这段讨论草稿');await expect(page.getByTestId('d4-section-flow')).toBeVisible();
});
test('project, plan, and route headers share their desktop content container',async({page})=>{
 await page.setViewportSize({width:1920,height:1080});const boxes=[];for(const hash of ['projects','plans/product','route/launch']){await page.goto('/demo4.html#'+hash);boxes.push(await page.locator('.judex-d4-main').boundingBox());}expect(boxes[0]!.x).toBeCloseTo(boxes[1]!.x,0);expect(boxes[1]!.x).toBeCloseTo(boxes[2]!.x,0);expect(boxes[0]!.width).toBeCloseTo(boxes[2]!.width,0);
});
test('standalone file opens offline and requires no external resources',async({page})=>{
 const external:string[]=[];page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});await page.goto(pathToFileURL(resolve('demo4.html')).href+'#route/launch');await page.getByRole('button',{name:'查看任务 · 交互评审',exact:true}).click();await expect(page.getByTestId('d4-drawer')).toBeVisible();await page.getByRole('tab',{name:'流程参考',exact:true}).click();await expect(page.getByTestId('d4-section-flow')).toContainText('已发布 · v3');expect(external).toEqual([]);
});
test('draft deletion prevents removing a task referenced by another task',async({page})=>{
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('judex.demo4.v1')!);s.tasks.find((t:any)=>t.id==='contract').before.push('draft-check');localStorage.setItem('judex.demo4.v1',JSON.stringify(s));});await page.reload();await menu(page,'draft-check','删除草稿任务');await expect(page.getByTestId('d4-confirm-delete')).toBeDisabled();await expect(page.locator('.judex-dialog-content')).toContainText('其他任务引用');
});
for(const width of [1120,1440,1920])for(const locale of ['zh-CN','en'])for(const theme of ['light','dark'])test(`desktop layout ${width} ${locale} ${theme}`,async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(({locale,theme})=>{localStorage.setItem('argus.locale',locale);localStorage.setItem('judex.theme',theme);},{locale,theme});await page.setViewportSize({width,height:1000});await page.goto('/demo4.html#route/launch');await page.reload();await page.getByRole('button',{name:locale==='en'?'View task · Review interactions':'查看任务 · 交互评审',exact:true}).click();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width===1440)await page.screenshot({path:info.outputPath('route-drawer.png'),fullPage:true});await page.goto('/demo4.html#chat/launch/review');await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width===1440)await page.screenshot({path:info.outputPath('discussion.png'),fullPage:true});expect(errors).toEqual([]);
});
