import {Tabs} from '@heroui/react';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowUp,ChevronRight,FileText,Files,GitBranch,Maximize2,MessageCircle,Minimize2,Plus,X} from 'lucide-react';
import {UITextArea,UIDisclosure} from '../src/components/ui/FormControls';
import {usePreview} from './context';
import {people,stats,taskStage,tx,type Plan,type Section,type Task,type Text} from './model';
import {Button,Menu,Person,PersonAvatar,Status} from './ui';
import {TaskActions,TaskHeader,TaskSection} from './task';
type Tool={key:string;kind:Section|'plan'|'materials';taskId?:string};
type Message={id:string;author:string;text:Text|string;time:string};
const toolLabels={overview:'d4Summary',records:'d4Records',flow:'d4Flow',plan:'d4PlanInfo',materials:'d4Materials'} as const;
const toolIcons={overview:FileText,records:FileText,flow:GitBranch,plan:GitBranch,materials:Files};
function read<T,>(key:string,fallback:T):T{try{return JSON.parse(sessionStorage.getItem('judex.demo4.'+key)??'null')??fallback;}catch{return fallback;}}
function write(key:string,value:unknown){try{sessionStorage.setItem('judex.demo4.'+key,JSON.stringify(value));}catch{}}
export function ChatView(){
 const p=usePreview(),plan=p.state.plans.find(v=>v.id===p.page.planId),task=p.state.tasks.find(t=>t.id===p.page.taskId);if(!plan)return null;
 return <Discussion key={plan.id+':'+(task?.id??'plan')} plan={plan} task={task}/>;
}
function Discussion({plan,task}:{plan:Plan;task?:Task}){
 const p=usePreview(),scope=plan.id+':'+(task?.id??'plan'),initial:Tool={key:task?'overview:'+task.id:'plan:'+plan.id,kind:task?'overview':'plan',taskId:task?.id};
 const [tools,setTools]=useState<Tool[]>(()=>read('tabs.'+scope,[initial])),[active,setActive]=useState(()=>read('active.'+scope,initial.key)),[panel,setPanel]=useState<'normal'|'wide'|'hidden'>('normal'),[draft,setDraft]=useState(()=>read('draft.'+scope,'')),[messages,setMessages]=useState<Message[]>(()=>read('messages.'+scope,[
  {id:'m1',author:'manager',time:'14:05',text:tx(task?'这项任务重点核对详情抽屉与路线查看，说明和完成条件已经放在右侧。':'这一轮先把协作入口理顺，各项任务的安排和进展在右侧查看。',task?'Review the detail drawer and route viewer. The description and completion criteria are in the right panel.':'Clarify collaboration entry points; use the right panel for arrangements and progress.')},
  {id:'m2',author:task?'designer':'member',time:'14:20',text:tx('我已整理任务卡片和记录时间线。需要对照规则时，可以从右上角加号打开流程参考。','Task cards and the record timeline are organized. Open the workflow reference from the plus button to check the rules.')},
  {id:'m3',author:'ai',time:'14:21',text:tx('建议保留当前任务的上下文，把原始报告、AI 分析和正式决定分别呈现。','Keep the current task context clear and present original reports, AI analysis, and formal decisions separately.')},
 ]));
 useEffect(()=>write('tabs.'+scope,tools),[tools,scope]);useEffect(()=>write('active.'+scope,active),[active,scope]);useEffect(()=>write('draft.'+scope,draft),[draft,scope]);useEffect(()=>write('messages.'+scope,messages),[messages,scope]);
 useEffect(()=>{const valid=tools.filter(t=>!t.taskId||p.state.tasks.some(v=>v.id===t.taskId));if(valid.length!==tools.length){setTools(valid);if(!valid.some(t=>t.key===active))setActive(valid[0]?.key??'launcher');}},[p.state.tasks]);
 const open=(kind:Tool['kind'],target?:Task)=>{const tool:Tool={key:kind+':'+(target?.id??plan.id),kind,taskId:target?.id};setTools(old=>old.some(t=>t.key===tool.key)?old:[...old,tool]);setActive(tool.key);setPanel('normal');};
 const current=tools.find(v=>v.key===active),contextTask=task??p.state.tasks.find(t=>t.id===current?.taskId);
 const close=(key:string)=>{const i=tools.findIndex(t=>t.key===key),next=tools.filter(t=>t.key!==key);setTools(next);if(active===key)setActive(next[Math.min(i,next.length-1)]?.key??'launcher');};
 const menu=[...(contextTask?(['overview','records','flow'] as const).map(kind=>({id:kind,label:p.t(toolLabels[kind]),icon:kind==='flow'?<GitBranch/>:<FileText/>,run:()=>open(kind,contextTask)})):[]),{id:'plan',label:p.t('d4PlanInfo'),icon:<GitBranch/>,run:()=>open('plan')},{id:'materials',label:p.t('d4Materials'),icon:<Files/>,run:()=>open('materials')}];
 const send=()=>{if(!draft.trim())return;setMessages(old=>[...old,{id:crypto.randomUUID(),author:p.state.role,text:draft.trim(),time:new Date().toLocaleTimeString(p.locale,{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'})}]);setDraft('');};
 return <div className={'judex-d4-chat judex-d4-panel-'+panel} data-testid="d4-chat"><aside className="judex-d4-chat-sidebar"><Button size="sm" className="judex-d4-back" onPress={()=>p.go({kind:'route',planId:plan.id})}><ArrowLeft/>{p.t('d4BackRoute')}</Button><p className="judex-d4-meta">{p.t(task?'d4TaskContext':'d4PlanContext')}</p><h2>{p.text(task?.title??plan.title)}</h2><div className="judex-d4-discussion-list"><Button className={!task?'judex-d4-discussion-current':''} onPress={()=>p.go({kind:'chat',planId:plan.id})}><MessageCircle/><span>{p.text(plan.title)}</span></Button>{p.state.tasks.filter(t=>t.planId===plan.id).slice(0,3).map(t=><Button key={t.id} className={task?.id===t.id?'judex-d4-discussion-current':''} onPress={()=>p.discuss(t)}><MessageCircle/><span>{p.text(t.title)}</span></Button>)}</div></aside>
  <main className="judex-d4-conversation"><header className="judex-d4-conversation-heading"><div><h1>{p.text(task?.title??plan.title)}</h1><p>{p.t(task?'d4TaskContext':'d4PlanContext')} · {p.text(plan.title)}</p></div>{panel==='hidden'&&<Button size="sm" variant="outline" onPress={()=>setPanel('normal')}><Plus/>{p.t('d4AddPanel')}</Button>}</header><div className="judex-d4-messages">{messages.map(m=><article className={'judex-d4-message'+(m.author==='ai'?' judex-d4-message-ai':'')} key={m.id}><PersonAvatar name={m.author==='ai'?'Judex':p.text(people[m.author as keyof typeof people])} small/><div><header><strong>{m.author==='ai'?p.t('d4AIAnalysis'):p.text(people[m.author as keyof typeof people])}</strong><time>{m.time}</time></header><p>{p.text(m.text)}</p></div></article>)}</div><div className="judex-d4-composer"><div className="judex-d4-composer-scope"><MessageCircle/><span>{p.text(task?.title??plan.title)}</span></div><UITextArea aria-label={p.t('d4ChatPlaceholder')} placeholder={p.t('d4ChatPlaceholder')} data-testid="d4-chat-input" value={draft} onChange={e=>setDraft(e.target.value)} rows={3} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><div className="judex-d4-composer-bottom"><span>{p.t('d4ComposerHint')}</span><Button size="sm" variant="primary" disabled={!draft.trim()} onPress={send}>{p.t('d4Send')}<ArrowUp/></Button></div><p className="judex-d4-discussion-note">{p.t('d4DiscussionOnly')}</p></div></main>
  <aside className="judex-d4-workspace" data-testid="d4-workspace"><Tabs className="judex-d4-workspace-tabs" selectedKey={active} onSelectionChange={key=>setActive(String(key))}><div className="judex-d4-workspace-bar"><Tabs.List aria-label={p.t('d4AddPanel')} className="judex-d4-workspace-tab-list">{tools.map(tool=>{const target=p.state.tasks.find(t=>t.id===tool.taskId),Icon=toolIcons[tool.kind];return <Tabs.Tab id={tool.key} key={tool.key} className="judex-d4-workspace-tab" data-testid={'d4-tool-'+tool.kind+(target?'-'+target.id:'')} aria-label={p.t(toolLabels[tool.kind])+(target?' · '+p.text(target.title):'')}><Icon/><span title={target?p.text(target.title):p.text(plan.title)}>{p.t(toolLabels[tool.kind])}</span><Button size="sm" isIconOnly aria-label={p.t('d4CloseTab')+' · '+p.t(toolLabels[tool.kind])} className="judex-d4-tab-close" onPointerDown={e=>{e.preventDefault();e.stopPropagation();}} onClick={e=>{e.stopPropagation();close(tool.key);}}><X/></Button></Tabs.Tab>;})}{active==='launcher'&&<Tabs.Tab id="launcher">{p.t('d4AddPanel')}</Tabs.Tab>}</Tabs.List><Menu label={p.t('d4AddPanel')} testId="d4-add-panel" items={menu}><Plus/></Menu><Button size="sm" isIconOnly data-testid="d4-expand-panel" aria-label={p.t(panel==='wide'?'d4RestorePanel':'d4ExpandPanel')} onPress={()=>setPanel(panel==='wide'?'normal':'wide')}>{panel==='wide'?<Minimize2/>:<Maximize2/>}</Button><Button size="sm" isIconOnly aria-label={p.t('d4CollapsePanel')} onPress={()=>setPanel('hidden')}><X/></Button></div><Tabs.Panel id={active} className="judex-d4-workspace-body">{current?<WorkspaceContent tool={current} plan={plan} openTask={(target,section)=>open(section,target)}/>:<div className="judex-d4-launcher"><h2>{p.t('d4AddPanel')}</h2><p>{p.t('d4ToolsHint')}</p>{menu.map(item=><Button variant="outline" key={item.id} onPress={item.run}>{item.icon}{item.label}<ChevronRight/></Button>)}</div>}</Tabs.Panel></Tabs></aside>
 </div>;
}
function WorkspaceContent({tool,plan,openTask}:{tool:Tool;plan:Plan;openTask:(t:Task,s:Section)=>void}){
 const p=usePreview(),task=p.state.tasks.find(t=>t.id===tool.taskId);
 if(tool.kind==='plan')return <PlanPanel plan={plan} openTask={t=>openTask(t,'overview')}/>;
 if(tool.kind==='materials')return <Materials/>;
 if(!task)return <p className="judex-d4-empty">{p.t('d4Empty')}</p>;
 return <div className="judex-d4-task-panel"><TaskHeader task={task} onSection={section=>openTask(task,section)}/><div className="judex-d4-panel-scroll"><TaskSection task={task} section={tool.kind} onSection={section=>openTask(task,section)}/></div><TaskActions task={task}/></div>;
}
function PlanPanel({plan,openTask}:{plan:Plan;openTask:(task:Task)=>void}){
 const p=usePreview(),progress=stats(p.state,plan),tasks=p.state.tasks.filter(t=>t.planId===plan.id);
 return <div className="judex-d4-plan-panel"><div className="judex-d4-section-title"><h2>{p.text(plan.title)}</h2><Status status={plan.status}/></div><p>{p.text(plan.goal)}</p><div className="judex-d4-inline-meta"><span>{p.t('d4Owner')}</span><Person id={plan.owner}/></div><section><h3>{p.t('d4Criteria')}</h3><ul className="judex-d4-check-list">{plan.criteria.map((c,i)=><li key={i}><CheckIcon/>{p.text(c)}</li>)}</ul></section><div className="judex-d4-section-title"><strong>{plan.status==="draft"?p.t("d4DraftCount",{count:progress.drafts}):p.t("d4Progress",{done:progress.accepted,total:progress.total})}</strong><Button size="sm" onPress={()=>p.openViewer(plan.id,true)}><GitBranch/>{p.t('d4PreviewRoute')}</Button></div>{progress.skipped>0&&<p className="judex-d4-meta">{p.t('d4SkippedCount',{count:progress.skipped})}</p>}<section><h3>{p.t('d4Tasks')}</h3><div className="judex-d4-plan-task-list">{tasks.map(t=><Button key={t.id} onPress={()=>openTask(t)}><div><strong>{p.text(t.title)}</strong><span>{p.text(people[t.owner as keyof typeof people])}</span></div><Status status={taskStage(p.state,t)}/><ChevronRight/></Button>)}</div></section></div>;
}
import {Check as CheckIcon} from 'lucide-react';
function Materials(){
 const p=usePreview();return <div className="judex-d4-plan-panel"><h2>{p.t('d4Materials')}</h2><p className="judex-d4-meta">{p.t('d4SharedHint')}</p>{[{title:tx('本轮需求与验收清单.md','Requirements and acceptance checklist.md'),body:tx('范围：计划路线、任务详情和讨论侧栏。\n检查：草稿编辑删除、管理员跳过恢复、全屏位置保持与中英文深浅主题。','Scope: plan routes, task details, and discussion panels.\nChecks: draft editing/deletion, administrator skip/resume, fullscreen position retention, and both languages/themes.')},{title:tx('任务详情布局说明.md','Task detail layout.md'),body:tx('概览：说明、人员、完成条件和前置要求。\n记录：原始报告、资料与 AI 分析。\n流程参考：已发布规则及当前环节职责。','Overview: description, people, completion criteria, and prerequisites.\nRecords: original reports, materials, and AI analysis.\nWorkflow reference: published rules and the current step responsibility.')}].map((doc,i)=><UIDisclosure key={i} title={p.text(doc.title)}><p className="judex-d4-original">{p.text(doc.body)}</p></UIDisclosure>)}</div>;
}
