import {useState} from 'react';
import {Check,CornerDownRight,Lock} from 'lucide-react';
import {UIDialog} from '../src/components/ui/Presentation';
import {FormField,UICheckbox,UIInput,UIOption,UISelect,UITextArea,UIDisclosure} from '../src/components/ui/FormControls';
import {canEdit,deleteBlocked,descendants,people,tx,type ModalState,type Patch,type Text} from './model';
import {usePreview} from './context';
import {Button,Person} from './ui';
export function Dialogs({modal}:{modal:ModalState}){
 if(modal.kind==='edit'||modal.kind==='create')return <EditDialog modal={modal}/>;
 if(modal.kind==='delete')return <DeleteDialog modal={modal}/>;
 if(modal.kind==='review')return <ReviewDialog modal={modal}/>;
 if(modal.kind==='skip'||modal.kind==='restore')return <SkipDialog modal={modal}/>;
 return <ReportDialog id={modal.id}/>;
}
function EditDialog({modal}:{modal:Extract<ModalState,{kind:'edit'|'delete'|'review'}>|Extract<ModalState,{kind:'create'}>}){
 const p=usePreview(),isCreate=modal.kind==='create',type=isCreate?'task':modal.type,task=p.state.tasks.find(t=>t.id===modal.id),plan=p.state.plans.find(v=>v.id===(isCreate?modal.id:type==='plan'?modal.id:task?.planId)),item=isCreate?undefined:type==='task'?task:plan;
 const [version]=useState(item?.version??1),[title,setTitle]=useState(item?p.text(item.title):''),[description,setDescription]=useState(item?p.text(type==='task'?task!.description:plan!.goal):''),[criteria,setCriteria]=useState(item?item.criteria.map(p.text).join('\n'):''),[owner,setOwner]=useState(item?.owner??p.state.role),[reviewer,setReviewer]=useState(task?.reviewer??'manager'),[before,setBefore]=useState(task?.before??[]);
 const change=(old:Text|undefined,value:string):Text=>old?{...old,[p.locale==='en'?'en':'zh']:value}:tx(value,value);
 const save=()=>{const patch:Patch={title:change(item?.title,title.trim()),description:change(type==='task'?task?.description:plan?.goal,description.trim()),criteria:criteria.split('\n').map(v=>v.trim()).filter(Boolean).map((v,i)=>change(item?.criteria[i],v)),owner,reviewer,before};const result=isCreate?p.perform({kind:'create',planId:modal.id,patch}):p.perform({kind:'edit',type,id:modal.id,patch,version});if(result.state){p.setModal(null);if(result.id)p.setDrawer({id:result.id,section:'overview'});}};
 const heading=isCreate?'d4NewTask':item?.status==='draft'?type==='task'?'d4EditTask':'d4EditPlan':type==='task'?'d4ChangeTask':'d4ChangePlan';
 return <UIDialog title={p.t(heading)} onClose={()=>p.setModal(null)} wide footer={<div className="judex-d4-dialog-actions"><Button variant="outline" onPress={()=>p.setModal(null)}>{p.t('d4Cancel')}</Button><Button variant="primary" data-testid="d4-save-edit" disabled={!title.trim()||!description.trim()||!criteria.trim()} onPress={save}>{p.t(isCreate?'d4Create':item?.status==='draft'?'d4Save':'d4SubmitChange')}</Button></div>}><div className="judex-d4-form">
  {item?.pending&&<p className="judex-d4-form-note">{p.t('d4WithdrawHint')}</p>}{item&&item.status!=='draft'&&<p className="judex-d4-form-note">{p.t('d4LiveEditHint')}</p>}
  <FormField label={p.t('d4Title')}><UIInput data-testid="d4-edit-title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={200}/></FormField>
  <FormField label={p.t(type==='task'?'d4Description':'d4PlanGoal')}><UITextArea data-testid="d4-edit-description" value={description} onChange={e=>setDescription(e.target.value)} rows={3}/></FormField>
  <FormField label={p.t('d4Criteria')}><UITextArea data-testid="d4-edit-criteria" value={criteria} onChange={e=>setCriteria(e.target.value)} rows={3}/></FormField>
  <div className="judex-d4-form-grid"><FormField label={p.t('d4Owner')}><UISelect data-testid="d4-edit-owner" value={owner} onChange={e=>setOwner(e.target.value)}>{Object.entries(people).map(([id,name])=><UIOption key={id} value={id}>{p.text(name)}</UIOption>)}</UISelect></FormField>{type==='task'&&<FormField label={p.t('d4Reviewer')}><UISelect value={reviewer} onChange={e=>setReviewer(e.target.value)}>{Object.entries(people).map(([id,name])=><UIOption key={id} value={id}>{p.text(name)}</UIOption>)}</UISelect></FormField>}</div>
  {type==='task'&&<UIDisclosure title={p.t('d4Prerequisites')}><div className="judex-d4-choice-list">{p.state.tasks.filter(t=>t.planId===plan?.id&&t.id!==task?.id).map(t=><UICheckbox key={t.id} checked={before.includes(t.id)} onChange={e=>setBefore(v=>e.target.checked?[...v,t.id]:v.filter(id=>id!==t.id))}>{p.text(t.title)}</UICheckbox>)}</div></UIDisclosure>}
 </div></UIDialog>;
}
function DeleteDialog({modal}:{modal:Extract<ModalState,{kind:'edit'|'delete'|'review'}>}){
 const p=usePreview(),item=modal.type==='task'?p.state.tasks.find(t=>t.id===modal.id):p.state.plans.find(v=>v.id===modal.id),blocked=deleteBlocked(p.state,modal.type,modal.id),tasks=p.state.tasks.filter(t=>t.planId===modal.id);if(!item)return null;
 const remove=()=>{const result=p.perform({kind:'delete',type:modal.type,id:modal.id});if(result.state){p.setModal(null);p.setDrawer(null);if(modal.type==='plan')p.go({kind:'plans',projectId:p.page.projectId??p.state.plans.find(v=>v.id===modal.id)?.projectId??'product'});}};
 return <UIDialog title={p.t(modal.type==='task'?'d4DeleteTask':'d4DeletePlan')} onClose={()=>p.setModal(null)} footer={<div className="judex-d4-dialog-actions"><Button variant="outline" onPress={()=>p.setModal(null)}>{p.t('d4Cancel')}</Button><Button variant="danger" data-testid="d4-confirm-delete" disabled={!!blocked||!canEdit(p.state,item)} onPress={remove}>{p.t('d4DeleteConfirm')}</Button></div>}><div className="judex-d4-form"><h3>{p.text(item.title)}</h3><p>{p.t(modal.type==='task'?'d4DeleteTaskHint':'d4DeletePlanHint',{count:tasks.length})}</p>{modal.type==='plan'&&<ul className="judex-d4-check-list">{tasks.map(t=><li key={t.id}><Check/>{p.text(t.title)}</li>)}</ul>}{blocked&&<p className="judex-d4-block-note">{p.t('d4DeleteBlocked')}</p>}</div></UIDialog>;
}
function SkipDialog({modal}:{modal:Extract<ModalState,{kind:'skip'|'restore'|'report'}>}){
 const p=usePreview(),task=p.state.tasks.find(t=>t.id===modal.id),restore=modal.kind==='restore',[reason,setReason]=useState(''),[waivers,setWaivers]=useState<string[]>([]),[acknowledged,setAcknowledged]=useState(false),[version]=useState(task?.version??1);if(!task)return null;
 const next=p.state.tasks.filter(t=>t.before.includes(task.id)||t.conditions.some(c=>c.target===task.id)),active=descendants(p.state,task.id).filter(t=>['working','delivered','accepted','rework'].includes(t.status));
 const confirm=()=>{const result=restore?p.perform({kind:'restore',id:task.id,reason,version,acknowledged}):p.perform({kind:'skip',id:task.id,reason,waivers,version});if(result.state)p.setModal(null);};
 return <UIDialog wide title={p.t(restore?'d4RestoreTitle':'d4SkipTitle')} onClose={()=>p.setModal(null)} footer={<div className="judex-d4-dialog-actions"><Button variant="outline" onPress={()=>p.setModal(null)}>{p.t('d4Cancel')}</Button><Button variant="primary" data-testid="d4-confirm-skip" disabled={!reason.trim()||p.state.role!=='manager'||restore&&active.length>0&&!acknowledged} onPress={confirm}>{p.t(restore?'d4ConfirmRestore':'d4ConfirmSkip')}</Button></div>}><div className="judex-d4-form"><div className="judex-d4-confirm-task"><strong>{p.text(task.title)}</strong><Person id={task.owner}/></div><p className="judex-d4-form-note">{p.t(restore?'d4RestoreHint':'d4SkipScope')}</p><FormField label={p.t(restore?'d4RestoreReason':'d4SkipReason')}><UITextArea value={reason} data-testid="d4-skip-reason" onChange={e=>setReason(e.target.value)} rows={2}/></FormField>
  {!restore&&<section><h3>{p.t('d4Affected')}</h3><div className="judex-d4-affected-list">{next.map(t=>{const hard=t.conditions.filter(c=>c.kind==='acceptance'&&c.target===task.id);return <div className="judex-d4-affected" key={t.id}><div className="judex-d4-section-title"><strong>{p.text(t.title)}</strong><span className="judex-d4-meta">{p.t(hard.length?'d4HardDependency':'d4SequenceConstraint')}</span></div>{hard.length?hard.map(c=><UICheckbox key={c.id} checked={waivers.includes(c.id)} data-testid={'d4-waive-'+c.id} onChange={e=>setWaivers(v=>e.target.checked?[...v,c.id]:v.filter(id=>id!==c.id))}>{p.t('d4Waive')}</UICheckbox>):<p className="judex-d4-meta"><CornerDownRight/>{p.t('d4SequenceBypass')}</p>}</div>;})}</div><p className="judex-d4-meta">{p.t('d4OtherConditions')}</p>{next.some(t=>t.conditions.some(c=>c.target===task.id&&!waivers.includes(c.id)))&&<p className="judex-d4-block-note"><Lock/>{p.t('d4SkipNoWaiver')}</p>}</section>}
  {restore&&active.length>0&&<section><p>{p.t('d4RestoreImpact')}</p><ul className="judex-d4-check-list">{active.map(t=><li key={t.id}><Lock/>{p.text(t.title)}</li>)}</ul><UICheckbox checked={acknowledged} data-testid="d4-restore-ack" onChange={e=>setAcknowledged(e.target.checked)}>{p.t('d4RestoreAcknowledge')}</UICheckbox></section>}
 </div></UIDialog>;
}
function ReviewDialog({modal}:{modal:Extract<ModalState,{kind:'edit'|'delete'|'review'}>}){
 const p=usePreview(),change=p.state.changes.find(c=>c.type===modal.type&&c.id===modal.id),task=p.state.tasks.find(t=>t.id===modal.id),plan=p.state.plans.find(v=>v.id===modal.id),item=modal.type==='task'?task:plan;if(!change||!item)return null;
 const rows=[{label:p.t('d4Title'),old:p.text(item.title),next:p.text(change.patch.title)},{label:p.t(modal.type==='task'?'d4Description':'d4PlanGoal'),old:p.text(task?.description??plan!.goal),next:p.text(change.patch.description)},{label:p.t('d4Criteria'),old:item.criteria.map(p.text).join('\n'),next:change.patch.criteria.map(p.text).join('\n')},{label:p.t('d4Owner'),old:p.text(people[item.owner as keyof typeof people]),next:p.text(people[change.patch.owner as keyof typeof people])}];
 return <UIDialog wide title={p.t('d4Compare')} onClose={()=>p.setModal(null)} footer={<div className="judex-d4-dialog-actions"><Button variant="outline" onPress={()=>p.setModal(null)}>{p.t('d4Cancel')}</Button><Button variant="primary" data-testid="d4-confirm-change" disabled={p.state.role!=='manager'} onPress={()=>{if(p.perform({kind:'confirm',type:modal.type,id:modal.id,version:change.version}).state)p.setModal(null);}}>{p.t('d4ConfirmChange')}</Button></div>}><div className="judex-d4-form"><p className="judex-d4-form-note">{p.t('d4LiveEditHint')}</p><table className="judex-d4-compare"><thead><tr><th/><th>{p.t('d4Old')}</th><th>{p.t('d4New')}</th></tr></thead><tbody>{rows.map(row=><tr key={row.label}><th>{row.label}</th><td>{row.old}</td><td>{row.next}</td></tr>)}</tbody></table></div></UIDialog>;
}
function ReportDialog({id}:{id:string}){
 const p=usePreview(),task=p.state.tasks.find(t=>t.id===id),[text,setText]=useState(''),[delivery,setDelivery]=useState(false);if(!task)return null;
 return <UIDialog title={p.t('d4Report')} onClose={()=>p.setModal(null)} footer={<div className="judex-d4-dialog-actions"><Button variant="outline" onPress={()=>p.setModal(null)}>{p.t('d4Cancel')}</Button><Button variant="primary" disabled={!text.trim()} onPress={()=>{if(p.perform({kind:'report',id,text,delivery}).state)p.setModal(null);}}>{p.t('d4SubmitReport')}</Button></div>}><div className="judex-d4-form"><strong>{p.text(task.title)}</strong><FormField label={p.t('d4ReportText')}><UITextArea value={text} onChange={e=>setText(e.target.value)} rows={5}/></FormField><UICheckbox checked={delivery} onChange={e=>setDelivery(e.target.checked)}>{p.t('d4FinishSample')}</UICheckbox></div></UIDialog>;
}
