import {Card} from '@heroui/react';
import {useEffect,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {ArrowUpRight,Check,GitBranch,MessageCircle,Plus,Search,X} from 'lucide-react';
import {UIInput,UIOption,UISelect,UIDisclosure} from '../src/components/ui/FormControls';
import {usePreview} from './context';
import {canEdit,projectNames,stats,type Plan} from './model';
import {Button,Heading,Person,PlanMenu,Status,PendingChange} from './ui';
import {Graph} from './graph';
import {TaskDrawer} from './task';
function read(key:string,fallback:string){try{return sessionStorage.getItem('judex.demo4.'+key)??fallback;}catch{return fallback;}}
function write(key:string,value:string){try{sessionStorage.setItem('judex.demo4.'+key,value);}catch{}}
export function ScrollPage({name,children}:{name:string;children:ReactNode}){const el=useRef<HTMLDivElement>(null);useLayoutEffect(()=>{if(el.current)el.current.scrollTop=Number(read('scroll.'+name,'0'));},[name]);return <div className="judex-d4-page-scroll" ref={el} onScroll={e=>write('scroll.'+name,String(e.currentTarget.scrollTop))}>{children}</div>;}
export function ProjectList(){
 const p=usePreview();return <ScrollPage name="projects"><main className="judex-d4-main"><Heading title={p.t('d4Projects')} description={p.t('d4ProjectListHint')}/><div className="judex-d4-project-grid">{Object.entries(projectNames).map(([id,title])=><Card className="judex-d4-board-card" key={id} data-testid={'d4-project-'+id}><Card.Header><span className="judex-d4-card-symbol"><GitBranch/></span><Card.Title>{p.text(title)}</Card.Title><Card.Description>{p.t('d4ProjectDescription')}</Card.Description></Card.Header><Card.Content><div className="judex-d4-inline-meta"><span>{p.t('d4MembersCount',{count:id==='product'?4:2})}</span><span>{p.t('d4PlansCount',{count:p.state.plans.filter(v=>v.projectId===id).length})}</span></div></Card.Content><Card.Footer><Button size="sm" variant="outline" onPress={()=>p.go({kind:'plans',projectId:id})}>{p.t('d4Plans')}<ArrowUpRight/></Button></Card.Footer></Card>)}</div></main></ScrollPage>;
}
export function PlanList(){
 const p=usePreview(),project=p.page.projectId??'product',[query,setQuery]=useState(()=>read('filter.q.'+project,'')),[filter,setFilter]=useState(()=>read('filter.kind.'+project,'all'));
 useEffect(()=>write('filter.q.'+project,query),[query,project]);useEffect(()=>write('filter.kind.'+project,filter),[filter,project]);
 const plans=p.state.plans.filter(plan=>plan.projectId===project&&(filter!=='draft'||plan.status==='draft')&&p.text(plan.title).toLowerCase().includes(query.toLowerCase()));
 return <ScrollPage name={'plans.'+project}><main className="judex-d4-main"><Heading title={p.text(projectNames[project as keyof typeof projectNames])} description={p.t('d4PlanListHint')} back={{label:p.t('d4BackProjects'),run:()=>p.go({kind:'projects'})}}/><div className="judex-d4-list-toolbar"><div className="judex-d4-search"><Search/><UIInput aria-label={p.t('d4SearchPlans')} placeholder={p.t('d4SearchPlans')} value={query} onChange={e=>setQuery(e.target.value)}/></div><UISelect value={filter} aria-label={p.t('d4AllPlans')} onChange={e=>setFilter(e.target.value)}><UIOption value="all">{p.t('d4AllPlans')}</UIOption><UIOption value="draft">{p.t('d4DraftFilter')}</UIOption></UISelect></div><div className="judex-d4-plan-grid">{plans.map(plan=><PlanCard plan={plan} key={plan.id}/>)}</div>{!plans.length&&<p className="judex-d4-empty">{p.t('d4NoPlans')}</p>}</main></ScrollPage>;
}
function PlanCard({plan}:{plan:Plan}){
 const p=usePreview(),progress=stats(p.state,plan);return <Card className="judex-d4-board-card" data-testid={'d4-plan-'+plan.id}><div className="judex-d4-card-top"><Status status={plan.status}/><PlanMenu plan={plan}/></div><Button className="judex-d4-board-hit" aria-label={p.t('d4ViewPlan',{title:p.text(plan.title)})} onPress={()=>p.go({kind:'route',planId:plan.id})}><h2>{p.text(plan.title)}</h2><p>{p.text(plan.goal)}</p></Button><Card.Content><div className="judex-d4-inline-meta"><span>{p.t('d4Owner')}</span><Person id={plan.owner}/></div><div hidden={plan.status === "draft"} className="judex-d4-progress" role="progressbar" aria-label={p.t('d4Progress', {done:progress.accepted,total:progress.total})} aria-valuenow={progress.accepted} aria-valuemax={Math.max(1,progress.total)}><span style={{width:(progress.total?progress.accepted/progress.total*100:0)+'%'}}/></div><div className="judex-d4-inline-meta"><span>{plan.status==="draft"?p.t("d4DraftCount",{count:progress.drafts}):p.t("d4Progress",{done:progress.accepted,total:progress.total})}</span>{progress.drafts>0&&plan.status!=="draft"&&<span>{p.t('d4DraftCount',{count:progress.drafts})}</span>}{progress.skipped>0&&<span>{p.t('d4SkippedCount',{count:progress.skipped})}</span>}</div></Card.Content><Card.Footer className="judex-d4-board-footer"><Button size="sm" variant="ghost" data-testid={'d4-preview-'+plan.id} onPress={()=>p.openViewer(plan.id,true)}><GitBranch/>{p.t('d4PreviewRoute')}</Button><Button size="sm" variant="outline" onPress={()=>p.go({kind:'chat',planId:plan.id})}><MessageCircle/>{p.t('d4Discuss')}</Button></Card.Footer></Card>;
}
export function PlanSummary({plan}:{plan:Plan}){
 const p=usePreview(),progress=stats(p.state,plan);return <div className="judex-d4-plan-summary"><div className="judex-d4-summary-owner"><span className="judex-d4-meta">{p.t('d4Owner')}</span><Person id={plan.owner}/></div><div className="judex-d4-summary-criteria"><span className="judex-d4-meta">{p.t('d4Criteria')}</span><span><Check/>{p.text(plan.criteria[0]??'')}</span>{plan.criteria.length>1&&<UIDisclosure title={p.t('d4AdditionalCriteria',{count:plan.criteria.length-1})}><ul className="judex-d4-check-list">{plan.criteria.slice(1).map((c,i)=><li key={i}><Check/><span>{p.text(c)}</span></li>)}</ul></UIDisclosure>}</div><div className="judex-d4-summary-progress"><span>{plan.status==="draft"?p.t("d4DraftCount",{count:progress.drafts}):p.t("d4Progress",{done:progress.accepted,total:progress.total})}</span><div className="judex-d4-inline-meta">{progress.drafts>0&&plan.status!=="draft"&&<span>{p.t('d4DraftCount',{count:progress.drafts})}</span>}{progress.skipped>0&&<span>{p.t('d4SkippedCount',{count:progress.skipped})}</span>}</div></div></div>;
}
export function PlanPage(){
 const p=usePreview(),plan=p.state.plans.find(v=>v.id===p.page.planId);
 if(!plan)return <PlanList/>;
 return <ScrollPage name={'route.'+plan.id}><main className="judex-d4-main judex-d4-route-main"><Heading title={p.text(plan.title)} description={p.text(plan.goal)} back={{label:p.t('d4BackPlans'),run:()=>p.go({kind:'plans',projectId:plan.projectId})}} actions={<><Status status={plan.status}/><Button variant="outline" onPress={()=>p.go({kind:'chat',planId:plan.id})}><MessageCircle/>{p.t('d4Discuss')}</Button>{canEdit(p.state,plan)&&plan.status!=='accepted'&&<Button variant="primary" data-testid="d4-new-task" onPress={()=>p.setModal({kind:'create',id:plan.id})}><Plus/>{p.t('d4NewTask')}</Button>}<PlanMenu plan={plan}/></>}/><PendingChange type="plan" id={plan.id}/><PlanSummary plan={plan}/><div className={'judex-d4-route-body'+(p.drawer?' judex-d4-has-drawer':'')}><Graph plan={plan}/><TaskDrawer/></div></main></ScrollPage>;
}
export function FullScreenViewer(){
 const p=usePreview(),plan=p.state.plans.find(v=>v.id===p.viewer?.planId);if(!plan)return null;
 return <div className="judex-d4-fullscreen" data-testid="d4-fullscreen-view"><header className="judex-d4-fullscreen-header"><div className="judex-d4-fullscreen-title"><GitBranch/><h1>{p.text(plan.title)}</h1>{p.viewer?.preview&&<span className="judex-d4-meta">{p.t('d4ReadOnly')}</span>}</div><div className="judex-d4-actions">{p.viewer?.preview&&<Button size="sm" variant="outline" onPress={()=>p.go({kind:'route',planId:plan.id})}>{p.t('d4EnterPlan')}<ArrowUpRight/></Button>}<Button size="sm" data-testid="d4-exit-fullscreen" onPress={p.closeViewer}><X/>{p.t('d4ExitFullScreen')}<kbd>Esc</kbd></Button></div></header><div className={'judex-d4-route-body judex-d4-fullscreen-body'+(p.drawer?' judex-d4-has-drawer':'')}><Graph plan={plan} full readOnly={p.viewer?.preview}/><TaskDrawer readOnly={p.viewer?.preview}/></div></div>;
}
