import {Tabs} from '@heroui/react';
import {Check,CornerDownRight,FileText,Lock,MessageCircle,Paperclip,Pencil,X,ArrowUpRight} from 'lucide-react';
import {UIDisclosure} from '../src/components/ui/FormControls';
import {usePreview} from './context';
import {canEdit,canWork,people,taskStage,unmet,workflowNodes,type Section,type Task} from './model';
import {Button,Person,Status,TaskMenu,PendingChange} from './ui';
export function TaskHeader({task,readOnly=false,onSection}:{task:Task;readOnly?:boolean;onSection?:(s:Section)=>void}){
 const p=usePreview(),plan=p.state.plans.find(v=>v.id===task.planId);
 return <header className="judex-d4-task-heading"><p className="judex-d4-breadcrumb">{p.text(plan?.title??'')}</p><div className="judex-d4-task-title"><h2>{p.text(task.title)}</h2><TaskMenu task={task} readOnly={readOnly} onSection={onSection}/></div><div className="judex-d4-inline-meta"><Status status={taskStage(p.state,task)}/><Person id={task.owner}/></div><PendingChange type="task" id={task.id}/></header>;
}
export function TaskSection({task,section,onSection,readOnly=false}:{task:Task;section:Section;onSection?:(s:Section)=>void;readOnly?:boolean}){
 const p=usePreview(),records=p.state.records.filter(r=>r.taskId===task.id),blocked=unmet(p.state,task),openRecords=()=>onSection?onSection('records'):p.setDrawer({id:task.id,section:'records'});
 if(section==='flow'&&!task.workflowAssigned)return <div className="judex-d4-task-content" data-testid="d4-section-flow"><h3>{p.t('d4FlowVersion')}</h3><p className="judex-d4-meta">{p.t('d4NoWorkflow')}</p></div>;
 return <div className="judex-d4-task-content" data-testid={'d4-section-'+section}>
  {section==='overview'?<>
   <section><h3>{p.t('d4Description')}</h3><p>{p.text(task.description)||p.t('d4NoDescription')}</p></section>
   <section><h3>{p.t('d4Criteria')}</h3><ul className="judex-d4-check-list">{task.criteria.map((c,i)=><li key={i}><Check/><span>{p.text(c)}</span></li>)}</ul></section>
   <dl className="judex-d4-facts"><div><dt>{p.t('d4Reviewer')}</dt><dd><Person id={task.reviewer}/></dd></div><div><dt>{p.t('d4VersionLabel')}</dt><dd>{task.version}</dd></div></dl>
   {(task.before.length>0||task.conditions.length>0)&&<section><h3>{p.t('d4Prerequisites')}</h3><div className="judex-d4-condition-list">{task.before.map(id=>{const prev=p.state.tasks.find(t=>t.id===id);return prev&&<div className="judex-d4-condition" key={id}>{prev.skip?<CornerDownRight/>:prev.status==='accepted'?<Check/>:<Lock/>}<span>{p.text(prev.title)}</span><span className="judex-d4-meta">{p.t(prev.skip?'d4Skipped':prev.status==='accepted'?'d4Accepted':'d4WaitFor',{title:''})}</span></div>;})}{task.conditions.map(c=>{const prev=p.state.tasks.find(t=>t.id===c.target),waived=prev?.skip?.waivers.includes(c.id),met=waived||(c.kind==='acceptance'?prev?.status==='accepted':c.met);return <div className="judex-d4-condition" key={c.id}>{met?<Check/>:<Lock/>}<span>{p.text(c.label)}</span>{waived&&<span className="judex-d4-meta">{p.t('d4Waived')}</span>}</div>;})}</div></section>}
   {task.skip&&<section className="judex-d4-skip-note"><h3><CornerDownRight/>{p.t('d4SkippedAt')}</h3><p>{task.skip.reason}</p><span className="judex-d4-meta">{new Date(task.skip.at).toLocaleString(p.locale,{timeZone:'Asia/Shanghai'})}</span></section>}
   {!task.skip&&blocked.length>0&&task.status!=='draft'&&<p className="judex-d4-block-note"><Lock/>{p.t('d4WaitFor',{title:blocked.map(p.text).join('、')})}</p>}
   {records[0]&&<section className="judex-d4-latest"><div className="judex-d4-section-title"><h3>{p.t('d4Latest')}</h3><Button size="sm" onPress={openRecords}>{p.t('d4Records')}<ArrowUpRight/></Button></div><p>{p.text(records[0].summary)}</p></section>}
  </>:section==='records'?<><h3>{p.t('d4History')}</h3>{records.length?<div className="judex-d4-timeline">{records.map(r=><article className="judex-d4-record" key={r.id}><div className="judex-d4-record-header"><Person id={r.author}/><time>{new Date(r.at).toLocaleString(p.locale,{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'})}</time></div><span className="judex-d4-meta">{p.t(r.source==='cli'?'d4CLISource':'d4WebSource')}</span><p>{p.text(r.summary)}</p>{r.materials&&<div className="judex-d4-materials">{r.materials.map((v,i)=><span key={i}><Paperclip/>{p.text(v)}</span>)}</div>}<UIDisclosure title={p.t('d4Original')}><p className="judex-d4-original">{p.text(r.original)}</p></UIDisclosure>{r.analysis&&<div className="judex-d4-analysis"><strong>{p.t('d4AIAnalysis')}</strong><p>{p.text(r.analysis)}</p></div>}</article>)}</div>:<p className="judex-d4-meta">{p.t('d4RecordEmpty')}</p>}</>:<>
   <section><h3>{p.t('d4FlowVersion')}</h3><div className="judex-d4-section-title"><strong>{p.t('d4WorkflowName')}</strong><span className="judex-d4-meta">{p.t('d4Published')}</span></div></section>
   <section><h3>{p.t('d4CurrentNode')}</h3><p className="judex-d4-current-node">{p.text(task.flowNode)}</p></section><section><h3>{p.t('d4Responsibility')}</h3><p>{p.text(task.responsibility)}</p></section>
   <section><h3>{p.t('d4HardRules')}</h3><ul className="judex-d4-check-list"><li><Check/><span>{p.t('d4OtherConditions')}</span></li>{task.conditions.map(c=><li key={c.id}><Lock/><span>{p.text(c.label)}</span></li>)}</ul></section>
   <div className="judex-d4-flow-strip" aria-label={p.t('d4EffectivePath')}>{workflowNodes.map(node=><span className={node.zh===task.flowNode.zh?'judex-d4-flow-current':''} key={node.zh}>{p.text(node)}</span>)}</div><p className="judex-d4-meta">{p.t('d4ReferenceHint')}</p><Button size="sm" variant="outline" onPress={()=>p.openViewer(task.planId,true,task.id)}><GitBranchIcon/>{p.t('d4LocateInPlan')}</Button>
  </>}
 </div>;
}
import {GitBranch as GitBranchIcon} from 'lucide-react';
export function TaskActions({task,readOnly=false}:{task:Task;readOnly?:boolean}){
 const p=usePreview(),work=canWork(p.state,task)&&!task.skip;
 return <footer className="judex-d4-task-actions">{!readOnly&&task.status==='draft'&&canEdit(p.state,task)?<Button size="sm" variant="primary" onPress={()=>p.setModal({kind:'edit',type:'task',id:task.id})}><Pencil/>{p.t('d4EditTask')}</Button>:!readOnly&&work&&['ready','rework'].includes(task.status)?<Button size="sm" variant="primary" disabled={unmet(p.state,task).length>0} onPress={()=>p.perform({kind:'start',id:task.id})}>{p.t('d4Start')}</Button>:!readOnly&&work&&task.status==='working'?<Button size="sm" variant="primary" onPress={()=>p.setModal({kind:'report',id:task.id})}><FileText/>{p.t('d4Report')}</Button>:null}<Button size="sm" variant="outline" onPress={()=>p.discuss(task)}><MessageCircle/>{p.t('d4TaskDiscuss')}</Button></footer>;
}
export function TaskDrawer({readOnly=false}:{readOnly?:boolean}){
 const p=usePreview(),task=p.state.tasks.find(t=>t.id===p.drawer?.id),close=()=>{p.setDrawer(null);document.querySelector<HTMLButtonElement>('[data-testid="d4-task-'+task?.id+'"] .judex-d4-card-body')?.focus();};if(!task||!p.drawer)return null;
 return <aside className="judex-d4-drawer" aria-label={p.text(task.title)} data-testid="d4-drawer"><div className="judex-d4-drawer-top"><span>{p.t('d4Summary')}</span><Button size="sm" isIconOnly aria-label={p.t('d4Close')} data-testid="d4-close-drawer" onPress={close}><X/></Button></div><TaskHeader task={task} readOnly={readOnly}/><Tabs variant="secondary" className="judex-d4-detail-tabs" selectedKey={p.drawer.section} onSelectionChange={key=>p.setDrawer({id:task.id,section:key as Section})}><Tabs.List aria-label={p.t('d4Summary')}><Tabs.Tab id="overview">{p.t('d4Summary')}<Tabs.Indicator/></Tabs.Tab><Tabs.Tab id="records">{p.t('d4Records')}<Tabs.Indicator/></Tabs.Tab><Tabs.Tab id="flow">{p.t('d4Flow')}<Tabs.Indicator/></Tabs.Tab></Tabs.List><Tabs.Panel id={p.drawer.section} className="judex-d4-detail-body"><TaskSection task={task} section={p.drawer.section} readOnly={readOnly}/></Tabs.Panel></Tabs><TaskActions task={task} readOnly={readOnly}/></aside>;
}
