// Copy for the standalone design proposal. Kept outside the production i18n registry.
export const zh = {
  preview: '设计预览', samples: '示例数据', login: '登录', projects: '项目列表', workspace: '项目协作',
  light: '浅色', dark: '深色', theme: '切换主题', language: '切换语言',
  brandLine: '让讨论有方向，让协作有结果。', brandFirst: '好的协作，', brandSecond: '从这里开始。',
  brandDescription: '把想法、讨论和工作连接起来。让每个决定有依据，让每次交付被看见。',
  brandCaption: '一个项目。一段讨论。一起向前。', internal: '团队协作空间',
  welcome: '欢迎回来', loginHint: '登录 Judex，继续和团队一起推进工作。', email: '工作邮箱',
  password: '密码', emailPlaceholder: 'you@company.com', passwordPlaceholder: '输入你的密码',
  showPassword: '显示密码', hidePassword: '隐藏密码', forgot: '忘记密码？',
  noAccount: '第一次来到这里？', register: '创建账号', loginDemo: '直接体验工作空间',
  loginNote: '此处为界面预览，可使用任意邮箱和密码。', registerTitle: '创建你的账号',
  recoverTitle: '找回密码', name: '姓名', namePlaceholder: '你的姓名', backLogin: '返回登录',
  sendReset: '发送重置链接', resetSent: '预览：重置链接已发送，请检查工作邮箱。',
  registered: '预览账号已创建，欢迎来到 Judex。', loginToast: '已进入示例工作空间。',
  myProjects: '我的项目', projectHint: '找到你的团队，继续上一次的好想法。', newProject: '新建项目',
  searchProjects: '搜索项目…', allProjects: '全部项目', owned: '我负责的', participating: '我参与的',
  all: '全部', active: '进行中', recent: '最近讨论', recentlyUpdated: '最近更新', title: '项目名称',
  projectNamePlaceholder: '为这个项目起一个名字', description: '项目简介',
  projectDescriptionPlaceholder: '用一句话描述这个项目的目标（选填）', create: '创建项目', cancel: '取消',
  projectCreated: '项目已添加到预览。', owner: '负责人', admin: '管理员', member: '成员',
  discussions: '个讨论', members: '位成员', pending: '待决定', enterProject: '进入项目',
  newCardTitle: '下一件值得一起做的事', newCardHint: '建立一个空间，让想法开始流动。',
  projectCount: '个项目', account: '个人设置', preferences: '偏好设置', close: '关闭', logout: '退出登录',
  appearance: '外观', displayLanguage: '显示语言', settingsHint: '为你的工作空间选择舒适的阅读方式。',
  emptyProjects: '没有找到相关项目', emptyProjectsHint: '换个关键词，或创建一个新的项目。',
  returnProjects: '返回项目列表', newDiscussion: '新建讨论', searchDiscussions: '搜索讨论…',
  conversations: '讨论', handoffs: '交接', inbox: '交接信箱', tasks: '任务', materials: '资料',
  decisions: '待决定', yourDecisions: '需要我决定', projectSettings: '项目设置',
  connected: '协作空间', today: '今天', yesterday: '昨天', justNow: '刚刚',
  discussTitle: '讨论主题', discussPlaceholder: '这次想和团队聊什么？', discussCreated: '新讨论已创建。',
  discussionHint: '围绕一个清晰的主题，邀请想法、资料和建议。',
  emptyDiscussion: '从一个想法开始', emptyDiscussionHint: '说说你的目标、遇到的问题，或希望团队一起讨论的事情。',
  messagePlaceholder: '分享想法，或补充一点新的进展…', send: '发送', attach: '添加附件',
  attachmentReady: '已添加附件', messageSent: '消息已添加到预览。', composerHint: 'Enter 发送 · Shift + Enter 换行',
  aiBoundary: 'AI 提供建议，正式决定由人确认。', aiRole: '项目协调 AI', aiTag: 'AI 建议',
  proposal: '工作提案', proposalHint: '将讨论整理为可确认的工作安排', reviewProposal: '查看提案',
  waitingConfirmation: '等待成员确认', proposalTitle: '登录与项目入口体验优化',
  proposalBody: '统一登录、项目列表与协作页面的视觉层级，先确认设计方向，再开始实施。',
  proposalOutcome: '验收要求', proposalCriteria: '桌面端排版清晰；中英文和深浅色一致；现有协作流程可用。',
  proposalOwner: '发起人', proposalScope: '涉及成员', proposalScopeValue: '林晓 · 陈安 · 周宁',
  proposalNotice: '这是示例提案。确认按钮只改变本页的预览状态。', agree: '同意此提案', approved: '你已确认',
  approvedToast: '已记录你的预览确认，仍需其余成员决定。',
  inProgress: '进行中', toDo: '待开始', done: '已完成', taskHint: '围绕当前目标，逐步向前。',
  planTitle: 'V1 体验优化', progress: '工作进度', completed: '已完成',
  taskOne: '整理界面优化方案', taskTwo: '确认交互与视觉方向', taskThree: '实现统一组件样式',
  taskFour: '桌面端体验验收', taskDetail: '任务详情', taskDetailHint: '本任务关联当前讨论与体验优化计划。',
  assignee: '执行人', reviewer: '验收人', due: '截止日期', dueValue: '10 月 10 日',
  taskCriteria: '形成可查看的界面方案，覆盖登录、项目列表和项目内协作页面。',
  acceptance: '验收条件', relatedDiscussion: '关联讨论', openDiscussion: '回到讨论',
  filesHint: '团队共享的资料与讨论依据。', fileOne: '界面优化说明.md', fileTwo: '交互验收清单.md',
  updatedBy: '更新于今天 · 林晓', openFile: '查看资料',
  fileContent: '统一使用暖灰背景、低饱和绿与清晰的按钮层级。登录页减少嵌套；项目列表突出项目入口；三栏工作区保持讨论、资料与工作的关联。',
  decisionHint: '这里汇集需要你明确判断的事项。', allDone: '暂时没有待决定事项',
  allDoneHint: '新的工作提案与交接请求会出现在这里。', receivedHandoff: '验收资料交接',
  handoffHint: '陈安提交了交付材料，请查看后决定是否接收。', receive: '接收交接',
  handoffAccepted: '已接收示例交接。任务最终验收仍需单独确认。',
  hidePanel: '收起工作面板', showPanel: '展开工作面板', expandPanel: '最大化工作面板', restorePanel: '恢复三栏',
  noDiscussions: '没有找到讨论', you: '你', newProjectWelcome: '你的项目已经准备好了',
  newProjectHint: '从一次讨论开始，把目标、工作与团队连接起来。',
  footer: 'Judex · 一起把事情做好', recentlyViewed: '最近打开',
} as const;

export type CopyKey = keyof typeof zh;
export const en: Record<CopyKey, string> = {
  preview: 'Design preview', samples: 'Sample data', login: 'Sign in', projects: 'Projects', workspace: 'Workspace',
  light: 'Light', dark: 'Dark', theme: 'Change theme', language: 'Change language',
  brandLine: 'Clear discussions. Meaningful progress.', brandFirst: 'Good work,', brandSecond: 'together.',
  brandDescription: 'Connect ideas, discussions and work. Give every decision a foundation and every delivery a place.',
  brandCaption: 'One project. One conversation. Forward, together.', internal: 'A space for your team',
  welcome: 'Welcome back', loginHint: 'Sign in to Judex and pick up where your team left off.', email: 'Work email',
  password: 'Password', emailPlaceholder: 'you@company.com', passwordPlaceholder: 'Enter your password',
  showPassword: 'Show password', hidePassword: 'Hide password', forgot: 'Forgot password?',
  noAccount: 'New around here?', register: 'Create an account', loginDemo: 'Explore the workspace',
  loginNote: 'A design preview. Use any email and password.', registerTitle: 'Create your account',
  recoverTitle: 'Reset your password', name: 'Name', namePlaceholder: 'Your name', backLogin: 'Back to sign in',
  sendReset: 'Send reset link', resetSent: 'Preview: a reset link has been sent to your work email.',
  registered: 'Your preview account is ready. Welcome to Judex.', loginToast: 'Welcome to the sample workspace.',
  myProjects: 'Your projects', projectHint: 'Find your team. Pick up your next good idea.', newProject: 'New project',
  searchProjects: 'Search projects…', allProjects: 'All projects', owned: 'Owned by me', participating: 'Joined',
  all: 'All', active: 'In progress', recent: 'Recent discussions', recentlyUpdated: 'Recently updated', title: 'Project name',
  projectNamePlaceholder: 'Give this project a name', description: 'Description',
  projectDescriptionPlaceholder: 'A short description of your goal (optional)', create: 'Create project', cancel: 'Cancel',
  projectCreated: 'Project added to the preview.', owner: 'Owner', admin: 'Admin', member: 'Member',
  discussions: 'discussions', members: 'members', pending: 'To review', enterProject: 'Open project',
  newCardTitle: 'Your next good idea', newCardHint: 'Make a space for something worth doing together.',
  projectCount: 'projects', account: 'Personal settings', preferences: 'Preferences', close: 'Close', logout: 'Sign out',
  appearance: 'Appearance', displayLanguage: 'Language', settingsHint: 'Make your workspace comfortable to read.',
  emptyProjects: 'No matching projects', emptyProjectsHint: 'Try another keyword or start a new project.',
  returnProjects: 'Back to projects', newDiscussion: 'New discussion', searchDiscussions: 'Search discussions…',
  conversations: 'Discussions', handoffs: 'Handoffs', inbox: 'Handoff inbox', tasks: 'Tasks', materials: 'Files',
  decisions: 'To review', yourDecisions: 'Needs your decision', projectSettings: 'Project settings',
  connected: 'Team workspace', today: 'Today', yesterday: 'Yesterday', justNow: 'Just now',
  discussTitle: 'Discussion title', discussPlaceholder: 'What would you like to discuss?', discussCreated: 'Discussion created.',
  discussionHint: 'Start with a clear topic. Bring ideas, context and suggestions.',
  emptyDiscussion: 'Start with an idea', emptyDiscussionHint: 'Share a goal, a question, or something you want to explore together.',
  messagePlaceholder: 'Share an idea or a little progress…', send: 'Send', attach: 'Attach a file',
  attachmentReady: 'File attached', messageSent: 'Message added to the preview.', composerHint: 'Enter to send · Shift + Enter for a new line',
  aiBoundary: 'AI offers suggestions. People make the decisions.', aiRole: 'Project coordinator AI', aiTag: 'AI suggestion',
  proposal: 'Work proposal', proposalHint: 'Turn a discussion into a plan for review', reviewProposal: 'View proposal',
  waitingConfirmation: 'Awaiting team review', proposalTitle: 'Improve sign-in and project entry',
  proposalBody: 'Align the visual hierarchy of sign-in, projects and collaboration. Review the direction before implementation.',
  proposalOutcome: 'Acceptance criteria', proposalCriteria: 'Clear desktop layouts; consistent languages and themes; existing collaboration flows remain usable.',
  proposalOwner: 'Proposed by', proposalScope: 'Participants', proposalScopeValue: 'Xiaolin · Chen · Ning',
  proposalNotice: 'This is a sample proposal. Confirmation only updates this preview.', agree: 'Agree to proposal', approved: 'You confirmed',
  approvedToast: 'Your preview confirmation is recorded. Other participants still need to decide.',
  inProgress: 'In progress', toDo: 'To do', done: 'Done', taskHint: 'Small steps toward a shared goal.',
  planTitle: 'V1 experience improvements', progress: 'Progress', completed: 'completed',
  taskOne: 'Prepare the interface proposal', taskTwo: 'Review the design direction', taskThree: 'Implement shared component styles',
  taskFour: 'Review the desktop experience', taskDetail: 'Task details', taskDetailHint: 'Linked to the discussion and the experience improvement plan.',
  assignee: 'Assignee', reviewer: 'Reviewer', due: 'Due date', dueValue: 'October 10',
  taskCriteria: 'Create a reviewable proposal covering sign-in, the project list and the project workspace.',
  acceptance: 'Acceptance criteria', relatedDiscussion: 'Related discussion', openDiscussion: 'Back to discussion',
  filesHint: 'Shared context and materials for the team.', fileOne: 'Interface proposal.md', fileTwo: 'Interaction checklist.md',
  updatedBy: 'Updated today · Xiaolin', openFile: 'View file',
  fileContent: 'Use warm neutral surfaces, muted greens and clear action hierarchy. Simplify sign-in, clarify project entry, and preserve the connection between discussions, files and work.',
  decisionHint: 'Items that need your explicit decision.', allDone: 'Nothing waiting for review',
  allDoneHint: 'New proposals and handoff requests will appear here.', receivedHandoff: 'Delivery materials handoff',
  handoffHint: 'Chen submitted delivery materials. Review them before accepting.', receive: 'Accept handoff',
  handoffAccepted: 'Sample handoff accepted. Final task acceptance is a separate decision.',
  hidePanel: 'Hide work panel', showPanel: 'Show work panel', expandPanel: 'Expand work panel', restorePanel: 'Restore columns',
  noDiscussions: 'No matching discussions', you: 'You', newProjectWelcome: 'Your project is ready',
  newProjectHint: 'Start a conversation. Connect your goals, work and team.',
  footer: 'Judex · Good work, together', recentlyViewed: 'Recently opened',
};
