import {useState} from "react";
import {Card,Tabs,TextField,Input} from "@heroui/react";
import {ArrowUpRight,Check,Folder,GitBranch,MessageCircle,Plus,Search,Settings,Users} from "lucide-react";
import {UIOption,UISelect} from "../src/components/ui/FormControls";
import {Button,Empty,PageTitle,PersonAvatar,Status} from "./ui";
import {usePreview} from "./context";
import {ownDecisions,planTasks,type Decision,type Handoff,type Plan} from "./model";
function countDecisions(p:ReturnType<typeof usePreview>,pid:string){return ownDecisions(p.state,pid).length+p.state.handoffs.filter(h=>h.projectId===pid&&h.receiverId===p.state.userId&&h.status==="pending").length;}
export function ProjectList(){
 const p=usePreview(),[search,setSearch]=useState(""),[filter,setFilter]=useState("all");
 const projects=p.state.projects.filter(v=>v.memberIds.includes(p.state.userId)&&p.text(v.title).toLowerCase().includes(search.toLowerCase())&&(filter==="all"||filter==="owned"&&v.ownerId===p.state.userId||filter==="joined"&&v.ownerId!==p.state.userId));
 return <main className="judex-co-main"><PageTitle title={p.t("cpProjects")} hint={p.t("cpProjectsHint")} actions={<Button variant="primary" onPress={()=>p.setModal({kind:"project"})}><Plus/>{p.t("cpCreateProject")}</Button>}/>
  <div className="judex-co-toolbar"><div className="judex-co-actions">{["all","owned","joined"].map(k=><Button key={k} size="sm" aria-pressed={filter===k} onPress={()=>setFilter(k)}>{p.t(k==="all"?"cpAll":k==="owned"?"cpOwned":"cpJoined")}</Button>)}</div><TextField className="judex-co-search" aria-label={p.t("cpSearchProjects")} value={search} onChange={setSearch}><Search size={16}/><Input placeholder={p.t("cpSearchProjects")}/></TextField></div>
  <div className="judex-co-project-grid">{projects.map(project=><Card key={project.id} className="judex-co-project-card">
   <Button className="judex-co-card-hit" aria-label={p.t("cpOpen")+" · "+p.text(project.title)} data-testid={"co-project-"+project.id} onPress={()=>p.go({page:"hub",projectId:project.id,tab:"plans"})}/>
   <Card.Header><div className="judex-co-card-top"><span className="judex-co-card-mark"><Folder/></span><Status status={project.status}/></div><Card.Title>{p.text(project.title)}</Card.Title><Card.Description>{p.text(project.goal)}</Card.Description></Card.Header>
   <Card.Content><div className="judex-co-meta">{p.state.plans.filter(v=>v.projectId===project.id).length} {p.t("cpPlans")} · {project.memberIds.length} {p.t("cpMembers")}</div><div className="judex-co-card-summary"><span>{p.t("cpDecisions")}</span><strong>{countDecisions(p,project.id)}</strong></div></Card.Content>
   <Card.Footer className="judex-co-card-footer"><div className="judex-co-avatars">{project.memberIds.slice(0,3).map(who=><PersonAvatar key={who} name={p.person(who)} small/>)}</div><div className="judex-co-actions">{project.ownerId===p.state.userId&&<><Button size="sm" variant="outline" aria-label={p.t("cpInvite")+" · "+p.text(project.title)} onPress={()=>p.setModal({kind:"invite",projectId:project.id})}><Users size={15}/>{p.t("cpInvite")}</Button><Button size="sm" variant="outline" aria-label={p.t("cpSettings")+" · "+p.text(project.title)} onPress={()=>p.setModal({kind:"settings",projectId:project.id})}><Settings size={15}/>{p.t("cpSettings")}</Button></>}<Button size="sm" variant="primary" onPress={()=>p.go({page:"hub",projectId:project.id,tab:"plans"})}>{p.t("cpOpen")}<ArrowUpRight size={15}/></Button></div></Card.Footer>
  </Card>)}</div>{!projects.length&&<Empty>{p.t("cpNoDiscussions")}</Empty>}
 </main>;
}
export function PlanCard({plan}:{plan:Plan}){
 const p=usePreview(),tasks=planTasks(p.state,plan.id),done=tasks.filter(t=>t.status==="accepted").length;
 return <Card className="judex-co-plan-card">
  <Button className="judex-co-card-hit" data-testid={"co-plan-"+plan.id} aria-label={p.t("cpTaskRoute")+" · "+p.text(plan.title)} onPress={()=>p.go({page:"route",projectId:plan.projectId,planId:plan.id})}/>
  <Card.Header><div className="judex-co-card-top"><span className="judex-co-card-mark"><GitBranch/></span><Status status={plan.status}/></div><Card.Title>{p.text(plan.title)}</Card.Title><Card.Description>{p.text(plan.goal)}</Card.Description></Card.Header>
  <Card.Content><div className="judex-co-meta">{p.t("cpOwner")} · {p.person(plan.ownerId)}</div><div className="judex-co-progress"><span style={{width:tasks.length?done/tasks.length*100+"%":"0%"}}/></div><div className="judex-co-card-top judex-co-meta"><span>{done} / {tasks.length} {p.t("cpAcceptedTasks")}</span><span>{tasks.length} {p.t("cpTasks")}</span></div>{tasks.some(t=>t.makerId===p.state.userId&&["ready","working","rework"].includes(t.status))&&<div className="judex-co-meta">{p.t("cpMyPending")} · {tasks.filter(t=>t.makerId===p.state.userId&&["ready","working","rework"].includes(t.status)).length}</div>}{plan.status==="accepted"&&tasks.some(t=>t.status==="rework")&&<p className="judex-co-warn">{p.t("cpPlanAcceptedNotice")}</p>}</Card.Content>
  <Card.Footer className="judex-co-card-footer"><Button size="sm" variant="outline" data-testid={"co-preview-route-"+plan.id} onPress={()=>p.setModal({kind:"route",planId:plan.id})}><GitBranch size={15}/>{p.t("cpPreviewRoute")}</Button><Button size="sm" variant="primary" data-testid={"co-plan-discuss-"+plan.id} onPress={()=>p.planChat(plan)}><MessageCircle size={15}/>{p.t("cpDiscuss")}</Button></Card.Footer>
 </Card>;
}
export function ProjectHub(){
 const p=usePreview(),project=p.state.projects.find(v=>v.id===p.route.projectId)!,[search,setSearch]=useState(""),[status,setStatus]=useState("all");
 const tab=p.route.tab??"plans",plans=p.state.plans.filter(v=>v.projectId===project.id&&p.text(v.title).toLowerCase().includes(search.toLowerCase())&&(status==="all"||status==="mine"&&(v.ownerId===p.state.userId||planTasks(p.state,v.id).some(t=>t.makerId===p.state.userId))||v.status===status));
 const tabs=[["plans","cpPlans"],["decisions","cpDecisions"],["handoffs","cpHandoffs"],["materials","cpMaterials"]] as const;
 return <main className="judex-co-main"><PageTitle title={p.text(project.title)} hint={p.t("cpHubHint")} back={{label:p.t("cpBackProjects"),run:()=>p.go({page:"projects",projectId:project.id})}} actions={<>{project.ownerId===p.state.userId&&<Button variant="outline" size="sm" onPress={()=>p.setModal({kind:"settings",projectId:project.id})}><Settings size={16}/>{p.t("cpSettings")}</Button>}<Button variant="primary" onPress={()=>p.setModal({kind:"arrangement",sourceTopicId:p.state.plans.find(v=>v.projectId===project.id)?.mainTopicId??""})}><Plus size={16}/>{p.t("cpNewPlan")}</Button></>}/>
  <Tabs selectedKey={tab} onSelectionChange={k=>p.go({page:"hub",projectId:project.id,tab:String(k)})} className="judex-co-hub-tabs"><Tabs.ListContainer><Tabs.List aria-label={p.t("cpProjectHub")}>{tabs.map(([id,key])=><Tabs.Tab key={id} id={id} data-testid={"co-tab-"+id}>{p.t(key)}{id==="decisions"&&countDecisions(p,project.id)>0&&<span className="judex-co-tab-count">{countDecisions(p,project.id)}</span>}<Tabs.Indicator/></Tabs.Tab>)}</Tabs.List></Tabs.ListContainer><Tabs.Panel id={tab}>
   {tab==="plans"?<><div className="judex-co-toolbar"><div className="judex-co-actions">{[["all","cpAll"],["mine","cpMyWork"],["active","cpWorking"],["draft","cpDraft"],["accepted","cpAccepted"]].map(([k,key])=><Button size="sm" key={k} aria-pressed={status===k} onPress={()=>setStatus(k)}>{p.t(key as "cpAll")}</Button>)}</div><TextField className="judex-co-search" value={search} onChange={setSearch} aria-label={p.t("cpSearchPlans")}><Search size={16}/><Input placeholder={p.t("cpSearchPlans")}/></TextField></div><div className="judex-co-plan-grid">{plans.map(plan=><PlanCard key={plan.id} plan={plan}/>)}</div></>:tab==="decisions"?<DecisionBoard/>:tab==="handoffs"?<HandoffBoard/>:<MaterialBoard/>}
  </Tabs.Panel></Tabs>
 </main>;
}
export function DecisionCard({decision}:{decision:Decision}){
 const p=usePreview(),plan=p.state.plans.find(v=>v.id===decision.planId)!,task=p.state.tasks.find(v=>v.id===decision.taskId);
 return <Card className="judex-co-action-card" data-testid={"co-decision-"+decision.id}><Card.Header><div className="judex-co-card-top"><span className="judex-co-tag">{p.t(decision.kind==="arrangement"?"cpArrangement":decision.kind==="task"?"cpTaskAcceptance":"cpPlanAcceptance")}</span><span className="judex-co-meta">{p.t("cpReviewVersion")} {decision.version}</span></div><Card.Title>{p.text(decision.title)}</Card.Title><Card.Description>{p.text(decision.description)}</Card.Description></Card.Header><Card.Content><div className="judex-co-meta">{p.text(plan.title)} · {p.t(task?"cpReviewer":"cpOwner")} {p.person(task?.reviewerId??plan.ownerId)}</div><div className="judex-co-meta">{p.t("cpPendingWho")} · {decision.actors.filter(v=>!decision.approvedBy.includes(v)).map(p.person).join(" · ")}</div></Card.Content><Card.Footer className="judex-co-card-footer"><Button variant="outline" size="sm" onPress={()=>p.planChat(plan)}><MessageCircle size={15}/>{p.t("cpReturnSource")}</Button><Button variant="primary" size="sm" onPress={()=>p.setModal({kind:"decision",decisionId:decision.id})}>{p.t("cpReview")}<ArrowUpRight size={15}/></Button></Card.Footer></Card>;
}
export function ReceiptCard({handoff}:{handoff:Handoff}){
 const p=usePreview(),source=p.state.tasks.find(t=>t.id===handoff.sourceTaskId)!,target=p.state.tasks.find(t=>t.id===handoff.targetTaskId)!;
 return <Card className="judex-co-action-card" data-testid={"co-handoff-"+handoff.id}><Card.Header><div className="judex-co-card-top"><span className="judex-co-tag">{p.t("cpHandoffItem")}</span><span className="judex-co-tag">{p.t(handoff.status==="accepted"?"cpReceived":handoff.status==="rejected"?"cpNeedsRevision":"cpWaitReceive")}</span></div><Card.Title>{p.text(source.title)} → {p.text(target.title)}</Card.Title><Card.Description>{p.t("cpReceiptHint")}</Card.Description></Card.Header><Card.Content><div className="judex-co-meta">{p.t("cpSender")} {p.person(handoff.senderId)} · {p.t("cpReceiver")} {p.person(handoff.receiverId)}</div><div className="judex-co-meta">{p.t("cpSentVersion")} {handoff.version}</div></Card.Content><Card.Footer className="judex-co-card-footer"><Button size="sm" variant="outline" onPress={()=>p.setModal({kind:"task",taskId:source.id})}>{p.t("cpOriginal")}</Button><Button size="sm" variant={handoff.receiverId===p.state.userId&&handoff.status==="pending"?"primary":"outline"} onPress={()=>p.setModal({kind:"receipt",handoffId:handoff.id})}>{p.t(handoff.receiverId===p.state.userId&&handoff.status==="pending"?"cpReview":"cpViewDetails")}</Button></Card.Footer></Card>;
}
export function DecisionBoard(){
 const p=usePreview(),[filter,setFilter]=useState("all"),items=ownDecisions(p.state,p.route.projectId).filter(d=>filter==="all"||d.kind===filter);
 const receipts=p.state.handoffs.filter(h=>h.projectId===p.route.projectId&&h.receiverId===p.state.userId&&h.status==="pending"&&(filter==="all"||filter==="receipt"));
 return <><div className="judex-co-toolbar"><UISelect value={filter} onChange={e=>setFilter(e.target.value)} aria-label={p.t("cpDecisionType")}><UIOption value="all">{p.t("cpAll")}</UIOption><UIOption value="arrangement">{p.t("cpArrangement")}</UIOption><UIOption value="task">{p.t("cpTaskAcceptance")}</UIOption><UIOption value="plan">{p.t("cpPlanAcceptance")}</UIOption><UIOption value="receipt">{p.t("cpReceipt")}</UIOption></UISelect><span className="judex-co-meta">{p.t("cpNoPendingHint")}</span></div><div className="judex-co-plan-grid">{items.map(d=><DecisionCard key={d.id} decision={d}/>)}{receipts.map(h=><ReceiptCard key={h.id} handoff={h}/>)}</div>{!items.length&&!receipts.length&&<Empty><Check/><h3>{p.t("cpNoDecisions")}</h3><p>{p.t("cpNoPendingHint")}</p></Empty>}</>;
}
export function HandoffBoard(){
 const p=usePreview(),[filter,setFilter]=useState("all");
 const handoffs=p.state.handoffs.filter(h=>h.projectId===p.route.projectId&&(filter==="all"||filter==="receive"&&h.receiverId===p.state.userId&&h.status==="pending"||filter==="sent"&&h.senderId===p.state.userId&&h.status==="pending"||filter==="revise"&&h.senderId===p.state.userId&&h.status==="rejected"));
 const deliveries=p.state.tasks.filter(t=>t.projectId===p.route.projectId&&t.status==="delivered"&&(filter==="all"||filter==="sent"&&t.makerId===p.state.userId));
 return <><div className="judex-co-toolbar"><div className="judex-co-actions">{[["all","cpAll"],["receive","cpNeedsMe"],["sent","cpWaitOther"],["revise","cpNeedsRevision"]].map(([k,key])=><Button key={k} size="sm" aria-pressed={filter===k} onPress={()=>setFilter(k)}>{p.t(key as "cpAll")}</Button>)}</div><span className="judex-co-meta">{p.t("cpDeliveryExplanation")}</span></div><div className="judex-co-plan-grid">{handoffs.map(h=><ReceiptCard key={h.id} handoff={h}/>)}{deliveries.map(task=><Card key={task.id} className="judex-co-action-card"><Card.Header><div className="judex-co-card-top"><span className="judex-co-tag">{p.t("cpTaskDelivery")}</span><Status status={task.status}/></div><Card.Title>{p.text(task.title)}</Card.Title><Card.Description>{p.t("cpTaskAcceptanceHint")}</Card.Description></Card.Header><Card.Content><div className="judex-co-meta">{p.t("cpSender")} {p.person(task.makerId)} · {p.t("cpReviewer")} {p.person(task.reviewerId)}</div></Card.Content><Card.Footer className="judex-co-card-footer"><Button variant="outline" size="sm" onPress={()=>p.setModal({kind:"task",taskId:task.id})}>{p.t("cpViewDetails")}</Button><Button variant="primary" size="sm" onPress={()=>p.taskChat(task)}>{p.t("cpDiscuss")}</Button></Card.Footer></Card>)}</div>{!handoffs.length&&!deliveries.length&&<Empty>{p.t("cpNoDeliveries")}</Empty>}</>;
}
export function MaterialBoard(){
 const p=usePreview(),items=p.state.materials.filter(m=>m.projectId===p.route.projectId);
 return <div className="judex-co-plan-grid">{items.map(m=><Card key={m.id}><Card.Header><Card.Title>{m.name}</Card.Title><Card.Description>{p.t("cpFixedMaterial")} {m.version} · {p.person(m.authorId)}</Card.Description></Card.Header><Card.Footer><Button variant="outline" size="sm" onPress={()=>p.setModal({kind:"material",materialId:m.id})}>{p.t("cpViewDetails")}</Button></Card.Footer></Card>)}{!items.length&&<Empty>{p.t("cpNoMaterials")}</Empty>}</div>;
}
