import {useEffect,useRef,useState} from "react";
import {Dropdown,Label,Tabs,TextArea,TextField,Input} from "@heroui/react";
import {ArrowLeft,ArrowUp,GitFork,Link,Maximize2,MessageCircle,Minimize2,MoreHorizontal,PanelRightClose,PanelRightOpen,Plus,Search,Sparkles,X} from "lucide-react";
import {Button,Empty,PersonAvatar,Status} from "./ui";
import {UIOption,UISelect} from "../src/components/ui/FormControls";
import {usePreview} from "./context";
import {history,linkedPlans,topicsInScope,type Topic} from "./model";
import {PlanRecords,TaskRecords,TaskSummary} from "./records";
import {DecisionCard} from "./boards";
function SuggestionCard({suggestionId}:{suggestionId:string}){
 const p=usePreview(),s=p.state.suggestions.find(v=>v.id===suggestionId)!,task=p.state.tasks.find(t=>t.id===s.taskId)!;
 const goMain=()=>{const result=p.perform({kind:"suggestion",suggestionId:s.id,mode:"main"});if(result.id)p.topicChat(p.state.topics.find(t=>t.id===result.id)!,{planId:task.planId});};
 return <article className="judex-co-suggestion"><div className="judex-co-meta"><Sparkles size={15}/>{p.t("cpSuggestion")} · {p.t("cpSimulated")}</div><h3>{p.text(s.title)}</h3><p>{p.text(s.reason)}</p><div className="judex-co-actions"><Button size="sm" variant="primary" onPress={()=>p.setModal({kind:"suggestion",suggestionId:s.id,mode:"create"})}>{p.t("cpSeparate")}</Button><Button size="sm" variant="outline" onPress={goMain}>{p.t("cpContinue")}</Button><Button size="sm" variant="outline" onPress={()=>p.setModal({kind:"suggestion",suggestionId:s.id,mode:"existing"})}>{p.t("cpExisting")}</Button></div><Button size="sm" onPress={()=>p.setModal({kind:"record",recordId:s.recordId})}>{p.t("cpOriginal")}</Button></article>;
}
function Conversation({topic,onTaskRecords}:{topic:Topic;onTaskRecords:(taskId:string)=>void}){
 const p=usePreview(),draftKey="judex.cooperation.draft."+p.state.userId+":"+topic.id,readingKey="judex.cooperation.reading."+p.state.userId+":"+topic.id;
 const [body,setBody]=useState(()=>sessionStorage.getItem(draftKey)??""),[taskContext,setTaskContext]=useState(()=>sessionStorage.getItem(draftKey+".task")??p.route.taskId??"");
 const area=useRef<HTMLDivElement>(null),messages=history(p.state,topic),parent=p.state.topics.find(t=>t.id===topic.parentId);
 useEffect(()=>{sessionStorage.setItem(draftKey,body);sessionStorage.setItem(draftKey+".task",taskContext);},[body,taskContext,draftKey]);
 useEffect(()=>{const el=area.current;if(!el)return;el.scrollTop=Number(sessionStorage.getItem(readingKey)??0);const save=()=>sessionStorage.setItem(readingKey,String(el.scrollTop));el.addEventListener("scroll",save);return()=>{save();el.removeEventListener("scroll",save);};},[readingKey]);
 useEffect(()=>{if(p.route.messageSeq)area.current?.querySelector('[data-co-seq="'+p.route.messageSeq+'"]')?.scrollIntoView({block:"center"});},[p.route.messageSeq,messages.length]);
 const send=()=>{const result=p.perform({kind:"message",topicId:topic.id,body,taskId:taskContext||undefined});if(result.state){setBody("");requestAnimationFrame(()=>{const el=area.current;if(el)el.scrollTop=el.scrollHeight;});}};
 const taskIds=p.route.taskId?[p.route.taskId]:p.state.tasks.filter(t=>topic.taskIds.length?topic.taskIds.includes(t.id):linkedPlans(p.state,topic).includes(t.planId)).map(t=>t.id);
 const titleKey=topic.kind==="plan-main"?"cpMainPlan":topic.kind==="task-main"?"cpMainTask":"cpSpecial";
 const proposals=p.state.decisions.filter(d=>d.status==="pending"&&(d.sourceTopicId===topic.id||topic.planIds.includes(d.planId)&&d.kind==="arrangement"));
 const suggestions=p.state.suggestions.filter(s=>s.status==="pending"&&(p.route.taskId?s.taskId===p.route.taskId:p.state.tasks.find(t=>t.id===s.taskId)?.planId===p.route.planId));
 return <section className="judex-co-conversation"><div className="judex-co-conversation-title"><div><h2>{p.text(topic.title)}</h2><span className="judex-co-meta">{p.t(titleKey)}</span></div><div className="judex-co-actions"><Button size="sm" variant="ghost" aria-label={p.t("cpEditLinks")} title={p.t("cpEditLinks")} onPress={()=>p.setModal({kind:"topic",topicId:topic.id})}><Link size={16}/></Button><Dropdown><Button size="sm" isIconOnly aria-label={p.t("cpViewDetails")}><MoreHorizontal size={17}/></Button><Dropdown.Popover><Dropdown.Menu onAction={key=>{if(key==="fork")p.setModal({kind:"topic",parentId:topic.id,afterSeq:messages.at(-1)?.seq??0});else p.setModal({kind:"arrangement",sourceTopicId:topic.id});}}><Dropdown.Item id="fork" textValue={p.t("cpFork")}><GitFork/><Label>{p.t("cpFork")}</Label></Dropdown.Item><Dropdown.Item id="arrange" textValue={p.t("cpNewArrangement")}><Label>{p.t("cpNewArrangement")}</Label></Dropdown.Item></Dropdown.Menu></Dropdown.Popover></Dropdown></div></div>
  <div className="judex-co-topic-links">{linkedPlans(p.state,topic).map(pid=><Button key={pid} size="sm" onPress={()=>p.go({page:"route",projectId:topic.projectId,planId:pid})}>{p.text(p.state.plans.find(v=>v.id===pid)?.title??"")}</Button>)}{topic.taskIds.map(tid=><Button key={tid} size="sm" onPress={()=>onTaskRecords(tid)}>{p.text(p.state.tasks.find(v=>v.id===tid)?.title??"")}</Button>)}{linkedPlans(p.state,topic).length>1&&<span className="judex-co-meta">{p.t("cpSameTopic")}</span>}</div>
  {parent&&<div className="judex-co-source"><span>{p.t("cpSource")}</span><Button size="sm" onPress={()=>p.topicChat(parent,{planId:parent.planIds[0],messageSeq:topic.forkAfterSeq})}>{p.text(parent.title)} · {topic.forkAfterSeq}</Button></div>}
  <div className="judex-co-thread" ref={area} data-testid="co-thread">
   {!messages.length&&<Empty><Sparkles/><h3>{p.t("cpTaskDiscussion")}</h3><p>{p.t("cpComposeHint")}</p></Empty>}
   {messages.map((m,i)=><div key={m.id}>{topic.parentId&&!m.inherited&&(i===0||messages[i-1].inherited)&&<div className="judex-co-branch-start">{p.t("cpBranchStart")}</div>}<article data-co-seq={m.seq} className={"judex-co-message"+(m.inherited?" judex-co-inherited":"")+(p.route.messageSeq===m.seq?" judex-co-message-focus":"")}><PersonAvatar name={p.person(m.authorId)} small/><div className="judex-co-message-content"><div className="judex-co-message-by"><strong>{p.person(m.authorId)}</strong><span>{m.at}</span>{m.kind==="ai"&&<span>{p.t("cpSimulated")}</span>}{m.inherited&&<span>{p.t("cpInherited")}</span>}<Dropdown><Button size="sm" isIconOnly aria-label={p.t("cpForkHere")+" · "+m.seq}><MoreHorizontal size={14}/></Button><Dropdown.Popover><Dropdown.Menu onAction={()=>p.setModal({kind:"topic",parentId:topic.id,afterSeq:m.seq})}><Dropdown.Item id="fork" textValue={p.t("cpForkHere")}><Label>{p.t("cpForkHere")}</Label></Dropdown.Item></Dropdown.Menu></Dropdown.Popover></Dropdown></div><p className={m.kind==="ai"?"judex-co-ai-body":""}>{p.text(m.text)}</p>{m.recordId&&<Button size="sm" onPress={()=>p.setModal({kind:"record",recordId:m.recordId!})}>{p.t("cpOriginal")}</Button>}</div></article></div>)}
   {topic.recordIds.map(rid=><Button key={rid} size="sm" className="judex-co-source-link" onPress={()=>p.setModal({kind:"record",recordId:rid})}>{p.t("cpOriginal")} · {p.text(p.state.tasks.find(t=>t.id===p.state.activities.find(r=>r.id===rid)?.taskId)?.title??"")}</Button>)}
   {topic.kind==="plan-main"&&p.state.tasks.filter(t=>t.planId===p.route.planId).map(task=><TaskSummary key={task.id} task={task} onRecords={onTaskRecords}/>)}
   {proposals.map(d=><DecisionCard key={d.id} decision={d}/>)}{suggestions.map(s=><SuggestionCard key={s.id} suggestionId={s.id}/>)}
  </div>
  <div className="judex-co-composer"><div className="judex-co-compose-scope"><span>{p.t("cpTaskContext")}</span><UISelect data-testid="co-compose-task" value={taskContext} onChange={e=>setTaskContext(e.target.value)}><UIOption value="">{p.t("cpWholeScope")}</UIOption>{taskIds.map(id=><UIOption key={id} value={id}>{p.text(p.state.tasks.find(t=>t.id===id)?.title??"")}</UIOption>)}</UISelect></div><TextArea aria-label={p.t("cpMessagePlaceholder")} data-testid="co-message" placeholder={p.t("cpMessagePlaceholder")} value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing&&body.trim()){e.preventDefault();send();}}}/><div className="judex-co-compose-footer"><small>{p.t("cpComposeHint")}</small><Button size="sm" variant="primary" disabled={!body.trim()} data-testid="co-send" onPress={send}>{p.t("cpSend")}<ArrowUp size={15}/></Button></div></div>
 </section>;
}
export function ChatView(){
 const p=usePreview(),[search,setSearch]=useState(""),[right,setRight]=useState(true),[expanded,setExpanded]=useState(false),[leftWidth,setLeftWidth]=useState(240),[rightWidth,setRightWidth]=useState(340);
 const current=p.state.topics.find(t=>t.id===p.route.topicId)!,task=p.state.tasks.find(t=>t.id===p.route.taskId),plan=p.state.plans.find(v=>v.id===(p.route.planId??task?.planId));
 const key=p.route.projectId+":"+(task?.id??plan?.id??"")+":"+p.state.userId;
 const topics=topicsInScope(p.state,p.route).sort((a,b)=>Number(b.kind!=="special")-Number(a.kind!=="special"));
 const [stored,setStored]=useState<{key:string;tabs:string[];info:string[];activeInfo:string}>(()=>({key,tabs:current?[current.id]:[],info:task?[task.id]:["plan"],activeInfo:task?.id??"plan"}));
 const model=stored.key===key?stored:{key,tabs:current?[current.id]:[],info:task?[task.id]:["plan"],activeInfo:task?.id??"plan"};
 const tabIds=[...new Set([...model.tabs,current?.id])].filter((v):v is string=>!!v&&p.state.topics.some(t=>t.id===v));
 const infoTask=p.state.tasks.find(t=>t.id===model.activeInfo);
 const showInfo=(taskId:string)=>{setStored({...model,info:[...new Set([...model.info,taskId])],activeInfo:taskId});setRight(true);};
 const open=(topic:Topic)=>{setExpanded(false);setStored({...model,tabs:[...new Set([...tabIds,topic.id])]});p.topicChat(topic);};
 const drag=(side:"left"|"right",e:React.PointerEvent<HTMLDivElement>)=>{
  e.currentTarget.setPointerCapture(e.pointerId);const start=e.clientX,initial=side==="left"?leftWidth:rightWidth;
  const move=(event:PointerEvent)=>{const delta=(event.clientX-start)*(side==="left"?1:-1);const value=Math.max(side==="left"?210:280,Math.min(side==="left"?310:480,initial+delta));side==="left"?setLeftWidth(value):setRightWidth(value);};
  const end=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",end);};window.addEventListener("pointermove",move);window.addEventListener("pointerup",end);
 };
 if(!current||!plan)return null;
 return <div className={"judex-co-chat"+(expanded?" judex-co-chat-expanded":"")+(!right?" judex-co-chat-focused":"")} style={{"--co-left":leftWidth+"px","--co-right":rightWidth+"px"} as React.CSSProperties}>
  <aside className="judex-co-chat-sidebar"><Button size="sm" className="judex-co-back" onPress={()=>p.go({page:"hub",projectId:plan.projectId,tab:"plans"})}><ArrowLeft size={15}/>{p.t("cpBackHub")}</Button><div className="judex-co-scope-heading"><span>{p.t(task?"cpTaskDiscussion":"cpPlanDiscussion")}</span><h2>{p.text(task?.title??plan.title)}</h2>{task&&<Button size="sm" onPress={()=>p.go({page:"route",projectId:plan.projectId,planId:plan.id})}>{p.text(plan.title)}</Button>}</div><Button variant="primary" className="judex-co-new-topic" data-testid="co-new-topic" onPress={()=>p.setModal({kind:"topic"})}><Plus size={15}/>{p.t("cpNewDiscussion")}</Button><TextField className="judex-co-chat-search" value={search} onChange={setSearch} aria-label={p.t("cpSearchDiscussions")}><Search size={14}/><Input placeholder={p.t("cpSearchDiscussions")}/></TextField><div className="judex-co-sidebar-label">{p.t("cpRelatedDiscussions")}<span>{topics.length}</span></div><nav>{topics.filter(t=>p.text(t.title).toLowerCase().includes(search.toLowerCase())).map(topic=><Button key={topic.id} data-testid={"co-topic-"+topic.id} aria-pressed={topic.id===current.id} className="judex-co-topic-row" onPress={()=>open(topic)}><MessageCircle size={16}/><span><strong>{p.text(topic.title)}</strong><small>{p.t(topic.kind==="plan-main"?"cpMainPlan":topic.kind==="task-main"?"cpMainTask":"cpSpecial")}{linkedPlans(p.state,topic).length>1?" · "+linkedPlans(p.state,topic).length+" "+p.t("cpPlans"):""}</small></span></Button>)}</nav><footer className="judex-co-sidebar-context"><Button size="sm" variant="outline" onPress={()=>p.go({page:"route",projectId:plan.projectId,planId:plan.id})}>{p.t("cpTaskRoute")}</Button><span className="judex-co-meta">{p.t("cpSameTopic")}</span></footer></aside>
  <div className="judex-co-resize" role="separator" aria-label="Resize discussions" onPointerDown={e=>drag("left",e)}/>
  <main className="judex-co-chat-main" hidden={expanded}><Tabs className="judex-co-chat-tabs" selectedKey={current.id} onSelectionChange={k=>open(p.state.topics.find(t=>t.id===k)!)}><div className="judex-co-tabbar"><Tabs.ListContainer><Tabs.List aria-label={p.t("cpRelatedDiscussions")}>{tabIds.map(tid=>{const topic=p.state.topics.find(t=>t.id===tid)!;return <Tabs.Tab key={tid} id={tid}>{p.text(topic.title)}<Tabs.Indicator/></Tabs.Tab>;})}</Tabs.List></Tabs.ListContainer><Button size="sm" isIconOnly aria-label={p.t("cpInfo")} onPress={()=>setRight(!right)}>{right?<PanelRightClose size={17}/>:<PanelRightOpen size={17}/>}</Button></div><Tabs.Panel id={current.id}><Conversation key={current.id+":"+p.state.userId} topic={current} onTaskRecords={showInfo}/></Tabs.Panel></Tabs></main>
  {right&&!expanded&&<div className="judex-co-resize" role="separator" aria-label="Resize records" onPointerDown={e=>drag("right",e)}/>}
  {right&&<aside className="judex-co-chat-inspector"><Tabs className="judex-co-info-tabs" selectedKey={model.activeInfo} onSelectionChange={k=>setStored({...model,activeInfo:String(k)})}><div className="judex-co-tabbar"><Tabs.ListContainer><Tabs.List aria-label={p.t("cpInfo")}>{model.info.map(i=><Tabs.Tab key={i} id={i}>{i==="plan"?p.t("cpInfo"):p.text(p.state.tasks.find(t=>t.id===i)?.title??"")}<Tabs.Indicator/></Tabs.Tab>)}</Tabs.List></Tabs.ListContainer><div><Button size="sm" isIconOnly aria-label={p.t(expanded?"cpRestore":"cpFullscreen")} onPress={()=>setExpanded(!expanded)}>{expanded?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</Button><Button size="sm" isIconOnly aria-label={p.t("cpClose")} onPress={()=>{setRight(false);setExpanded(false);}}><X size={17}/></Button></div></div><Tabs.Panel id={model.activeInfo}>{infoTask?<TaskRecords key={infoTask.id} task={infoTask}/>:<PlanRecords planId={plan.id}/>}</Tabs.Panel></Tabs></aside>}
 </div>;
}
