import {useState} from "react";
import {Card} from "@heroui/react";
import {FileText,MessageCircle} from "lucide-react";
import {Button,Empty,Status} from "./ui";
import {usePreview} from "./context";
import {ready,type Activity,type Task} from "./model";
export function Record({record,full=false}:{record:Activity;full?:boolean}){
 const p=usePreview();
 return <article className="judex-co-record"><div className="judex-co-card-top"><strong>{p.t(record.kind==="progress"?"cpProgress":record.kind==="delivery"?"cpDelivery":record.kind==="question"?"cpQuestion":"cpReply")}</strong><span className="judex-co-meta">{record.at}</span></div><div className="judex-co-meta">{p.person(record.actorId)} · {p.t(record.source==="cli"?"cpLocal":"cpWeb")}</div><p>{p.text(record.text)}</p>{record.materialIds.map(mid=>{const m=p.state.materials.find(v=>v.id===mid);return m&&<Button size="sm" key={mid} className="judex-co-material-tag" onPress={()=>p.setModal({kind:"material",materialId:mid})}><FileText size={13}/>{m.name} · v{m.version}</Button>;})}<div className="judex-co-analysis"><strong>{p.t("cpAnalysis")}</strong><p>{p.text(record.analysis)}</p></div><div className="judex-co-actions">{!full&&<Button size="sm" onPress={()=>p.setModal({kind:"record",recordId:record.id})}>{p.t("cpOriginal")}</Button>}{record.topicIds.map(tid=>{const topic=p.state.topics.find(t=>t.id===tid);return topic&&<Button variant="outline" size="sm" key={tid} onPress={()=>p.topicChat(topic,{taskId:record.taskId})}><MessageCircle size={13}/>{p.text(topic.title)}</Button>;})}</div></article>;
}
export function TaskRecords({task}:{task:Task}){
 const p=usePreview(),[tab,setTab]=useState("records"),[older,setOlder]=useState(false),records=p.state.activities.filter(r=>r.taskId===task.id).slice().reverse(),plan=p.state.plans.find(v=>v.id===task.planId)!,flow=p.state.flows.find(v=>v.id===plan.workflowId),node=flow?.nodes.find(n=>n.id===task.nodeId);
 const own=task.makerId===p.state.userId;
 return <div className="judex-co-task-records">
  <div className="judex-co-inner-tabs"><Button size="sm" aria-pressed={tab==="records"} onPress={()=>setTab("records")}>{p.t("cpRecords")}</Button><Button size="sm" aria-pressed={tab==="flow"} onPress={()=>setTab("flow")}>{p.t("cpWorkflow")}</Button></div>
  <div className="judex-co-inspector-body"><div className="judex-co-card-top"><h3>{p.text(task.title)}</h3><Status status={task.status}/></div><div className="judex-co-meta">{p.text(plan.title)} · {p.person(task.makerId)} · {p.text(p.state.positions.find(v=>v.id===task.positionId)?.name??"")}</div>
   {tab==="records"?<><p>{p.text(task.goal)}</p><div className="judex-co-criteria"><strong>{p.t("cpCriteria")}</strong>{task.criteria.map((v,i)=><p key={i}><span>✓</span>{p.text(v)}</p>)}</div><div className="judex-co-meta">{p.t("cpReviewer")} · {p.person(task.reviewerId)}</div>
    <div className="judex-co-actions">{own&&["ready","rework"].includes(task.status)&&<Button size="sm" variant="outline" disabled={!ready(p.state,task)} onPress={()=>p.perform({kind:"start",taskId:task.id})}>{p.t("cpStart")}</Button>}<Button size="sm" variant="outline" disabled={!own||!["working","rework"].includes(task.status)} onPress={()=>p.setModal({kind:"report",taskId:task.id,recordKind:"progress"})}>{p.t("cpProgress")}</Button><Button size="sm" variant="outline" disabled={!own||!["working","ready","rework"].includes(task.status)||!ready(p.state,task)} onPress={()=>p.setModal({kind:"report",taskId:task.id,recordKind:"delivery"})}>{p.t("cpDelivery")}</Button><Button size="sm" variant="outline" onPress={()=>p.setModal({kind:"report",taskId:task.id,recordKind:"question"})}>{p.t("cpQuestion")}</Button></div>
    <Button size="sm" variant="primary" data-testid="co-local-report" onPress={()=>p.setModal({kind:"report",taskId:task.id,recordKind:own&&["working","rework"].includes(task.status)?"progress":"question",local:true})}>{p.t("cpSimulate")}</Button>
    <div className="judex-co-card-top"><h4>{p.t("cpRecords")}</h4><span className="judex-co-meta">{records.length} {p.t("cpReports")}</span></div>{(older?records:records.slice(0,3)).map(r=><Record key={r.id} record={r}/>)}{!records.length&&<Empty>{p.t("cpNoRecords")}</Empty>}{records.length>3&&!older&&<Button size="sm" variant="outline" onPress={()=>setOlder(true)}>{p.t("cpViewDetails")} · {records.length-3}</Button>}
    {task.status==="delivered"&&task.reviewerId===p.state.userId&&p.state.decisions.find(d=>d.taskId===task.id&&d.status==="pending")&&<Button variant="primary" onPress={()=>p.setModal({kind:"decision",decisionId:p.state.decisions.find(d=>d.taskId===task.id&&d.status==="pending")!.id})}>{p.t("cpAcceptTask")}</Button>}
    {task.status==="accepted"&&task.reviewerId===p.state.userId&&<Button size="sm" variant="outline" onPress={()=>{const reason=p.locale==="en"?"Further review requested":"需要进一步核对";p.perform({kind:"reopen",taskId:task.id,reason});}}>{p.t("cpReopen")}</Button>}
   </>:<><strong>{p.text(flow?.name??"")} · v{flow?.version}</strong><h4>{p.text(node?.name??"")}</h4><p>{p.text(node?.responsibility??"")}</p><div className="judex-co-meta">{p.t("cpWorkflowRole")} · {node?.positions.map(pid=>p.text(p.state.positions.find(v=>v.id===pid)?.name??"")).join(" · ")}</div><p className="judex-co-meta">{p.t("cpWorkflowHint")}</p><div className="judex-co-actions"><Button variant="outline" size="sm" onPress={()=>p.setModal({kind:"settings",projectId:task.projectId,section:"flows"})}>{p.t("cpSettings")}</Button></div></>}
  </div>
 </div>;
}
export function PlanRecords({planId}:{planId:string}){
 const p=usePreview(),plan=p.state.plans.find(v=>v.id===planId)!;
 return <div className="judex-co-inspector-body"><h3>{p.t("cpGoal")}</h3><p>{p.text(plan.goal)}</p><div className="judex-co-meta">{p.t("cpOwner")} · {p.person(plan.ownerId)}</div><strong>{p.t("cpCriteria")}</strong>{plan.criteria.map((v,i)=><p key={i}>{p.text(v)}</p>)}<Button variant="outline" size="sm" onPress={()=>p.setModal({kind:"route",planId:plan.id})}>{p.t("cpPreviewRoute")}</Button><Button variant="outline" size="sm" onPress={()=>p.go({page:"hub",projectId:plan.projectId,tab:"decisions"})}>{p.t("cpDecisions")}</Button>{plan.status==="draft"&&<div className="judex-co-meta">{p.t("cpDraftHint")}</div>}</div>;
}
export function TaskSummary({task,onRecords}:{task:Task;onRecords?:(taskId:string)=>void}){
 const p=usePreview(),records=p.state.activities.filter(r=>r.taskId===task.id),last=records.at(-1);
 return <Card className="judex-co-summary"><div className="judex-co-card-top"><strong>{p.text(task.title)}</strong><Status status={task.status}/></div><span className="judex-co-meta">{records.length} {p.t("cpReports")}</span><p className="judex-co-summary-text">{last?p.text(last.text):p.text(task.goal)}</p><div className="judex-co-actions"><Button variant="outline" size="sm" onPress={()=>onRecords?onRecords(task.id):p.setModal({kind:"task",taskId:task.id})}>{p.t("cpRecords")}</Button><Button variant="outline" size="sm" onPress={()=>p.taskChat(task)}>{p.t("cpTaskDiscussion")}</Button></div></Card>;
}
