// split-api partitions generated Go declarations without changing their API.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func run() error {
	if len(os.Args) != 3 {
		return fmt.Errorf("usage: split-api source output-directory")
	}
	source, err := os.ReadFile(os.Args[1])
	if err != nil {
		return err
	}
	set := token.NewFileSet()
	file, err := parser.ParseFile(set, os.Args[1], source, parser.ParseComments)
	if err != nil {
		return err
	}
	imports := map[string]*ast.ImportSpec{}
	for _, item := range file.Imports {
		name := strings.TrimSuffix(filepath.Base(strings.Trim(item.Path.Value, "\"")), ".go")
		if item.Name != nil {
			name = item.Name.Name
		}
		imports[name] = item
	}
	var chunks [][]ast.Decl
	var current []ast.Decl
	size := 0
	for _, decl := range file.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.IMPORT {
			continue
		}
		var data bytes.Buffer
		if err = format.Node(&data, set, decl); err != nil {
			return err
		}
		lines := bytes.Count(data.Bytes(), []byte("\n")) + 2
		if lines > 1800 {
			return fmt.Errorf("single generated declaration exceeds line limit")
		}
		if size+lines > 1800 && len(current) > 0 {
			chunks = append(chunks, current)
			current = nil
			size = 0
		}
		current = append(current, decl)
		size += lines
	}
	if len(current) > 0 {
		chunks = append(chunks, current)
	}
	dir := os.Args[2]
	if err = os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	old, err := filepath.Glob(filepath.Join(dir, "types*.gen.go"))
	if err != nil {
		return err
	}
	for _, path := range old {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if !bytes.Contains(data, []byte("Code generated")) {
			return fmt.Errorf("refusing to replace non-generated file %s", path)
		}
		if err = os.Remove(path); err != nil {
			return err
		}
	}
	for i, decls := range chunks {
		used := map[string]bool{}
		for _, decl := range decls {
			ast.Inspect(decl, func(node ast.Node) bool {
				if sel, ok := node.(*ast.SelectorExpr); ok {
					if id, ok := sel.X.(*ast.Ident); ok {
						used[id.Name] = true
					}
				}
				return true
			})
		}
		var out bytes.Buffer
		out.WriteString("// Code generated by api/generate-types.mjs; DO NOT EDIT.\npackage " + file.Name.Name + "\n")
		for _, item := range file.Imports {
			name := strings.Trim(filepath.Base(strings.Trim(item.Path.Value, "\"")), "\"")
			if item.Name != nil {
				name = item.Name.Name
			}
			if used[name] {
				out.WriteString("import ")
				if item.Name != nil {
					out.WriteString(item.Name.Name + " ")
				}
				out.WriteString(item.Path.Value + "\n")
			}
		}
		for _, decl := range decls {
			out.WriteString("\n")
			if err = format.Node(&out, set, decl); err != nil {
				return err
			}
			out.WriteString("\n")
		}
		formatted, err := format.Source(out.Bytes())
		if err != nil {
			return err
		}
		if bytes.Count(formatted, []byte("\n")) > 2000 {
			return fmt.Errorf("generated chunk too long")
		}
		if err = os.WriteFile(filepath.Join(dir, "types_"+strconv.Itoa(i)+".gen.go"), formatted, 0644); err != nil {
			return err
		}
	}
	return nil
}
