import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Check,Lock,RotateCcw} from 'lucide-react';
import {UIDialog} from '../../components/ui/Presentation';
import {Button} from '../../components/ui/Button';
import {FormField,UIInput,UITextArea,UISelect,UIOption,UICheckbox,UIDisclosure,UIWarning} from '../../components/ui/FormControls';
import {request} from '../../lib/api/client';
import {useWork} from './store';
import {useWorkspaceDraft} from '../chat/useWorkspaceDraft';
import type {Plan,Task,Requirement} from './types';
import type {DiscardReview,ExecutionReview,ExceptionWaiver} from './runtimeTypes';
import {demoDiscardReview,demoExecutionReview} from './demoRuntime';
import {uid} from './seed';
import {workCapabilities} from './runtime';
export type WorkMutation={action:'edit'|'delete'|'skip'|'restore';kind:'task'|'plan';id:string};
export function WorkMutationDialog({mutation,onClose}:{mutation:WorkMutation;onClose:()=>void}){
 const p=useWork(),item=(mutation.kind==='task'?p.state.tasks:p.state.plans).find(v=>v.id===mutation.id);if(!item)return null;
 return mutation.action==='edit'?<EditWork item={item} kind={mutation.kind} onClose={onClose}/>:<ConfirmWork item={item} mutation={mutation} onClose={onClose}/>;
}
function EditWork({item,kind,onClose}:{item:Task|Plan;kind:'task'|'plan';onClose:()=>void}){
 const p=useWork(),task=kind==='task'?item as Task:undefined,plan=kind==='plan'?item as Plan:undefined,status=item.businessStatus??item.status,directDraft=status==='draft'&&workCapabilities(p.state,item).editDraft;
 const initial={version:item.revision??1,title:p.text(item.title),description:p.text(task?.expected??plan!.goal),criteria:item.criteria.map(p.text).join('\n'),owner:plan?.ownerSeatId??'',reviewer:task?.reviewerSeatId??'',participants:task?.seatIds??[],requirements:task?.requirements.filter(r=>!r.inheritedFrom&&!p.text(r.label).startsWith('workflow:')).map(({id,at,kind,ref,hard,label})=>({id,at,kind,ref,hard,label}))??[]};
 const [draft,setDraft]=useWorkspaceDraft('work-edit:'+kind+':'+item.id,initial,'work-edit-v1:'+kind+':'+item.id),[busy,setBusy]=useState(false),[compare,setCompare]=useState(false),[failed,setFailed]=useState('');
 const set=(patch:Partial<typeof draft>)=>setDraft(v=>({...v,...patch}));
 const stale=(item.revision??1)!==draft.version;
 const seats=p.state.seats.filter(s=>(!s.status||s.status==='active')&&p.state.positions.some(v=>v.projectId===item.projectId&&v.id===s.positionId));
 const label=(id:string)=>{const s=p.state.seats.find(v=>v.id===id);return (s?.person??id)+' · '+p.text(p.state.positions.find(v=>v.id===s?.positionId)?.name??'');};
 const fields=()=>{const out:Record<string,unknown>={};if(draft.title!==initial.title)out.title=draft.title.trim();if(draft.description!==initial.description)out[kind==='task'?'expectedOutput':'goal']=draft.description;if(draft.criteria!==initial.criteria)out.acceptanceCriteria=draft.criteria;if(kind==='plan'&&draft.owner!==initial.owner)out.ownerIdentityId=draft.owner;if(kind==='task'){
  if(draft.reviewer!==initial.reviewer)out.reviewerIdentityId=draft.reviewer;if(JSON.stringify(draft.participants)!==JSON.stringify(initial.participants))out.participantIdentityIds=draft.participants;
  if(JSON.stringify(draft.requirements)!==JSON.stringify(initial.requirements))out.requirements=draft.requirements.map(r=>({phase:r.at??'both',kind:r.kind==='task'?'task_acceptance':r.kind==='receipt'?'handoff_receipt':'material_ready',targetId:r.ref,materialVersionId:r.kind==='evidence'?r.ref:undefined,hard:r.hard,label:p.text(r.label)}));
 }return out;};
 const requirementText=(list:Requirement[])=>list.map(r=>p.text(r.label)+' · '+p.t(r.at==='start'?'chatBeforeStart':r.at==='accept'?'chatBeforeAccept':'workCriteria')).join('\n');
 const submit=async()=>{if(stale||busy)return;const values=fields();if(!Object.keys(values).length){onClose();return}if(!directDraft&&!compare){setCompare(true);return}setBusy(true);setFailed('');try{const result=directDraft?await p.act('updateWorkDraft',{kind,id:item.id,expectedVersion:draft.version,fields:values}):await p.act('proposeWorkChange',{kind,id:item.id,expectedVersion:draft.version,fields:values,reason:p.t('taskDetailsConfirmChange')});if(result.ok){setDraft(initial);onClose();if(!directDraft)p.go({page:'hub',hubTab:'decisions',view:'decisions',id:undefined});}else setFailed(result.errorCode??'failed');}finally{setBusy(false);}};
 return <UIDialog wide title={p.t(compare?'taskDetailsConfirmChange':directDraft?kind==='task'?'taskDetailsDraftEdit':'taskDetailsPlanDraftEdit':kind==='task'?'taskDetailsChange':'taskDetailsPlanChange')} onClose={onClose} dismissable={!busy} footer={<div className="judex-task-dialog-actions"><Button variant="outline" disabled={busy} onPress={()=>compare?setCompare(false):onClose()}>{p.t('cancel')}</Button><Button variant="primary" data-testid="save-work-edit" isPending={busy} disabled={stale||!draft.title.trim()} onPress={()=>void submit()}>{p.t(directDraft?'taskDetailsSave':'taskDetailsSubmitChange')}</Button></div>}>
 <div className="judex-task-edit-form"><p className="judex-task-note">{p.t(directDraft?'taskDetailsDraftEditHint':'taskDetailsLiveEditHint')}</p>{(stale||failed)&&<UIWarning>{p.t('taskDetailsStale')}<Button size="sm" onPress={()=>{setDraft(v=>({...v,version:item.revision??1}));setFailed('');setCompare(true);}}><RotateCcw/>{p.t('taskDetailsRecheck')}</Button></UIWarning>}
 {compare?<table className="judex-task-compare"><thead><tr><th/><th>{p.t('taskDetailsCurrent')}</th><th>{p.t('taskDetailsProposed')}</th></tr></thead><tbody>{[{label:p.t('workTitle'),old:initial.title,next:draft.title},{label:p.t('taskDetailsDescription'),old:initial.description,next:draft.description},{label:p.t('workCriteria'),old:initial.criteria,next:draft.criteria},{label:p.t(kind==='task'?'taskDetailsParticipants':'coopOwner'),old:kind==='task'?initial.participants.map(label).join('\n'):label(initial.owner),next:kind==='task'?draft.participants.map(label).join('\n'):label(draft.owner)},{label:p.t('workReviewer'),old:label(initial.reviewer),next:label(draft.reviewer)},{label:p.t('taskDetailsPrerequisites'),old:requirementText(initial.requirements),next:requirementText(draft.requirements)}].filter(row=>row.old!==row.next).map(row=><tr key={row.label}><th>{row.label}</th><td>{row.old}</td><td>{row.next}</td></tr>)}</tbody></table>:<>
 <FormField label={p.t('workTitle')}><UIInput data-testid="edit-work-title" value={draft.title} onChange={e=>set({title:e.target.value})} maxLength={200}/></FormField><FormField label={p.t(kind==='task'?'taskDetailsDescription':'workGoal')}><UITextArea data-testid="edit-work-description" value={draft.description} onChange={e=>set({description:e.target.value})} rows={3}/></FormField><FormField label={p.t('workCriteria')}><UITextArea data-testid="edit-work-criteria" value={draft.criteria} onChange={e=>set({criteria:e.target.value})} rows={3}/></FormField>
 <FormField label={p.t(kind==='task'?'workReviewer':'coopOwner')}><UISelect value={kind==='task'?draft.reviewer:draft.owner} onChange={e=>set(kind==='task'?{reviewer:e.target.value}:{owner:e.target.value})}><UIOption value="">{p.t('workChooseSeat')}</UIOption>{seats.map(s=><UIOption key={s.id} value={s.id}>{label(s.id)}</UIOption>)}</UISelect></FormField>
 {task&&<><FormField label={p.t('taskDetailsParticipants')}><div className="judex-task-choice-list">{seats.map(s=><UICheckbox key={s.id} data-testid={'edit-participant-'+s.id} checked={draft.participants.includes(s.id)} onChange={e=>set({participants:e.target.checked?[...draft.participants,s.id]:draft.participants.filter(id=>id!==s.id)})}>{label(s.id)}</UICheckbox>)}</div></FormField><UIDisclosure title={p.t('taskDetailsPrerequisites')}><div className="judex-task-choice-list">{draft.requirements.map((r,i)=><div className="judex-task-requirement-edit" key={r.id}><span>{p.text(r.label)}</span><UISelect aria-label={p.t('taskDetailsPrerequisites')} value={r.at??'both'} onChange={e=>set({requirements:draft.requirements.map((v,n)=>n===i?{...v,at:e.target.value as Requirement['at']}:v)})}><UIOption value="start">{p.t('chatBeforeStart')}</UIOption><UIOption value="accept">{p.t('chatBeforeAccept')}</UIOption><UIOption value="both">{p.t('workCriteria')}</UIOption></UISelect><Button size="sm" onPress={()=>set({requirements:draft.requirements.filter(v=>v.id!==r.id)})}>{p.t('taskDetailsRemove')}</Button></div>)}{p.state.tasks.filter(t=>t.projectId===item.projectId&&t.id!==item.id&&!t.discardedAt).map(t=><UICheckbox key={t.id} checked={draft.requirements.some(r=>r.kind==='task'&&r.ref===t.id)} onChange={e=>set({requirements:e.target.checked?[...draft.requirements,{id:uid(),kind:'task',ref:t.id,at:'start',hard:true,label:t.title}]:draft.requirements.filter(r=>r.kind!=='task'||r.ref!==t.id)})}>{p.text(t.title)}</UICheckbox>)}</div></UIDisclosure></>}
 </>}</div></UIDialog>;
}
function ConfirmWork({item,mutation,onClose}:{item:Task|Plan;mutation:WorkMutation;onClose:()=>void}){
 const p=useWork(),remove=mutation.action==='delete',restore=mutation.action==='restore',version=item.revision??1,path=`/projects/${p.project.id}/${mutation.kind}s/${item.id}/`+(remove?'discard-review':'execution-review?operation='+mutation.action);
 const query=useQuery({queryKey:['work-review',p.mode,p.project.id,p.state.currentUserId??p.state.currentUser,item.id,mutation.action,version],enabled:p.mode==='api',queryFn:()=>request<DiscardReview|ExecutionReview>(path)});
 const live=p.mode==='api'?query.data:remove?demoDiscardReview(p.state,mutation.kind,item.id):demoExecutionReview(p.state,item.id,mutation.action as 'skip'|'restore');
 const [basis,setBasis]=useState<DiscardReview|ExecutionReview>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useWorkspaceDraft('work-exception-reason:'+item.id+':'+mutation.action,''),[waivers,setWaivers]=useState<ExceptionWaiver[]>([]),[ack,setAck]=useState(false);
 useEffect(()=>{if(!basis&&live)setBasis(live);},[live?.reviewHash]);
 const stale=!!basis&&(basis.targetVersion!==version||!!live&&basis.reviewHash!==live.reviewHash),impact=basis&&!('tasks' in basis)?basis:null,discard=basis&&'tasks' in basis?basis:null;
 const recheck=async()=>{const latest=p.mode==='api'?(await query.refetch()).data:live;if(latest){setBasis(latest);setWaivers([]);setAck(false);setError('');}};
 const confirm=async()=>{if(!basis||stale||busy)return;setBusy(true);setError('');try{const result=remove?await p.act('discardWork',{kind:mutation.kind,id:item.id,expectedVersion:basis.targetVersion,reviewHash:basis.reviewHash}):await p.act('executionException',{taskId:item.id,operation:restore?'restore':'skip',expectedVersion:basis.targetVersion,reviewHash:basis.reviewHash,reason,waivers,acknowledgeStarted:ack});if(result.ok){setReason('');onClose();if(remove){if(mutation.kind==='plan')p.go({page:'hub',hubTab:'plans',view:'plans',id:undefined,scopePlanId:undefined});else p.go({view:'plan',id:(item as Task).planId??undefined,activityId:undefined,taskSection:undefined});}}else setError(result.errorCode??'failed');}finally{setBusy(false);}};
 return <UIDialog wide title={p.t(remove?mutation.kind==='task'?'taskDetailsDelete':'taskDetailsPlanDelete':restore?'taskDetailsRestoreTitle':'taskDetailsSkipTitle')} onClose={onClose} dismissable={!busy} footer={<div className="judex-task-dialog-actions"><Button variant="outline" disabled={busy} onPress={onClose}>{p.t('cancel')}</Button><Button data-testid="confirm-work-mutation" variant={remove?'danger':'primary'} isPending={busy} disabled={!basis||stale||!!error||remove&&!!discard?.blockers.length||!remove&&(!reason.trim()||restore&&!!impact?.affectedTasks.some(t=>t.alreadyStarted)&&!ack)} onPress={()=>void confirm()}>{p.t(remove?'taskDetailsConfirmDelete':restore?'taskDetailsConfirmRestore':'taskDetailsConfirmSkip')}</Button></div>}>
 <div className="judex-task-edit-form"><strong>{p.text(item.title)}</strong><p className="judex-task-note">{p.t(remove?'taskDetailsDeleteHint':'taskDetailsExceptionScope')}</p>{query.isPending&&p.mode==='api'&&!basis&&<p role="status">{p.t('shellLoading')}</p>}{(query.isError||stale||error)&&<UIWarning>{p.t('taskDetailsStale')}<Button size="sm" onPress={()=>void recheck()}><RotateCcw/>{p.t('taskDetailsRecheck')}</Button></UIWarning>}
 {discard&&<>{mutation.kind==='plan'&&<p>{p.t('taskDetailsDeleteChildren',{count:discard.tasks.length})}</p>}<ul className="judex-task-check-list">{discard.tasks.map(t=><li key={t.taskId}><Check/>{t.title}</li>)}</ul>{discard.blockers.length>0&&<UIWarning>{p.t('taskDetailsCannotDelete')}<ul>{discard.blockers.map((b,i)=><li key={i}>{b.reason}</li>)}</ul></UIWarning>}</>}
 {impact&&<><FormField label={p.t('taskDetailsReason')}><UITextArea data-testid="execution-exception-reason" value={reason} onChange={e=>setReason(e.target.value)} rows={2}/></FormField><section><h3>{p.t('taskDetailsAffected')}</h3><div className="judex-task-affected-list">{impact.affectedTasks.map(t=><div className="judex-task-affected" key={t.taskId}><strong>{t.title}</strong>{!restore&&t.requirements.map(r=><UICheckbox key={r.id} checked={waivers.some(w=>w.taskId===t.taskId&&w.requirementId===r.id)} disabled={!r.hard} data-testid={'exception-waiver-'+t.taskId} onChange={e=>setWaivers(v=>e.target.checked?[...v,{taskId:t.taskId,requirementId:r.id,fingerprint:r.fingerprint??''}]:v.filter(w=>w.taskId!==t.taskId||w.requirementId!==r.id))}>{p.t('taskDetailsWaive')} · {p.t(r.phase==='start'?'chatBeforeStart':r.phase==='accept'?'chatBeforeAccept':'taskDetailsBothPhases')}</UICheckbox>)}{restore&&t.alreadyStarted&&<span className="judex-task-meta">{p.t('taskDetailsStartedHint')}</span>}</div>)}</div><p className="judex-task-meta">{p.t('taskDetailsOtherConditions')}</p>{impact.referencingPlanIds.length>0&&<p className="judex-task-note">{p.t('taskDetailsReferencePlans')}</p>}{!restore&&impact.affectedTasks.some(t=>t.requirements.some(r=>r.hard&&!waivers.some(w=>w.taskId===t.taskId&&w.requirementId===r.id)))&&<p className="judex-task-warning"><Lock/>{p.t('taskDetailsUnwaived')}</p>}{restore&&impact.affectedTasks.some(t=>t.alreadyStarted)&&<UICheckbox data-testid="exception-acknowledge" checked={ack} onChange={e=>setAck(e.target.checked)}>{p.t('taskDetailsAcknowledge')}</UICheckbox>}</section></>}
 </div></UIDialog>;
}
