import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const root = fileURLToPath(new URL("../", import.meta.url));
const cache = path.join(root, ".cache/api-generation");
fs.mkdirSync(cache, { recursive: true });
const generatedGo = execFileSync("go", ["tool", "oapi-codegen", "-generate", "types", "-package", "apigen", "api/openapi.yaml"], { cwd: root, encoding: "utf8", maxBuffer: 16 << 20 });
const goInput = path.join(cache, "types.go");
fs.writeFileSync(goInput, generatedGo);
execFileSync("go", ["run", "./tools/split-api", goInput, "internal/gen/api"], { cwd: root, stdio: "inherit" });

const source = astToString(await openapiTS(new URL("./openapi.yaml", import.meta.url)));
const ast = ts.createSourceFile("schema.d.ts", source, ts.ScriptTarget.Latest, true);
const directory = path.join(root, "web/src/lib/api");
const banner = "/** Generated by api/generate-types.mjs. Do not edit. */\n";
const names = ast.statements.filter(ts.isInterfaceDeclaration).map((node) => node.name.text);
const rootImports = [];
const declarations = [];
const outputs = new Map();
const pendingParts=[];
function partition(name,input){
 const groups=[];let members=[],lines=0;
 for(const member of input){let text=member.getFullText(ast),size=text.split("\n").length;
  if(size>1800&&ts.isPropertySignature(member)&&member.type&&ts.isTypeLiteralNode(member.type)){
   const key=member.name.getText(ast).replace(/[^a-zA-Z0-9]/g,"");
   const nested=`Schema${name[0].toUpperCase()}${name.slice(1)}${key[0].toUpperCase()}${key.slice(1)}`;
   const parts=partition(nested,member.type.members);names.push(nested);
   declarations.push(`export interface ${nested} extends ${parts.join(", ")} {}`);
   const start=member.getFullStart();text=text.slice(0,member.type.getStart(ast)-start)+nested+text.slice(member.type.getEnd()-start);size=text.split("\n").length;
  }
  if(size>1800)throw new Error(`Generated member ${name} exceeds line limit`);
  if(lines+size>1800&&members.length){groups.push(members);members=[];lines=0}
  members.push(text);lines+=size;
 }
 if(members.length)groups.push(members);
 return groups.map((group,index)=>{const type=`Schema${name[0].toUpperCase()}${name.slice(1)}${index}`,file=`schema-${name}-${index}`;pendingParts.push({file,type,group});rootImports.push(`import type { ${type} } from "./${file}";`);return type;});
}
for (const node of ast.statements) {
  if (!ts.isInterfaceDeclaration(node)) { declarations.push(node.getText(ast)); continue; }
  const name = node.name.text;
  const parts=partition(name,node.members);
  declarations.push(`export interface ${name}${parts.length ? ` extends ${parts.join(", ")}` : ""} {}`);
}
for(const {file,type,group} of pendingParts)outputs.set(file+".d.ts",banner+`import type { ${names.join(", ")} } from "./schema";\nexport interface ${type} {\n${group.join("\n")}\n}\n`);
outputs.set("schema.d.ts", banner + rootImports.join("\n") + "\n" + declarations.join("\n") + "\n");
for (const file of fs.readdirSync(directory)) {
  if (/^schema-.*\.d\.ts$/.test(file) && !outputs.has(file)) fs.unlinkSync(path.join(directory, file));
}
for (const [file, content] of outputs) {
  if (content.split("\n").length > 2000) throw new Error(`${file} exceeds 2000 lines`);
  fs.writeFileSync(path.join(directory, file), content);
}
console.log(`Generated ${outputs.size} TypeScript files and partitioned Go types.`);
